### ISSUE TITLE
_.wrap doesn't support wrapping function with argument

### ISSUE THREAD

**Issue by umarfarooq125** [jashkenas/underscore#1009]
Today while writing code using underscore and backbone i had to wrap some functions. I saw following example on underscorejs.org

var hello = function(name) { return "hello: " + name; };
hello = _.wrap(hello, function(func) {
  return "before, " + func("moe") + ", after";
});
hello();
=> 'before, hello: moe, after'

on the second last line 
what if the function call is like 
hello("umar");
I means to say that arguments are coming from outside.

**Comment by zarehb** [comment]
it seems underscore _wrap only supports one parameter , use this instead:


fn = (function(fn,before,after, self) {
				return function() {
					if(before) before.apply(self,arguments);
					var res = fn.apply(self,arguments);
					if(after) after.apply(self,arguments);
					return res;
				}
			})(fn, before, after, this )

**Comment by megawac** [comment]
You can also use partial for that zarehb

**Comment by zarehb** [comment]
tnx megawac, partial is more for pre-filling the arguments not calling a before and after function

**Comment by megawac** [comment]
```js
fn = _.partial(function(fn, before, after, self) {
	var args = _.rest(arguments, 4);
	if (before) before.apply(self,args);
	var res = fn.apply(self,args);
	if (after) after.apply(self,args);
	return res;
})(fn, before, after, this )
```

**Comment by zarehb** [comment]
that's correct and it will work, but in case anyone wants a pure js solution can take mine specially that using underscore doesn't give you any benefit in this case!
