### ISSUE TITLE
_.object with single value

### ISSUE THREAD

**Issue by jacobsandlund** [jashkenas/underscore#1021]
I'm finding I often have code that looks like this:

``` javascript
var hash = {};
_.each(list, function (item) {
  hash[item.keyOfSorts] = defaultValue;
});

// later
if (hash[item.keyOfSorts] === defaultValue)
...
hash[item.keyOfSorts] = otherValue;
```

Since `_.object` already takes an array and converts it to an object, it could be a way to create the initial hash. Right now, though, the code looks like this:

``` javascript
var hash = _.object(_.map(list, function (item) {
  return [item.keyOfSorts, defaultValue];
}));
```

It would be easier if `_.object` could take a singular value as the second argument:

``` javascript
var hash = _.object(_.pluck(list, 'keyOfSorts'), defaultValue);

// or with the item being the key:
var hash = _.object(list, defaultValue);
```

The downside is that anyone thinking they could set every key to the same array by
doing `_.object(list, array)` will be surprised. I don't see that being something anyone would want to do.

**Comment by estani** [comment]
I use this list to hash conversion a lot for fast lookups. Most of the time this is enough:
```javascript
    var list = ['id1', 'id2', 'id3'];
    var hash = _.object(list, [undefined]);
    // hash -> {id1:undefined, id2:undefined, id3:undefined};
```
which allows a lookup in O(1) by doing `'id4' in hash`. Sometimes it would be nicer to allow for `if (hash.id1) {...}` which would work if the default value were true. Something like:
```javascript
    _.object(list, true);
```
or more flexible with:
```javascript
    _.object(list, function(){return true});
```
is there a better way of doing this?

**Comment by Florian-R** [comment]
@estani If you don't have a lot of lookups, my gut feeling is that using `_.contains` will be much more efficient (and cleaner).

If you do a lot of lookups on the same list and you know the overhead of the initial `_.object` is worth it, you might want to do something like : 

```
var list = ['id1', 'id2', 'id3'];
var hash = _.object(list, _.times(list.length, () => true));
// hash -> {id1:true, id2:true, id3:true}
```
