### ISSUE TITLE
_.without to accept array as second argument

### ISSUE THREAD

**Issue by ondrejhlavacek** [jashkenas/underscore#104]
The current definition of _.without accept array as the first argument and then any number of following args. I know it might get tricky, but it would be helpful, if I could pass another array as argument. 

The new functionality would work as 
    _.without([1,2,3], [1, 2])
returns
    [3]

As far as I know _.without does not work deep, so it might not be overcomplicated - 
    _.without([1,2,3,[1]], [1], 1)
returns
    [2, 3, [1]]

**Comment by addisonbgross** [comment]
For those who find their way here.... _.difference([0, 1, 3, 9], [1, 3]); // => [0, 9]

**Comment by agwidarsito** [comment]
I know this is closed, but ES6's splat operator will help with this ;)

**Comment by rally25rs** [comment]
For anyone who doesn't want to search for ES6 spread operator that @agwidarsito mentioned, what he is saying is that you can do this in ES6:

```
const items = [1,2,3,4];
const itemsToRemove = [3,4,5];
const result = _.without(items, ...itemsToRemove);
// result is [1,2]
```
