### ISSUE TITLE
_.where() to find multi level keys

### ISSUE THREAD

**Issue by skmasq** [jashkenas/underscore#1207]
I stumbled upon problem where I wanted to do this

``` javascript
var objectList = [
{
    type: 1
},
{
    config: {
        type: 2
    }
},
{
    name: "super"
}]
```

in result getting

``` javascript
[{ config: { type: 2 } }]
```

Only way I can do this is by using something like this

``` javascript
_.filter(objectList, function(v){ 
    return _.isObject(v.config) && v.config.type == 2; 
});
```

**But would it be possible to do something like this?**

``` javascript
_.where(objectList,{config: {type: 2}})
```

**Comment by usman250994** [comment]
I have created a package/ function which can search deep down in nested Object or in array of nested Objects. and returns the required key/s and value/s. as a new object. Please have a look to it.

Even if you have multiple occurances of a same name key. It will return an array of all values as the value of that key name.
Please have look to the demo as well
https://www.npmjs.com/package/uas-get-my-keys
https://github.com/usman250994/getMyKeys
