### ISSUE TITLE
Documentation for `compose` is not clear about the order of execution

### ISSUE THREAD

**Issue by rtpg** [jashkenas/underscore#1236]
Here's the current example for `compose`:

```
var greet    = function(name){ return "hi: " + name; };
var exclaim  = function(statement){ return statement + "!"; };
var welcome = _.compose(exclaim, greet);
welcome('moe');
=> 'hi: moe!'
```

The problem with this example (actually referenced in issue #110 , surprised it wasn't fixe) is that the example is commutative: `_.compose(exclaim,greet)==_.compose(greet,exclaim)`

maybe if we were to do something like change `exclaim` to:

`var exclaim = function(statement) { return statement.toUpperCase(); };`

then we'll have:

```
welcome('moe');
=> 'HI: MOE'
var backwards = _.compose(welcome,exclaim);
backwards('moe');
=> 'hi: MOE'
```

**Comment by am** [comment]
After trying to replace loadash 'flow' with underscore 'compose' and realising that it doesn't work the same way. Reading the documentation carefully helps, but still got there after finding this issue.

Maybe this sound stupid, but "funcitons are executed on reverse order." statement would alleviate the symptom =P
