### ISSUE TITLE
_.chain & _.each are not playing together?

### ISSUE THREAD

**Issue by LeonFedotov** [jashkenas/underscore#1391]
Hi I'm not sure but I think this is a bug: 

```
  _.chain([1,2,3,4]).each(function(current){ console.log(current) }).value(); // returns undefined
  //where: 
  _.chain([1,2,3,4]).map(function(current){ return current; }).value() // returns expected. 
```

I guess chained function have to return values but then tap is not an iterable, im looking for a way to access the values without un-chaining them and without mutation.

**Comment by dwilches** [comment]
Is there now an alternative method that can be chained and allow modifying elements of an array in place? I was searching for something like a `peek`:

    _.chain(myArray)
        ...
        .peek(e -> e.craftedVar = e.otherVar * 2)
        ...
        .value();
