### ISSUE TITLE
_.union for empty array

### ISSUE THREAD

**Issue by OpenSiteMobile** [jashkenas/underscore#1506]
Hi,

Is this the correct output for _.union()?

_.union([], [1, 2, 3]); // => [undefined, 1, 2, 3];

I'm guessing it is, but this only seemed to appear after I downloaded the latest (v1.6.0) version of underscore.js. Not saying it isn't caused by my code somewhere, but couldn't track it down to anything else.

**Comment by spk2piyu** [comment]
this[this.glob] = typeof(this[this.glob]) != "undefined"  ? _.union(this[this.glob], oldImages) : oldImages;
