### ISSUE TITLE
_.intersection should ignore non-array values.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1514]
I noticed that the arrays method `_.intersection` allows object values while others, like `_.union`, ignore them.

``` js
_.intersection([1,2], {'0': 1 });
// => [1];

_.union([1,2], {'0': 3 });
// => [1, 2]
```

I know there was [recent work](https://github.com/jashkenas/underscore/pull/1428) to ignore non-array/arguments for `_.union` and `_.difference`, and others. I think this falls into that bucket.

**Comment by BSteephenson** [comment]
What behavior do you propose instead? Should it just pass over the object?
```
_.intersection([1,2], {'0': 1 });
// => []
or 
// => [1,2]

**Comment by olleboll** [comment]
Is this still Open as in you want this implemented? I've made a solution that simply ignores arguments that aren't arrays and would love to contribute, even though it's very basic :)

**Comment by jgonggrijp** [comment]
This would be a breaking change, which would mean it could not happen until 2.0. In 2.0, however, the set operations should operate on actual `Set`s, which makes the point moot. Closing for this reason.
