### ISSUE TITLE
Underscore.js uses "new Function()". Needs to be replaced in order to let Undescore.js work with Content Security Policy (CSP)

### ISSUE THREAD

**Issue by admix** [jashkenas/underscore#1522]
Content Security Policy (CSP) doesn't allow to use eval() & new Function.
"new Function" used here-> https://github.com/jashkenas/underscore/blob/master/underscore.js#L1298
Evaluating strings of JavaScript like this is a common XSS attack vector.
Would be really great if "new Function" could be replaced with safe code.

**Comment by ConcatenatedNonsense** [comment]
This issue may lead to our removal of your library from our projects; non-adherence to safe coding guidelines and policies is not acceptable at this point in time.

Have you released an updated version which addresses this issue?

**Comment by michaelficarra** [comment]
@ConcatenatedNonsense Pull requests welcome.
