### ISSUE TITLE
_.intersection should work with arrays regardless of if the first arg is an array

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1583]
Currently `_.intersection(null, [1, 2, 3]);` returns an empty array `[]` but it should return `[1, 2, 3]` just as `_.intersection(null, [1, 2], null, [2, 3])` should return `[2]`.

This would allign with the current behavior of `_.union` which `_.union(null, [1, 2], null, [3]);` returns `[1, 2, 3]`.

**Comment by jashkenas** [comment]
The intersection of nothing and something is nothing. The union of nothing and something is something. I think the current behavior is the correct behavior.
