### ISSUE TITLE
Separate concerns of `arguments` object tests.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1584]
I noticed a few `arguments` objects test in test/arrays.js use the OO-style syntax when it's not relevant to the test.

They are [here](https://github.com/jashkenas/underscore/blob/6ddd517d745c5cde3fe7eb009609d51d6a2829a2/test/arrays.js#L27), [here](https://github.com/jashkenas/underscore/blob/6ddd517d745c5cde3fe7eb009609d51d6a2829a2/test/arrays.js#L31), [here](https://github.com/jashkenas/underscore/blob/6ddd517d745c5cde3fe7eb009609d51d6a2829a2/test/arrays.js#L40), and [here](https://github.com/jashkenas/underscore/blob/6ddd517d745c5cde3fe7eb009609d51d6a2829a2/test/arrays.js#L50).

**Comment by jashkenas** [comment]
That's ok — no harm, no foul.
