### ISSUE TITLE
Each iterates badly when it contains the `length` field

### ISSUE THREAD

**Issue by sgenoud** [jashkenas/underscore#1590]
Each iterates correctly on most objects:

```.js
_.each({a:2}, function(value, key) { console.log('value: ' + value + ', key:' + key) });
value: 2, key:a 
```

It fails if the object contains a `length` property:

```.js
_.each({a:2, length:4}, function(value, key) { console.log('value: ' + value + ', key:' + key) });
value: undefined, key:0
value: undefined, key:1
value: undefined, key:2
value: undefined, key:3 
```

The source of the bug is that the object is considered an "Array-like": https://github.com/jashkenas/underscore/blob/master/underscore.js#L69

**Comment by jashkenas** [comment]
Closing this ol' ticket down — in the absence of `arrayMap`, `arrayFilter` etc ... just doing an `arrayEach` doesn't seem like a good idea.

**Comment by YuriGor** [comment]
Hi folks, so is there any workaround to fix this?
I have to iterate over echarts3 options object recursively, and there are a LOTS of 'length' keys so I fail often.
