### ISSUE TITLE
_.contains does not work for arrays

### ISSUE THREAD

**Issue by joaomilho** [jashkenas/underscore#1615]
So contains does not work for array...

``` js
_.contains([[]], [])
=> false

_.contains([[1]], [1])
=> false
```

Since arrays are broken...

``` js
[] == []
=> false

[] === []
=> false

[1] === [1]
=> false
```

Anyway it's pretty misleading not to work with arrays... any thoughts?

**Comment by allenan** [comment]
It seems like there should be a more natural way to test if an array includes values from a sub-array. If the implementation of includes/contains is not intended to handle this case, what about a `_.containsAll(collection, [value1, value2])` method?
