### ISSUE TITLE
Deep Extend and Deep Copy

### ISSUE THREAD

**Issue by jscheel** [jashkenas/underscore#162]
Feature Request:
Would it be possible to either have a boolean parameter on `_.extend()` and `_.copy()` to make them deep, or to have separate deep methods?

**Comment by fov42550564** [comment]
_.deepClone = function(obj) {
    if(!obj || typeof obj == 'function' || _.isDate(obj) || typeof obj != 'object') {
      return obj;
    }
    var retVal, i;
    if(_.isArray(obj)){
      retVal = [];
      for(i = 0; i < obj.length; ++i){
        retVal.push(_.deepClone(obj[i]));
      }
      return retVal;
    }
    retVal = {};
    for(i in obj){
      if(!(i in retVal) || retVal[i] != obj[i]) {
        retVal[i] = _.deepClone(obj[i]);
      }
    }
    return retVal;
  };

**Comment by luncht1me** [comment]
We run into a use case a lot in our work environment that would benefit from deep cloning.

Sometimes, you have to do database migration, when features of a complicated web app are updated and expanded to a new paradigm. A Deep copy of our data is very helpful when having to do operations like generating hashes from the data when the original reference is preferred to not be manipulated. I don't think a single document in our massive database is 'flat'. Nested properties exist everywhere. 

Also, sometimes you want to send a copy of an object to a different service within your web application, to be operated on before deciding what to do with it. Having the nested properties by reference defeats the purpose of having a cloned object. The WHOLE point, imo, of a cloned object is to leave the original reference in tact. 

I'm sure there's a decent way to go about this where an object can be navigated to it's depths, then reconstructed from the deepest layer up to the root.

**Comment by seyfer** [comment]
Lodash has it - https://lodash.com/docs/4.17.5#cloneDeep
