### ISSUE TITLE
Adding a "deep" argument to _.contains() and _.difference()

### ISSUE THREAD

**Issue by ckosmowski** [jashkenas/underscore#1789]
When i try to find the difference between two arrays containing objects i.e;

```
var array1 = [{
    name: "Peter",
    age: 27
}];

var array2 = [{
    name: "Peter",
    age: 27
},{ 
    name: "Max",
    age: 23
}];

var diff = _.difference(array2, array1);

```

I would expect diff to be:

```
{ 
    name: "Max",
    age: 23
}
```

but it actually yields both elements of `array2`. This is because the implementation of `_.contains()` uses the strict equality operator rather than `_.isEqual()` to compare the elements.

My suggestion would be to add a boolean parameter `deep` to `_.difference()` and `_.contains()` which controls wether or not `_.isEqual()` should be used for comparison?

What do you think?

If you agree i would also like to add a pull request for that.

**Comment by fwoelm** [comment]
Did this ever evolve into anything? I was looking for a similar method (deep diff) today and was very excited when I found an [amazing JS fiddle doing exactly that](http://jsfiddle.net/drzaus/9g5qoxwj/). If it does not already exist, then I think it would be a valuable addition to Underscore.js.

I don't think I'm the right person to propose the addition, but just putting this here in case anyone finds themselves in the same situation I was in.

PS: :+1:  awesome work on Underscore.js! Thanks so much :)
