### ISSUE TITLE
Avoid Function.prototype additions on initial `mixin` setup.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1851]
I'm not sure if I've brought this up before (couldn't find an issue). In any case, currently Underscore calls `_.mixin(_);` to initialize its chaining API, however that has a side effect of picking up additions to the `Function.prototype`.

I've seen this when combined with Ember which adds `Function.prototype` methods (`observes`, `observesBefore`, `observesImmediately`, `on`, & `property`) by default. See an example [here](http://jsbin.com/munupi/1/).

For 2.0 this can be avoided doing `_.mixin(_.extend({}, _))` or by making `_.mixin` only use own properties of the source value.

**Comment by jashkenas** [comment]
I don't think we should change this — `mixin` should take all of the properties from the passed in object, not just the own properties.
