### ISSUE TITLE
Issue with sorting in _.sortBy.

### ISSUE THREAD

**Issue by eraser88** [jashkenas/underscore#1879]
If i have objects like these : 
`[{"1", 100}, {"1", 1}, {"1", 2}, {"1", 200}]`
If i sort the elements using both the columns then the result should be :
`[{"1", 1}, {"1", 2}, {"1", 100}, {"1", 200}]`
But in the current code the result that is displayed is :
`[{"1", 1}, {"1", 100}, {"1", 2}, {"1", 200}]`

Which i think is an issue ?

**Comment by jgonggrijp** [comment]
Closing for the reasons discussed in #1880 and #2846.
