### ISSUE TITLE
2.0 chaining behavior

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1896]
There's a couple things that you all may want to consider for 2.0:

* Intuitive chaining
* Deferred execution + shortcut fusion

Intuitive chaining would allow chaining to kick off as soon as the `_(...)` wrapper is used without requiring the `.chain()` method call.

So chaining would follow a behavior similar to jQuery where a wrapped value is returned unless you're resolving a value. For example:
```js
var array = _.range(100);
_(array).filter(...).value();  // => the filtered array
_(array).map(...).reduce(...); // => the reduced value
_(array).map(...).first();     // => the first value
```

The `chain()` method could still be used to force explicit chaining
```js
_(array).chain().first().value(); // => the first value
```

Deferred execution means that while creating the chain the methods are queued but not executed until an explicit or implicit `value()` is requested. For example:

```js
// actions are queued, but not performed
var a = _(array).map(...).filter(...);
// actions now are performed
var r = a.value(); // => the filtered array
```

With deferred execution in place shortcut fusion becomes possible. Shortcut fusion involves reducing the number of iterations when ultimately wanting a smaller portion of results. For example:

```js
// normally
_(array)
  .chain()
  .map(function(v) { console.log('map'); return v * 2; })
  .filter(function(v) { console.log('filter'); return v % 2 === 0; })
  .take(5)
  .value();
// logs `map` 100 times
// logs `filter` 100 times
// => [0, 2, 4, 6, 8]
```
but with shortcut fusion the iteratees of `map` and `filter` are composed so that instead of iterating all elements of `array` for `map` and then again for `filter` its taking the first `5` that pass `filter(map)`.
```js
// with shortcut fusion
_(array)
  .chain()
  .map(function(v) { console.log('map'); return v * 2; })
  .filter(function(v) { console.log('filter'); return v % 2 === 0; })
  .take(5)
  .value();
// logs map, filter, map, filter, map, filter, map, filter, map, filter
// for a total of 10 iterations instead of 200
// => [0, 2, 4, 6, 8]
```

**Comment by jashkenas** [comment]
> I'm all for a transducer-style implementation to give us stream fusion during chaining.

Cool. I'd love to see what this would look like as a pull request — how intrusive or bulky it would be. Let's move this conversation over to a PR, if one happens. As a parallel with `chain()`, perhaps something like: 

    _(bigArray).lazy()
      .map, function(v) { return v * 2; })
      .filter, function(v) { return v > 50; })
      .first(5)
      .value();
