### ISSUE TITLE
_.debounce() loses event.currentTarget

### ISSUE THREAD

**Issue by jezen** [jashkenas/underscore#1905]
I am unable to get the `event.currentTarget` when using `addEventListener` with `_.debounce()`.

[Here’s a fiddle](http://jsfiddle.net/v0fpm4c8/).

**Comment by samrispaud** [comment]
@jridgewell any idea how to get around this in a React onChange. when i don't use debounce I am able to access the proper event in my onChange function but when I use `_.debounce` I lose the proper `event` – see below

```
// in my render
<input onChange={ _.debounce(this.updateNote.bind(this), 500) } />
```

```
// my change handler
updateNote(event) {
    // undefined on event.target, get lodash event not <input/> event target
    const note = event.target.value
    this.sendNote({ note })
 }
```

**Comment by jridgewell** [comment]
See my [second suggestion](https://github.com/jashkenas/underscore/issues/1905#issuecomment-60306121).

**Comment by jacobhobson** [comment]
This is a matter of implementation. You need to persist the event. onChange should call a persist and THEN pass the persisted event to the debounced handler:

`
onChange_persist = (e) =>
{
    e.persist();
    e.onChange_debounced(e);
}
`
