### ISSUE TITLE
_.safeMixin?

### ISSUE THREAD

**Issue by joshuacc** [jashkenas/underscore#1920]
It would be nice for mixin libraries like contrib if there were a way to mixin methods without clobbering the existing methods on `_`.

### Use cases:

1. When Underscore adds a new method with a name that already exists in contrib, using `_.mixin` will result in clobbering the Underscore method. I think in most cases it would be preferable to default to using the core methods by using something like `_.safeMixin`, and then allow users to override the core method with `_.mixin`if they really need to.
2. When using multiple mixin libraries, if there is a name conflict, the last mixin always wins. It would seem preferable to leave the first method in place and allow the user to explicitly choose to override if necessary.

Thoughts?

**Comment by jashkenas** [comment]
Mixins are inherently "unsafe" in this way — they're about sharing a namespace. If you want to be safe — don't share a namespace.

At the point where you need to know about using `mixin` vs. `safeMixin` ... you already probably know which version of the function you should be calling or what name to safely add it under. I don't think the use case merits the addition.
