### ISSUE TITLE
Templates broken in 1.7

### ISSUE THREAD

**Issue by acl0056** [jashkenas/underscore#1928]
It seems like the API for templates changed.  Not sure if that is considered a feature, but I would consider it a bug as it breaks everything I have ever done with underscore templates.

The issue is that I can no longer pass in data and get the rendered template back.  It now returns a function instead of a string.

**Comment by cancerberoSgx** [comment]
And I thought if there was one js library I wound't have compatibility problems would be underscore.... and in a minor version !!! there are no excuses for this...  :(
