### ISSUE TITLE
_.defaults should have for-in fixes

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1984]
`_.defaults` should have `for-in` fixes like `_.extend`.

**Comment by jmrog** [comment]
Meager newb to the underscore.js source here, so feel free to shoot me down! :)

Anyway, this seems like a good idea to me and a fairly easy change to make, unless I'm missing something. Two suggestions. One is to simply call `_.keysIn` or `_.keys` (depending on which exact behavior we want) in `_.defaults` itself, as in:

```javascript
  _.defaults = function(obj) {
    if (!_.isObject(obj)) return obj;
    for (var i = 1, length = arguments.length; i < length; i++) {
      var source = arguments[i],
            keys = _.keysIn(source), // or _.keys(source), depending on whether we want only "own" keys here
            l = keys.length;
      for (var j = 0; j < l; j++) {
        var key = keys[j];
        if (obj[key] === void 0) obj[key] = source[key];
      }
    }
    return obj;
  };
```

That solution duplicates a lot of the functionality already provided by the `createAssigner` internal function, though. It doesn't look like we can easily make use of `createAssigner` for `_.defaults` as it is, but maybe a small modification to `createAssigner` is in order: have it take a second (Boolean) argument that tells it whether to only assign properties/values when the property is undefined, as in:

```javascript
  var createAssigner = function(keysFunc, undefinedOnly) {
    return function(obj) {
      var length = arguments.length;
      if (length < 2 || obj == null) return obj;
      for (var index = 0; index < length; index++) {
        var source = arguments[index],
            keys = keysFunc(source),
            l = keys.length;
        for (var i = 0; i < l; i++) {
          var key = keys[i];
          // not sure about the preferred coding style below; input welcome
          if ((undefinedOnly && obj[prop] === void 0) || !undefinedOnly) {
            obj[key] = source[key];
          }
        }
      }
      return obj;
    };
  };

  // ... and then ...
  
  _.defaults = createAssigner(_.keysIn, true); // or use _.keys, depending on which is preferred
```

The second option would require a very small  (non-breaking, AFAICT) addition of a conditional check to `createAssigner` but would have the benefit of making the creation of `_.defaults` nearly identical to the creation of `_.extends` and `_.assign`. 

Thoughts? I'm happy to create a pull request for either of these, but don't to immediately do that, being a newb.

**Comment by jridgewell** [comment]
> Thoughts? I'm happy to create a pull request for either of these, but don't to immediately do that, being a newb.

I think the `undefinedOnly` is a great solution. :+1: 

My only suggestion: the if conditional could be simplified

```javascript
if (!undefinedOnly || obj[key] === void 0) obj[key] = source[key];
```

**Comment by megawac** [comment]
Yep, do it @jmrog

**Comment by jmrog** [comment]
Okay, thanks guys. I've submitted the pull request, with the small change mentioned by @jridgewell  (good call!). 

Sorry about the multiple references showing up above this comment; was having some issues with git. The first commit reference above (5c58807) should be ignored. It doesn't affect the later commit and doesn't even exist anymore; didn't expect that it would still be showing up here.
