### ISSUE TITLE
_.isMatch

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1985]
There's been a request for a function like `_.matches` that accepts the object to compare to without having to create the function. So kind-of like `_.isEqual`. Do you all have thoughts on an  `_.isMatch` method that accepts an object and a source to compare it against?

```js
var object = {'a':1,'b':2,'c':3};
var source = {'b':2};
_.isMatch(object, source);
// => true
```

**Comment by jashkenas** [comment]
-> #2057
