### ISSUE TITLE
_.matches and _.isEqual behavior

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1986]
Thoughts on aligning `_.matches` behavior closer to `_.isEqual` by matching only own properties of objects? This would allow easier adoption in the future for partial deep equality comparisons.

**Comment by amZotti** [comment]
:+1:

**Comment by jashkenas** [comment]
I think `matches` should simply check properties. After all, you can access them just the same. Doing only "own" properties would be incorrect.
