### ISSUE TITLE
Collections should not iterate functions as array-likes

### ISSUE THREAD

**Issue by megawac** [jashkenas/underscore#1992]
I brought this up in https://github.com/jashkenas/underscore/pull/1990#issuecomment-68230946 and https://github.com/jashkenas/underscore/issues/1590#issuecomment-42617297

I think all the collection methods should not iterate functions as `arrays` but as `objects`. I would like to address this in #1990

``` js
_.each(_, console.log.bind(console));
```

**Comment by akre54** [comment]
How is `_.each(_.functions(_), console.log.bind(console))` not clearer? Implicitly treating functions as a grab bag of key-val pairs is a mistake, in my opinion.

**Comment by megawac** [comment]
I think that makes more sense than trying to access `_[0], _[1]` etc by indexes. (I don't think that ever makes sense)

**Comment by akre54** [comment]
Agreed but my point is that we shouldn't be anticipating every single value that could potentially be passed to a collection method. `_.each` is undefined for functions, just pass an array instead. I feel like all these edge cases we're supporting "because we can" are bloating and hobbling the API.

**Comment by jdalton** [comment]
> Agreed but my point is that we shouldn't be anticipating every single value that could potentially be passed to a collection method

This isn't anticipating every single value it's taking a pretty common type, function, and handling it in a more intuitive way. 

> I feel like all these edge cases we're supporting "because we can" are bloating and hobbling the API.

It's not bloating or hobbling the API. It's a more natural behavior than the existing one.

**Comment by akre54** [comment]
And then what about Dates or class instances? Where do you draw the line
fixing unsupported behavior?

**Comment by jridgewell** [comment]
> And then what about Dates or class instances? Where do you draw the line fixing unsupported behavior?

I think this is the only common instance with a (surprising) `length` property?

**Comment by jdalton** [comment]
What @jridgewell said :)

**Comment by jgonggrijp** [comment]
Closing because of #2830.
