### ISSUE TITLE
_.runInContext

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2001]
Thoughts on having `_.runInContext` to create pristine Underscore instances that are safe to mixin and aid in mocking?

```js
_.mixin({ 'add': function(a, b) { return a + b; } });

var u = _.runInContext();
u.mixin({ 'sub': function(a, b) { return a - b; } });

_.isFunction(_.add);
// => true
_.isFunction(_.sub);
// => false

u.isFunction(u.add);
// => false
u.isFunction(u.sub);
// => true
```
```js
// using `context` for mocking timers
var u = _.runInContext({
  'Date': function() {
    return { 'getTime': getTimeMock };
  }
});

// or creating a suped-up `defer` in Node
var defer = _.runInContext({ 'setTimeout': setImmediate }).defer;
```

**Comment by jdalton** [comment]
Naming inspired by http://nodejs.org/api/vm.html#vm_vm_runincontext_code_context_filename.

**Comment by stoeffel** [comment]
:+1:

**Comment by jashkenas** [comment]
I dunno. It seems like `noConflict` covers the actual use case for this — if your scripts are cooperating, then you want to share mixins ... and if you're not cooperating, then you want to `noConflict`.

Perhaps if there was a good use case for this, outside of testing Underscore.
