### ISSUE TITLE
doc for _.range

### ISSUE THREAD

**Issue by pdavidow** [jashkenas/underscore#2002]
http://underscorejs.org/#range
Explanation of 'stop' should make it crystal clear that end value is not included.

Returns a list of integers from start to stop
=>
Returns a list of integers from start up to but not including stop

**Comment by megawac** [comment]
Sounds good, feel free to submit a pull request

**Comment by amZotti** [comment]
I have submitted a pull request for resolving this issue 

https://github.com/jashkenas/underscore/pull/2035
