### ISSUE TITLE
_.reduce error 

### ISSUE THREAD

**Issue by TSteele27** [jashkenas/underscore#2004]
If you try to run reduce on an empty array it will cause an error. One would expect the function to just return an empty array, not throw an error.

**Comment by michaelficarra** [comment]
Did you not provide an initial value for the reduction?

> One would expect the function to just return an empty array

No, one wouldn't. At least, no one should. The result of a reduction has nothing to do with the fact that your reducing an array. It is only related to the initial value, the reducing function, and the array elements.

**Comment by jdalton** [comment]
LOL @michaelficarra. @TSteele27 This has been fixed in edge.

**Comment by michaelficarra** [comment]
@jdalton what do you mean by fixed? It returns an undefined value, no? If reduce on an effort array  without an initial value returns an empty array, I will be very confused.

**Comment by TSteele27** [comment]
The function was part of a chain, the previous steps ended up in an empty set, so when reduce ran it threw an error complaining about an empty set, either way I don't think that throwing an error is the best way to deal with this case. This is in version 1.5.2 so it may be fixed in newer version, but I didn't see a bug report for it.

**Comment by megawac** [comment]
#1858
