### ISSUE TITLE
_.toPlainObject

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2007]
With recent issues around iterating source object properties in `_.assign` and `_.extend` a method like `_.toPlainObject` may be useful. It would convert an objects enumerable inherited & own properties to a plain object of own properties:

```js
function Foo() { this.b = 2; };
Foo.prototype.c = 3;

Object.assign({ 'a': 1 }, new Foo);
// => { 'a': 1, 'b': 2 }
Object.assign({ 'a': 1 }, _.toPlainObject(new Foo));
// = > { 'a': 1, 'b': 2, 'c': 3 }
```

The name `toPlainObject` aligns with jQuery's and Lo-Dash's concept of a plain objects and their `isPlainObject` methods as well as avoids confusion with the [existing behavior](http://es5.github.io/#x15.2.1.1) of `Object('foo')`.

**Comment by megawac** [comment]
Underscore didn't scope `extend` to `own` properties, so for your example you can just do

```js
_.extend({ 'a': 1 }, new Foo);
```

This can also be negotiated by just calling `_.omit(new Foo)`?

**Comment by jdalton** [comment]
> Underscore didn't scope extend to own properties, so for your example you can just do

I know, as my example showed an API which takes own properties of sources showing that it can be used to tackle similar issues that exist outside of Underscore's own methods as well as tackle those in Underscore.

> This can also be negotiated by just calling `_.omit(new Foo)`?

It doesn't feel as intuitive. With a method like `toPlainObject` it would allow refining what a plain object is. For example treating `arguments` objects as objects with length and index properties only.
