### ISSUE TITLE
Feature request: _.matches accepting an array as the argument, or multiple arguments

### ISSUE THREAD

**Issue by afanasy** [jashkenas/underscore#2008]
So it's possible to filter by multiple values of the same key:

```javascript
_.matches([{name: 'Bob'}, {name: 'Alice'}])
//matches both {name: 'Bob'} and {name: 'Alice'}

//and this syntax would be nice to have too :)
_.matches({name: 'Bob'}, {name: 'Alice'})
//matches both {name: 'Bob'} and {name: 'Alice'}
```

**Comment by megawac** [comment]
I would sooner have a `anyPass` and `allPass` which call each function in an array with provided arguments

Then we could do
```js
var isBobOrAlice = _.partial(_.anyPass, _.map([{name: 'Bob'}, {name: 'Alice'}], _.matches));

isBobOrAlice({name: 'Bob'})
```

**Comment by afanasy** [comment]
This looks good too, but I wanted to use _.where in the same manner:
```javascript
_.where(person, [{name: 'Bob'}, {name: 'Alice'}])
```
returns array with Bob and Alice
and the new syntax is backward compatible as far as I can see, it just adds the special handling case if argument is an array

**Comment by jashkenas** [comment]
Yeah, `anyPass` and `allPass` would be better than this. If you want boolean logic, just use it!

    _.matches(a) or _.matches(b)

    _.matches(a) and _.matches(b) and not _.matches(c)
