### ISSUE TITLE
chain breaking

### ISSUE THREAD

**Issue by ppalladino** [jashkenas/underscore#2009]
Is it possible to break a chain? For example I have created a breakIfNull mixin, and I would like to stop executing the chain if some condition is met.

**Comment by megawac** [comment]
Nope - at least I cant think of a way to do it - that may be a cool and useful enhancement!

**Comment by ppalladino** [comment]
Ha! Yeah, I could not see one myself. Thanks for the direction. I'll chew on it for a bit.

**Comment by jashkenas** [comment]
-> #2017
