### ISSUE TITLE
Don't hard code amd module name

### ISSUE THREAD

**Issue by togakangaroo** [jashkenas/underscore#2018]
I'd like to discuss the wisdom of the following bit of code

      // AMD registration happens at the end for compatibility with AMD loaders
      // that may not enforce next-turn semantics on modules. Even though general
      // practice for AMD registration is to be anonymous, underscore registers
      // as a named module because, like jQuery, it is a base library that is
      // popular enough to be bundled in a third party lib, but not be part of
      // an AMD load request. Those cases could generate an error when an
      // anonymous define() is called outside of a loader request.
      if (typeof define === 'function' && define.amd) {
        define('underscore', [], function() {
          return _;
        });
      }

For my application this is a breaking change. In my case I do not use the base underscore. Instead I use an extended version which has a proxy that unwraps knockout observables and has a half dozen utility methods attached (things for dealing with hierarchies, `mapObject: _.compose(_.map, _.object)`, that sort of thing).

The way this works is that I have an extendedUnderscore.js file that initializes extensions, this depends on `_underscore`.

I have a requirejs paths configuration that redirects requests for `_underscore` to *actual* underscore, and requests to `underscore` to `extendedUnderscore`

Starting version 1.7.0, this works in development but when I use r.js to bundle everything together this breaks. I believe this is because the module is already defined by the time the paths configuration is run.

removing the hard coded amd module name

        define([], function() { ....

allows everything continue to work.

**Comment by jdalton** [comment]
\cc @jrburke.

**Comment by togakangaroo** [comment]
I...guess this could be a requirejs issue, sure. It is certainly bad for require to behave differently bundled versus not, but I'm still thinking that naming modules is a mistake here.

Can someone elaborate on the conditions under which it causes an error?

**Comment by jrburke** [comment]
Background here:
https://github.com/jrburke/requirejs/wiki/Updating-existing-libraries#anon

You can use map config if you need to do tricks with the module ID to get set up an "extendedUnderscore". This is an example that is for jquery but same applies here, where "jquery-adapter" is your "extendedUnderscore". Scroll the example down to see how the adapter is defined.

On the plus side, if an ES6 module loader ever ships, it should not have this issue (or if all browsers in use supported something like [document.currentScript](https://developer.mozilla.org/en-US/docs/Web/API/document.currentScript)).

**Comment by togakangaroo** [comment]
@jrburke sorry to re-open this can of worms but I'm only now getting back to this. I think you meant to post a link above where you say "This is an example" but you forgot to?

**Comment by jrburke** [comment]
@togakangaroo sorry about that, meant to link to here, be sure to scroll the example to see it all:

http://jrburke.com/talks/moduleids/#/13
