### ISSUE TITLE
Documentation: link entries to the source

### ISSUE THREAD

**Issue by redolent** [jashkenas/underscore#2019]
Link the entries in the documentation to the source (http://underscorejs.org/docs/underscore.html) so that we can read the source of each method on the fly.

Also, if possible, link things from within the source display.

**Comment by amZotti** [comment]
I'm on it

**Comment by akre54** [comment]
Unfortunately those section ids are labeled numerically (e.g. "section-12"), rather than by method name, meaning we couldn't make sure they were properly linked (and kept up to date) without a whole lot of work. To fix this would require changes to docco, the software that generates the annotated source code.

**Comment by thejameskyle** [comment]
If only there was a way to reach out to the maintainer of docco.

**Comment by akre54** [comment]
;)

Unfortunately this is definitely out of scope for docco. It would require parsing the AST for all the languages docco supports (too many to count) instead of just looking for the comment tokens.

**Comment by knowtheory** [comment]
At risk of turning this into a thread about docco: seems like the easier way forward would be providing anchors based on markdown header hierarchy rather than source parsing.  Although in this case, it'd require adding `### [method name]` ahead of each method, which would look a little redundant if reading through the bare source (although some of the comments already do this).

**Comment by akre54** [comment]
What's wrong with simply linking to the actual source?

**Comment by amZotti** [comment]
@akre54  :+1:

**Comment by redolent** [comment]
After reading this thread, I looked at the source. I could see two ways of doing this:

* Linking to the section, since they already have id's. This would be tacky, but it would be helpful nonetheless (e.g., http://underscorejs.org/docs/underscore.html#object-functions)
* Using a script to add id's after docco runs. This could be done by looking at all the <pre> tags and adding the text of the first line into an id.

**Comment by greenify** [comment]
> Linking to the section, since they already have id's

But then adding a new function would break all your subsequent ids.

> Using a script to add id's after docco runs

I think that would be the easiest option.

> It would require parsing the AST

Yes, but at least for the underscore specific style there is a quick & dirty regex way to search for functions and their aliases.
This code adds the "function name" (and its aliases) as a `a` tag to the matching section and thus allows urls like http://underscorejs.org/docs/underscore.html#sortBy.
Warning: I just quickly hacked this together, there might be a more elegant way...

```
var rootEl = document.getElementsByClassName("sections")[0];
var childs = rootEl.children;
Array.prototype.forEach.call(childs, function(el) {
    var ps = el.getElementsByTagName("pre");
    if (ps.length === 1) {
        // at least for docco we always want to add it to the "pilcrow" div
        var elToAdd = el.children[0].children[0]; 
        var code = ps[0].innerHTML;
        // a very ugly way to remove all highlighting spans
        code = removeSpan(removeSpan(code));
        // pick only matching function aliases (either 1 or 2)    
        var matches = /_\.(\w+).*?(?:_\.(\w+))?\s*=\s*function/g.exec(code);
        if (matches && matches.length > 1) {
            var aliases = matches.slice(1).filter(function(e) {
                return e;
            });
            aliases.forEach(function(al) {
                var aLink = document.createElement("a");
                aLink.name = al;
                elToAdd.appendChild(aLink);
            });
        }
    }
});

function removeSpan(code) {
    return code.replace(/<span[^>]*>(.*?)<\/span>/g, "$1");
}
```

**Comment by akre54** [comment]
Sure, but again what's the usefulness of this? It's easy enough to look within the source for someone who is curious, or link to a git tagged version for posting somewhere else. The annotated source doesn't really need to be linkable.

**Comment by redolent** [comment]
How is it easy? At the moment I have to find the method in the doc, then open up the source in another window and Cmd+F through it. I have to do this for every method I'm reading on.

**Comment by jashkenas** [comment]
The source is a single document that's meant to be read ... the docs are a single document that's meant to be read. You're not really intended to bounce back and forth between the two — if you're actually doing that, just go read the source ;)

And in any case, a little Cmd+F action isn't such an onerous thing. God forbid the bad old days. Indexes! Folded corners! Concordances! Bibliographies! Annotated companions!

**Comment by thejameskyle** [comment]
> God forbid the bad old days. Indexes! Folded corners! Concordances! Bibliographies! Annotated companions!

"Back in my bad we had folded corners, now get off my property ye' hooligans" – Old man @jashkenas

Would a reasonable compromise be to link to line numbers in the annotated source?
