### ISSUE TITLE
_.extend converts destination object's prototype properties to "own" properties

### ISSUE THREAD

**Issue by jmrog** [jashkenas/underscore#2023]
I'm trying to figure out (or at least get opinions on) whether this behavior is an undocumented "feature" of `_.extend` or a bug:

```javascript
function Foo(){}

var foo = new Foo();
Foo.prototype.bar = "On the prototype!";
foo.hasOwnProperty('bar');
// => false

_.extend(foo, {});
foo.hasOwnProperty('bar');
// => true
```

Basically, the current version of `_.extend` not only iterates through the properties of passed in "source" objects, but also through the properties of the "destination" object itself, including properties on the prototypes. `_.extend` is intended to include properties from prototypes, AFAIK (if you want only the "own" properties, there's now `_.assign` for that), so that isn't the issue. The issue is whether `_.extend` should be including the properties on the prototype chain for *the original destination object itself*, so that the destination object gets new "own" properties and ends up extended even when the "source" is an empty object.

I'm inclined to think this shouldn't be the case. When the "source" is empty (an empty object), the "destination" shouldn't be changed. You can just supply the prototypes as additional arguments to `_.extend` if you want the prototype properties on the destination object iself.

Thoughts?

Original notice of this issue and some related discussion is here: https://github.com/jashkenas/underscore/pull/2022

**Comment by jridgewell** [comment]
This is actually a **huge** breaking change. Consider Backbone's `.extend`:

```javascript
function extend(protoProps, staticProps) {
    //...

    // Add prototype properties (instance properties) to the subclass,
    // if supplied.
    if (protoProps) _.extend(child.prototype, protoProps);

    //...
};
```

With this change, all of the parent's instance methods will be copied onto the new subclass. This'll break things like generic base method wrapping (if it was loaded afterwards).

```javascript
var View = Backbone.View.extend({});
Backbone.Model.prototype.set = wrappedSet;

View.prototype.set === wrappedSet; // => false
```

Great catch, @jmrog. :clap:

**Comment by jmrog** [comment]
Good to know, @jridgewell. Thanks! I'll try to put together a pr (fix should be easy, at least at first glance) and a couple of tests shortly.

**Comment by jmrog** [comment]
Actually, @jridgewell, can you say more (if you get a chance) about what's going on and/or supposed to be going on in that second bit of code (with `wrappedSet`)? I'm not immediately seeing it.

**Comment by jridgewell** [comment]
In general, you can change a parent classes prototype and have that immediately reflected in any subclasses.

```javascript
var Parent = function() {};
Parent.prototype.method = function() {
    // does something...
};

var Child = function() {
    Parent.call(this);
};
Child.prototype = Object.create(Parent.prototype);

// Later on, we decide #method should throw for Parent and all its subclasses
Parent.prototype.method = function() {
    throw new Error("don't call this");
};
```

Under normal JS inheritance, calling `Child#method` will throw an error after the change. Since `method` won't be found on `Child.prototype`, it will traverse up the prototype chain until it finds it on `Parent.prototype`.

Since `_.extend` is now setting any enumerable-properties as own-properties, this means `Child#method` won't throw. That's because `Child.prototype` has an own `method`, and won't traverse up the prototype chain any further.

**Comment by jmrog** [comment]
Ah, gotcha. Thanks. :+1:
