### ISSUE TITLE
Issue with r.js optimizer and Underscore _.template() function

### ISSUE THREAD

**Issue by LordotU** [jashkenas/underscore#2026]
I have an issue with Underscore (I use an old version [1.3.3] and can't use others for this project) `_.template()` function after creating optimized build. 

After optimizing I have a file with all my initial modules. Underscore (like jQuery) also placed there via shim. Templates files are excluded via `onBuildWrite()` function and loaded dynamically.

But there is a big problem: after optimization `_.template()` doesn't work properly. It can't evaluate multiline (but singleline code evaluates fine in some cases [I can't check all of it]) JS in template files. So, for example it can't parse this template file:

    <%
    	var subsIconsNames = {
    		promosite: 'programs',
    		photomodel: 'models',
    		photographer: 'photo',
    		stylist: 'stylist',
    		nailmaster: 'nailmaster',
    		expo: 'exhibition',
    		tourism: 'turism'
    	};
    %>
    
    <div><%= subsIconsNames [type] %></div>

> "Uncaught ReferenceError: subsIconsNames is not defined"

But without optimization it works fine.

Thanks for your attention.

https://github.com/jrburke/r.js/issues/773

**Comment by megawac** [comment]
Can you precompile your templates?

https://github.com/dciccale/requirejs-underscore-tpl

**Comment by LordotU** [comment]
I don't need to include templates into build file. It should load dynamically.

Or you just wanna look to precompiled code?

**Comment by megawac** [comment]
AFAIK `r.js` will include the templates in the built file, so precompiling would do that plus optimize the setup step

**Comment by LordotU** [comment]
No, r.js doesn't include template files to build, because I override it via `onBuildWrite()` - for template files it returns `false`:

```
var noopModules = ['text!', 'json!'];
// Build config starts here
onBuildWrite: function(moduleName, modulePath , contents) {
  return noopModules.filter(function(module) { return !!moduleName.indexOf(module) !== -1}).length ? false : contents;
}
// Build config ends here

**Comment by jashkenas** [comment]
Presumably because the optimizer is renaming the local variable? Or something like that?

Not an Underscore issue — that's between you and your optimizer.

**Comment by jdalton** [comment]
\cc @jrburke
