### ISSUE TITLE
Make partial placeholder customizable

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2027]
Currently the `_.partial` placeholder is fixed as `_` but it would rock if it was customizable.
```js
_.partial.placeholder = '_';

var fn = function(a, b) { return [a, b]; };
var par = _.partial(fn, '_', 'b');
par('a') // => ['a', 'b']
```

**Comment by megawac** [comment]
Duplicate of #1688

**Comment by jdalton** [comment]
Ah I did a search for placeholders before opening the issue :P
It's covered by PR #1689.

**Comment by jdalton** [comment]
Then this issue serves as a * ping * on that.
