### ISSUE TITLE
not to be bounded to window by default

### ISSUE THREAD

**Issue by pasupulaphani** [jashkenas/underscore#2040]
Hi all,

In my scenario where one of my client has different version of Underscore and my library is using different version of underscore.

We ended up overriding our window._

Is there a way to source underscore and not to be bounded to window. Instead bind to the reference provided.

Kind regards,
Phani.

**Comment by megawac** [comment]
There are several ways you can address this:

1. You can build your application using a build tool such as browserify or esperanto, which will respect the version ranges you set
2. you can load the multiple versions of underscore via a script tag and call `_.noConflict()`


Assuming you load 3 underscore versions
```js
// The last loaded underscore version
var _3 = _.noConflict();
// The second loaded version
var _2 = _.noConflict();
// The first one
var _1 = _;
```

**Comment by pasupulaphani** [comment]
Thank you.
