### ISSUE TITLE
_.property accept a value argument.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2045]
It seems that a common case is `{prop:value}` but that's pretty clunky since the object has to be crawled, cloned, and compared. It seems that a more straight forward approach would be to allow `_.property` to accept a `value` param creating a simple `return object[prop] === value` callback.

This could be seen in callback sugar as `_.filter(objects, prop, value)`.

This would also handle the transition of #2044 is done since "property" matches would have no own-prop checks.

 Thoughts?

**Comment by jdalton** [comment]
This would also handle the transition if #2044 is done as "property" matches would have no own-prop checks.

**Comment by megawac** [comment]
Yeah, sounds like a good enhancement - should probably be implemented with a guard

**Comment by jdalton** [comment]
Closing as stale.
