### ISSUE TITLE
Expand guards.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2046]
Currently the iteratee guards for `_.first`, `_.initial`, `_.last`, `_.rest`, & `_.sample` are [documented](https://github.com/jashkenas/underscore/commit/3bb940580e6145173f470e1b8ac00b61939ba4cc). You can expand this to all other methods that fit. I've seen this done for methods like:
`clone`, `flatten`, `invert`, `max`, `min`, `sortBy`, `template`, `random`, `range`, & `uniq`

This can also apply for `_.reduce` & friends for methods like:
`extend`, `assign`, &  `defaults`

![image](https://cloud.githubusercontent.com/assets/4303/6131961/678c6ee8-b104-11e4-943b-1b5fe83babdf.png)

**Comment by amZotti** [comment]
:+1:  I'll handle this. Any recommendations for implementation?

**Comment by jdalton** [comment]
How they're documented shouldn't effect the expanding of them. It's to different concerns.

**Comment by jridgewell** [comment]
> How they're documented shouldn't effect the expanding of them. It's to different concerns.

:+1:
