### ISSUE TITLE
Lack of custom `_.isEqual` causing issues with objects with private properties.

### ISSUE THREAD

**Issue by jiaweihli** [jashkenas/underscore#2047]
Hi!  I've forked a library called [monapt](https://github.com/jiaweihli/monapt), which attempts to bring the [Option type](https://en.wikipedia.org/wiki/Option_type) to javascript.  I'm very explicitly hiding the wrapped value behind an method.  There's only 1 attribute - a marker indicating whether or not the object contains a value or not.

This is causing problems in the default implementation of `_.isEqual`, which only iterates over properties (as it should).  Backbone is calling `_.isEqual` when I issue a `set`.  It doesn't realize there's been a change when I replace one wrapped value with another.  

This is a concrete use case for #748, which would solve this problem by allowing me to define a custom `isEqual` function to ensure interoperability with `_.isEqual`.

**Comment by jiaweihli** [comment]
Alternatively, implementing this would work as well: https://github.com/jashkenas/backbone/issues/944
That way, I could force-set any attribute that's an `Option`.

**Comment by jiaweihli** [comment]
For a concrete comparison of the benefits, selecting either solution would cut down this code:

```typescript
set paginatedQuery(paginatedQuery: Monapt.Option<PaginatedQuery>) {
  // :KLUDGE: Options don't trigger correctly - https://github.com/jashkenas/underscore/issues/2047
  var needsManualTrigger: Boolean = !paginatedQuery.isEmpty && !this.paginatedQuery.isEmpty &&
    !_.isEqual(paginatedQuery.get(), this.paginatedQuery.get());

  this.set('paginatedQuery', paginatedQuery);

  if (needsManualTrigger) {
    this.trigger('change:paginatedQuery');
    this.trigger('change');
  }
}
```

to this:

```typescript
set paginatedQuery(paginatedQuery: Monapt.Option<PaginatedQuery>) {
  this.set('paginatedQuery', paginatedQuery);
}
```

for each attribute that's an `Option`.

**Comment by megawac** [comment]
@jiaweihli one way you can get around this is to wrap `isEqual` so that your type is supported. An easy way to do this would be to do

```js
_.isEqual = _.wrap(_.isEqual, function(defaultIsEqual, a, b) {
    // or whatever
    if (a instanceof Monapt.Option) return a.equals(b);
    else return defaultIsEqual(a, b);
});
```

Though I gotcha here, but in this case theres not many other ways about changing it for BB's set method

**Comment by jiaweihli** [comment]
@megawac I see, that would work!

Though upon closer inspection, my code will work as-is, since the typescript compiler doesn't truly hide private members inside a closure, but rather declares them as private in the definition.
