### ISSUE TITLE
Alias isUndefined to something, maybe with negation

### ISSUE THREAD

**Issue by djvs** [jashkenas/underscore#2051]
Possiblities...

_.undefined
_.undef
_.def 
_.defined

How nice would the middle two be?

**Comment by jashkenas** [comment]
Not nice enough ;)

**Comment by djvs** [comment]
Well, if your goal is to prevent people having to type:

  if typeof param == "undefined"

...

**Comment by jridgewell** [comment]
> Well, if your goal is to prevent people having to type:

It's not possible to do that with a method. https://github.com/jashkenas/underscore/issues/2015

**Comment by djvs** [comment]
Oh, geez.  Didn't even think about that.
