### ISSUE TITLE
1.8.0 tests have 102 failures in IE8

### ISSUE THREAD

**Issue by paulfalgout** [jashkenas/underscore#2062]
Not the best release.. not the worst

**Comment by akenn** [comment]
:+1: :shipit:

**Comment by jashkenas** [comment]
Probably the worst.

**Comment by medcat** [comment]
:shipit:

**Comment by jashkenas** [comment]
Simply removing the `hasEnumBug` and `collectNonEnumProps` workarounds has the result of fixing the vast majority of these errors. Any bright ideas?

**Comment by paulfalgout** [comment]
I haven't tried the test directly, but my app works if I remove `toString` from `nonEnumerableProps`

Just a start.

```js
  var hasEnumBug = !{toString: null}.propertyIsEnumerable('toString');
  var nonEnumerableProps = ['constructor', 'valueOf', 'isPrototypeOf',
                      'propertyIsEnumerable', 'hasOwnProperty', 'toLocaleString'];
```

**Comment by jashkenas** [comment]
@paulfalgout — Please give the current **master** a try and let me know if it works for you in your app.

**Comment by thejameskyle** [comment]
It might be good to fix some of these tests instead of deleting them.

**Comment by jashkenas** [comment]
@paulfalgout When you get a chance — I've pushed out 1.8.1, with changes that allow the important tests to pass in IE. Let us know how its working for you...

**Comment by paulfalgout** [comment]
Well `1.8.1` doesn't totally bomb, but I'm seeing a very strange bug now.  Switching back to `1.6.0` it works fine, so I'm attempting to see if something around this changed in underscore or if there's a new issue.

**Comment by jashkenas** [comment]
Well, if you can only change Underscore, and see issues with 1.8.1, then it's probably our fault. Let us know when you have a failing test case — and we can push out a revised 1.8.2 ... or however many it takes to get it right.

**Comment by paulfalgout** [comment]
Actually as far as my app is concerned I think I'm in the clear.  The bug I was seeing was an older use of `_.template` passing data as the 2nd attribute.  Didn't catch it earlier because we initially didn't upgrade to `1.7.0` because I have some legacy code that depends on `1.6.0` `_.extend` and it is unfortunately difficult to refactor.  (though it will be refactored soon)  Difficult bug to track down, because our current tests fail a bit after the template renders as "function(){ return render.call ..." in a nearly unrelated place.  IE8 + contenteditable = :crying_cat_face:

Anyhow.. a bit nervous about everything that was pulled out at the last moment.  I'm sure that'll be addressed in the near term.  In the future I'm more than willing to run a preview branch through the ringer..as I'm sure others are as well.  I've been watching this release fairly closely, but it seemed like it was a ways off.. and then it wasn't.  But we could work on catching these things prior to a release.

I do appreciate the work and the library for sure, and there are many brilliant contributors, but I don't have a ton of confidence in many last minute changes.  There's just no way I could sell using `1.8.1` at work without waiting a long time for possible issues to rise to the surface.  We're pretty willing to live on the edge, but this just isn't safe enough.

**Comment by jashkenas** [comment]
Thanks for checking it out and reporting back. Living on the edge is never a good idea — you could always take the time to try out new versions of things.

For what it's worth, `1.6.0 _.extend` is back in 1.8+ ... so you should be all set on that front.
