### ISSUE TITLE
Add "New in version x.y" annotation to Underscore's API docs.

### ISSUE THREAD

**Issue by coredumperror** [jashkenas/underscore#2080]
The Python docs make it very clear when a new API was added to the standard library. This makes it easy, at a glance, to determine if you have access to this shiny new API despite being stuck on a certain version of the language due to various reasons.

I just ran into a problem recently where Chrome was throwing "undefined is not a function" in the code I was debugging. It turns out that `_.pairs()` was added in a later version of Underscore than the version installed on my site. But since there was no hint in the docs about `_.pairs()` being added after the initial released of the library, I was quite flummoxed because *I didn't know I had such an old version*.

I'm requesting this feature on behalf of other users like me, who develop for a site that installed Underscore years ago.

**Comment by jashkenas** [comment]
All of this information is in the Changelog, at the bottom of the page.

You're suggesting putting it inline with the documentation of each individual function instead?

**Comment by megawac** [comment]
You can also just look at the documentation for the version you are using. For example

[**1.3.1 docs**](https://cdn.rawgit.com/jashkenas/underscore/1.3.1/index.html)

**Comment by coredumperror** [comment]
@jashkenas Sorry, I should have been more specific. Yes, I'm asking for the "New in version x.y" info to be inline with the individual functions. Much like how the Python docs work, e.g. [all()](https://docs.python.org/2/library/functions.html#all)

@megawac As I mentioned at the end of the second paragraph, I didn't even know what version I actually had installed. So going after the 1.3.1 docs would be something I'd never even imagine was needed. The "New in version x.y" tag essentially acts as an indicator that one need to install at least version x.y, which then prompts one to think "What version do I have installed?" I was never prompted to wonder this, which was why I was so confused by the error I was getting.

**Comment by jashkenas** [comment]
Interesting idea, but I think that the docs are better without "new in version X" tags on every function.

Debugging the call of a function that doesn't exist is a critical JS skill in any context — not just Underscore. Docs would have been beside the point to solving your particular problem.

**Comment by coredumperror** [comment]
> Docs would have been beside the point to solving your particular problem.

Not true. If I'd seen some sort of evidence that `_.pairs()` had been added in a version before the first release, looking at the docs would have immediately prompted to me check which version of Underscore I had. 

jQuery does this, Python does this, every major library I've ever used does *something* inline to tell its users when a certain API was added.
