### ISSUE TITLE
 Wrong number of iterations for objects that contain numeric keys

### ISSUE THREAD

**Issue by francois2metz** [jashkenas/underscore#2081]
This is an ios only bug that also happened on lodash. 

https://github.com/lodash/lodash/issues/799

Here is the original testcase updated for underscore: http://jsfiddle.net/rcsz27v1/2/

The result should be 3, but on ios it's 51.

It happens on underscore 1.8.2 as well as 1.7.0.

**Comment by megawac** [comment]
@francois2metz IOS8? Want to make a PR with a failing test case (otherwise I can do it later)?

**Comment by francois2metz** [comment]
@megawac Yep, IOS8. I'll create the pull request.

**Comment by jridgewell** [comment]
It's coming because `isArrayLike()` is being improperly JIT'd.

```javascript
// Using a non-closure underscore to expose isArrayLike

// Setup. At least one property must not be a number
var obj = {1: 'foo', 2: 2, 3: 3};
var logger = function(val, key) { console.log(val, key); }

// JIT isArrayLike with only arrays
_.times(1000, function() { _.each([], logger); });

isArrayLike(obj); // => true
```

**Comment by osolo** [comment]
There is further discussion of this topic at http://stackoverflow.com/questions/28155841/misterious-failure-of-jquery-each-and-underscore-each-on-ios.

The problem is that the iOS bug causes a `length` property to incorrectly appear for these objects, which causes `each` to try to iterate the object as an array.

The solution is to check for `obj.hasOwnProperty('length')`, which I can confirm is immune to this bug.

Also see this summary in the related bug I filed against jQuery: https://github.com/jquery/jquery/issues/2145

**Comment by firstdoit** [comment]
Got bitten by this bug today. One entire afternoon debugging an iPhone 6... It seems @osolo solution works. Do you guys need a PR?

**Comment by jridgewell** [comment]
@firstdoit: https://github.com/jashkenas/underscore/pull/2094

**Comment by firstdoit** [comment]
@jridgewell nice! sorry I missed that.

**Comment by hansifer** [comment]
Can someone shed light on exactly how the current implementation (v1.8.3) of isArrayLike() circumvents this bug. 

    var property = function(key) {
        return function(obj) {
            return obj == null ? void 0 : obj[key];
        };
    };

    var getLength = property('length');

    var isArrayLike = function(collection) {
        var length = getLength(collection);  // essentially calls collection['length']
        return typeof length == 'number' && length >= 0 && length <= MAX_ARRAY_INDEX;
    };

How does getLength() not return a bad length vs. `collection.length`?

**Comment by jridgewell** [comment]
I'm not familiar with iOS' implementations, but it JITs `collection.length` and `collection['length']` differently.
