### ISSUE TITLE
Proposal: fill an array with _num_ entries of the _value_

### ISSUE THREAD

**Issue by zuber** [jashkenas/underscore#2082]
If there is a range() already in Underscore.JS, it would be useful to have a function like PHP array_fill(), omitting its _start_index_ parameter:
http://php.net/manual/en/function.array-fill.php

It should have a different name, not _fill_, to avoid confusion with https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

**Comment by Florian-R** [comment]
No need, you can already fix the start parameter with `_.partial`
```js
_.partial(_.range, 0)(10, 2)
//Array [ 0, 2, 4, 6, 8 ]
```

**Comment by zuber** [comment]
There is another task:
_.fill(1, 5)
// Array [1, 1, 1, 1, 1]

_.fill('bar', 3)
// Array ['bar', 'bar', 'bar']

**Comment by Florian-R** [comment]
Yap, sorry, i misread your use case. You can use `_.times`

```js
_.times(3, function() { return 'foo'; });
//Array [ "foo", "foo", "foo" ]
```

**Comment by zuber** [comment]
Ok, Florian-R, may you close this issue?

**Comment by Florian-R** [comment]
Nope, i'm not a collaborator of this repo. But you can totally do it.

**Comment by jridgewell** [comment]
Yup, `_.times` is going to be your best bet:

```javascript
_.times(3, _.constant('foo')); // => ['foo', 'foo', 'foo']
```
