### ISSUE TITLE
issue with unicode variable names

### ISSUE THREAD

**Issue by yinwang0** [jashkenas/underscore#2083]
Hi,

I'm making a javascript renamer. When testing it on underscore's code, I found that whenever I rename variables into unicode, the test suite would fail.

For example, if you put this line anywhere in underscore.js, the test suite will fail with messages like "... is not defined".

  var ☺ = 0;

The variable is never used, so ideally the test suite should pass as usual. I wonder if the test framework is not handling unicode properly. I appreciate any ideas regarding this. Thanks.

**Comment by jridgewell** [comment]
A unicode smiley face is [not](https://mothereff.in/js-variables#%E2%98%BA) a valid variable name.

**Comment by yinwang0** [comment]
Oh I made a bad example. Indeed smily is not valid, but try another one which is valid and the same problem will happen:

var ꎂ=1;

Other libraries like backbone's test suite will pass, and it's using the same version of qunit. So I wonder what's special in underscore.

**Comment by jridgewell** [comment]
It's due to the linter:

```javascript
var ꎂ= 1;

(function() {

  var ꎂ= 1;


  // Baseline setup
  // --------------

  // Establish the root object, `window` in the browser, or `exports` on the server.
  var root = this;

///...
```

```
$ npm test
// snip...
> underscore@1.8.2 lint /Users/jridgewell/src/underscore
> eslint underscore.js test/*.js


underscore.js
     6:4   error    Infix operators must be spaced                                   space-infix-ops
    10:6   error    Infix operators must be spaced                                   space-infix-ops
// snip...
    10:6   error    ꎂ is defined but never used                                      no-unused-vars
```

**Comment by yinwang0** [comment]
But if you change the variable name to some unused ascii name, the tests will pass...

**Comment by jridgewell** [comment]
Even an ASCII name will fail:

```
> underscore@1.8.2 lint /Users/jridgewell/src/underscore
> eslint underscore.js test/*.js


underscore.js
//snip...
    10:6   error    unused is defined but never used                                 no-unused-vars
```

**Comment by megawac** [comment]
On another note, Backbone should probably be linted - the `jsl` script isn't being run by travis

**Comment by jridgewell** [comment]
@michaelficarra: mind closing this time?

**Comment by yinwang0** [comment]
Yes can be closed. 

I ran the test suite in an incorrect way (I just loaded test/index.html into browser). If I run it using

  npm run test-browser

the tests will pass even with unicode names. Thanks.
