### ISSUE TITLE
_.findWhere Works differently on same browser but different OS

### ISSUE THREAD

**Issue by safeer-in** [jashkenas/underscore#2090]
_.findWhere([ {id:"1"} , {id:"2"} , {id:"3"} ], {id:2} ) is return object on windows with Chrome; while return 'undefined' on Chrome with ubuntu. when needle set to {id:'2'} it return object in ubuntu while return 'undefined' in windows.

**Comment by megawac** [comment]
Are you using the same version of underscore in both environments

What version of chrome and windows?
What version of chromium and ubuntu?

**Comment by megawac** [comment]
Closing due to lack of information

**Comment by safeer-in** [comment]
Ok. Its becuse of different JSON parsing behaviour in browsers. In Chrome 40 in windows json parsed data return 'data with integer keys' , in chrome 39 on ubuntu , data parse as 'data with string keys'.
