### ISSUE TITLE
_.contains(list, value) not works with objects

### ISSUE THREAD

**Issue by kiranps** [jashkenas/underscore#2092]
var list = [{name: "kiran"},{name: "smith"}];
    _.contains(list, {name: "kiran"});

returns false

    _.where(list, {name: "kiran"});

works perfectly

**Comment by jridgewell** [comment]
`_.contains` uses strict equality. `_.contains(list, list[0])` works perfectly.

Use `_.find` / `_.any` for predicate finding.
