### ISSUE TITLE
template function safety

### ISSUE THREAD

**Issue by oshanz** [jashkenas/underscore#2095]
[Mithril framework](http://lhorie.github.io/mithril/) say that there is a [security hole](http://lhorie.github.io/mithril/comparisons/backbone.safety.html) in underscore template function. Test results are at there home page. What you gays think?

**Comment by megawac** [comment]
This could be avoided by using `<%- val ->` instead of `<%= val %>`

http://jsbin.com/nicivikife

**Comment by jridgewell** [comment]
Saying underscore templates are unsafe by default is ingenuous. Use `<%- %>` instead of `<%= %>`.

**Comment by jridgewell** [comment]
Apologies, I didn't mean to imply it's you, @oshanz. It's Mithril, and it's contributors should know better.

**Comment by jashkenas** [comment]
You can ping @lhorie about it.

**Comment by lhorie** [comment]
Uh, no, I'm not claiming there's a security hole in Underscore templates. What that demo aims to demonstrate is that it's easy for a developer to unintentionally do the wrong thing.
