### ISSUE TITLE
extendOwn - description and maybe even naming...

### ISSUE THREAD

**Issue by infolock** [jashkenas/underscore#2101]
Granted, I am late to the game to the whole story about how this method came to be (and the war it almost caused lol..), but some small issues still exists.

Primarily, its in the description of what this method does and how it should be used.  The current documentation for this method is so ...vague, that it made it damn near impossible to understand exactly what it does and (more importantly) how it differs from just the regular extend.

Imo, even looking at the source code itself doesn't even really do it any justice.

The request would be to either have someone explain it better, reference (somehow) ES6's Object.assign, or something similar.

*\* removed the question about the naming... https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty  helped explain this (via a source from "mu is too short" on stackoverflow **

**Comment by jridgewell** [comment]
See the comments in https://github.com/jashkenas/underscore/pull/2089. PRs are welcome.

**Comment by infolock** [comment]
Cool beans thanks!

**Comment by jgonggrijp** [comment]
Appears to have been adressed.
