### ISSUE TITLE
_.where doesn't work for inner object

### ISSUE THREAD

**Issue by portus84** [jashkenas/underscore#2104]
Hi, for inner json object `_.where` doesn't work:
example code:
`_.where([{"id": 1, "in": {"id": "a"}}], {"in": {"id": "a"}});`

return empty array.

Thanks

**Comment by akre54** [comment]
That's correct. `_.where` isn't deep. Use a `filter` for this, or mixin your own `_.deepWhere.

**Comment by jridgewell** [comment]
This is another case that a [customizable `_.iteratee`](https://github.com/jashkenas/underscore/pull/1965) would help.

**Comment by akre54** [comment]
But that would affect every method that uses `_.iteratee` right? Much better to specifically indicate if you want deep or shallow, right?

**Comment by jridgewell** [comment]
Not necessarily. It'd be convenient to drop in deep support across the board:

```javascript
_.where(..., {"in": {"id": "a"}});
_.any(..., {"in": {"id": "a"}});
_.every(..., {"in": {"id": "a"}});
_.reject(..., {"in": {"id": "a"}});
// And way too many more

// How about deeply.nested.plucking.cause.its.always.requested
_.pluck(..., 'in.id');
```

**Comment by akre54** [comment]
Yuck. Too much internal mucking. Just create a separate method (or set of `__Deep` methods). You slow everything down for the one or two times in your code you actually need deep methods (and that could be better handled with a regular filter, map, whatever).
