### ISSUE TITLE
Version 1.8.3

### ISSUE THREAD

**Issue by jridgewell** [jashkenas/underscore#2110]
Needs:
======

Possibly:
=======

- [ ] Gaurd `_.min` / `_.max` - #2039
- [ ] Flatten `_.bindAll` - #2005
- [ ] Changeable `_.partial` placeholder - #1689
- [ ] Reset `_.debounce` - #1542

Changes:
========

- `_.create` added - #2074
- Fix for `isArrayLike(0)` - #2079
- Fix `_.findIndex([0, NaN], NaN, 1)` - #2102
- Guard `_.contains` - #2109
- iOS JIT bug - #2094

**Comment by jridgewell** [comment]
Ping @jashkenas: Two important bugfixes now (#2094 and #2079). Mind cutting [that](https://github.com/jashkenas/underscore/pull/2079#issuecomment-75568898) release?

**Comment by jridgewell** [comment]
Actually, hold off for 10 minutes.

**Comment by megawac** [comment]
@jashkenas can we get a release out ASAP

**Comment by jashkenas** [comment]
Sure thing. Will do it now.

**Comment by jashkenas** [comment]
Done.

**Comment by jashkenas** [comment]
By the way, if you guys want to ping me — just shoot me an email directly. Github issues notifications go into the "Forums" tab, and are only intermittently looked at.
