### ISSUE TITLE
question about _.template rendering context

### ISSUE THREAD

**Issue by thomhickey** [jashkenas/underscore#2111]
Hello and sorry if this is the wrong place to just ask a question about functionality. We use jQuery.tmpl() to do things like:

{{each getUniquePrograms(4)}}
    <li>
        ${$value.getDisplayName()}
    </li>
{{/each}}

where getUniquePrograms() is a method on the data object passed to .tmpl() and getDisplayName() is a method on a rich object of the iterated collection. I see that _.template allows for javascript eval via <% %> but in playing around I can't get the rendering context to execute methods on the passed-in data object. Is it possible to create an api-style rendering context like this so that we can expose methods that might return a collection of rich objects?

Thanks in advance,

-Thom

p.s. moving away from jQuery.tmpl() for obvious reasons, looking for the all-out speed demon of templating engines.

**Comment by jashkenas** [comment]
<%= value.getDisplayName() %>

Voilá.

**Comment by braddunbar** [comment]
Also, the context of the template is accessible as `this` because templates are just functions! :smiley_cat:

```js
var view = {
  foo: function() { return 'x'; },
  template: _.template('<%= this.foo() %>')
};
view.template() // 'x'
```

**Comment by thomhickey** [comment]
Awesome ... I guess the question then becomes how to code the iteration. And we nest loops:

{{each getSomeList()}}
  {{each $value.getAnotherList()}}
  {{/each}}
{{/each}}

Do I do something like this in underscore:?

<% _.each(this.getSomeList(), function(item) { %> <strong><%= name %></strong> <% }); %>

That would handle the outer loop, what about the inner? Just throw another _.each in there?

**Comment by megawac** [comment]
I think you want `<% _.each(this.getSomeList(), function(item) { %> <%= item.name %> <% }); %>`

**Comment by thomhickey** [comment]
getting: Object [object global] has no method 'getSomeList' doing:

renderedListing = _.template('<% _.each(this.getSomeList(), function(item) { %> <strong><%= item.name %></strong> <% }); %>',  this);

object 'this' definitely has a getSomeList() method when _.template is invoked

**Comment by d10** [comment]
Try `renderedListing = _.template('...').call(this);`.

**Comment by akre54** [comment]
Or `this.renderedListing = _.template('...'); this.renderedListing();`
