### ISSUE TITLE
#create link doesn't go anywhere on underscorejs.org

### ISSUE THREAD

**Issue by shamrin** [jashkenas/underscore#2112]
As [reported by][1] @alanhussey in PR #2074:

> `_.create` is being shown in the sidebar on [underscorejs.org](underscorejs.org), but there isn't any documentation available for it.

![broken create link](https://camo.githubusercontent.com/b1ae2cd33719266147042e25df9ee41c48249c1d/687474703a2f2f692e696d6775722e636f6d2f59524e6a6a75622e706e67)

Super confusing.

[1]: https://github.com/jashkenas/underscore/pull/2074#issuecomment-76852065

**Comment by akre54** [comment]
Thanks!
