### ISSUE TITLE
_.memoize accepts only unary functions, should accept any arity

### ISSUE THREAD

**Issue by rightfold** [jashkenas/underscore#2113]
To my surprise `_.memoize((a, b) => a + b)` broke horribly. Why does _.memoize work only with unary functions?

**Comment by spadgos** [comment]
`memoize` takes a second function so you can define your own hashing function. A naive one which would work in your situation would be:

```js
_.memoize((a, b) => a + b, (a, b) => a + '+' + b)
```

**Comment by jridgewell** [comment]
> memoize takes a second function so you can define your own hashing function

Exactly. `_.memoize`, by default, only memoizes by the first parameter's string value. If you're using objects or need memoization across multiple parameters, you need to provide the second parameter `hasher` to generate a unique string for each memo value.

**Comment by Morantron** [comment]
What's the motivation for only using the first argument? Found this PR but cannot figure out why exactly: https://github.com/jashkenas/underscore/pull/1679/files

**Comment by jridgewell** [comment]
@Morantron: That PR kept the same behavior since it used `_.identity` as the default hasher. It's because it's simple to implement on our end, and there's no way to cover everyone's needs.
