### ISSUE TITLE
stable sort with a comparator

### ISSUE THREAD

**Issue by pmcelhaney** [jashkenas/underscore#2114]
[Array.prototype.sort() isn't guaranteed to be stable](http://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers).

Why not implement a `_.sort(array, comparator)` method that's just like the native sort but stable? You could implement a [merge sort in JavaScript](http://stackoverflow.com/questions/1427608/fast-stable-sorting-algorithm-implementation-in-javascript) or use the surrogate array strategy employed in [sortBy](http://underscorejs.org/docs/underscore.html#section-41).

**Comment by megawac** [comment]
The implementation in underscore and lodash is guaranteed to be stable as the comparators we use take original order into account. It may be worthwhile to implement a different sorting algorithm internally, however, it would need to beat the performance hybrid native algorithms implemented by browsers. For now I don't think its worthwhile to pursue.

**Comment by pmcelhaney** [comment]
I don't think you understood. There is no implementation of `_.sort` in underscore that takes a comparator. If I'm missing something, please let me know. 

I understand that such an implementation would be slower than native. I don't see anything wrong with falling back to native if we know the browser's sorting algorithm is stable. For those browsers that don't use a stable algorithm, it would be nice to have an abstraction that makes sorting stable and consistent across browsers (at the cost of performance in some browsers).

**Comment by megawac** [comment]
We have the sortBy method which is stable and not in place (implemented via
array.sort()).

If you're suggesting that we add _.sort I dont think it'd be a worthwhile
addition, better left for a mixin.

**Comment by pmcelhaney** [comment]
The keyword is **comparator**. `_.sortBy` does not take a comparator function. 

The specific problem I had actually came out of an app that uses Backbone. Backbone collections are able to be sorted with a comparator and they use the native `Array.sort` rather than underscore. 

Comparator, stable, always-native performance. Pick two. :)
