### ISSUE TITLE
_.defaults() does not initialize for undefined/null

### ISSUE THREAD

**Issue by balnagy** [jashkenas/underscore#2115]
Hi,

I'm using _.defaults to initalize the config of my class.

```
var config = {
    port: 10000
};

function Server(options) {
    this.config = _.defaults(options, config);
}
```

I expected it to work even if I don't pass any options, but it doesn't. I need to do this:

```
this.config = _.defaults(options || {}, config);
```

For me it's unexpected. How do you think?

**Comment by lukeasrodgers** [comment]
`_.defaults` could be rewritten to handle this scenario, but I would say that, in general, calling it on `null` or `undefined` probably means you have a bug in your code. I would consider rewriting your code to have `options` actually be a set of defaults which you are (optionally) overriding with whatever's in `config`.

**Comment by jridgewell** [comment]
See https://github.com/jashkenas/underscore/issues/1565 for history. I wouldn't mind having `_.extend` and `_.defaults` default `null` / `undefined` to an empty array instead of returning early.

**Comment by balnagy** [comment]
Thanks for the link to history. Actually empty array still doesn't make sense to me if the defaults was defined.

> _.defaults(object, *defaults) 
Fill in undefined properties in object with the first value present in the following list of defaults objects.

I might interpret this wrong, but my expectation was that
1. it should always return an object
2. that object should contain all the properties from `defaults` if it was not present in `object`

**Comment by jridgewell** [comment]
Lol, typo. Corrected now.

**Comment by jgonggrijp** [comment]
This was adressed in #2232.
