### ISSUE TITLE
isFunction problem with flash applet functions in Safari

### ISSUE THREAD

**Issue by btamas** [jashkenas/underscore#2117]
I found a problem with _.isFunction. In my page, there is a flash applet and I want to call functions on it. When I use the _.isFunction function on an applet function, it says false.
I checked the implementation of this function and I found the problem, because in Safari the toString.call(appletFunction) returns with [object NPMethod] and not [object function].
The typeof appletFunction returns with "function", so it is working correctly.

**Comment by akre54** [comment]
May be related to #1929 and #1936. What version of Underscore are you using?

**Comment by btamas** [comment]
I'm using the newest version (1.8.2).
I saw this fixes that you mentioned, but in the line 1229 the typeof Int8Array != 'object' is false in my browser (Mac 10.10.2, Safari 8.0.3). So the method override does not execute in the next line.

**Comment by megawac** [comment]
@btamas can you try running `Object.prototype.toString.call(appletFunction)`. Also want to submit a failing test case?

**Comment by btamas** [comment]
It is the same: "[object NPMethod]"

**Comment by btamas** [comment]
@megawac I created a jsbin example: http://jsbin.com/yisewehivi/1/edit?html,js,console
The only problem with that is the cross-domain policy. If you want to test it, you should create an HTML based on this source and you should download the flash applet binary and embed locally.
This flash applet is a dummy flash applet that do nothing. It has an external empty test function and that's all.

**Comment by jashkenas** [comment]
I don't think that Underscore is supposed to necessarily have any specific behavior when it comes to interfacing with plugin objects. Talking to Flash? Talking to Java? Out of scope.
