### ISSUE TITLE
None function

### ISSUE THREAD

**Issue by megawac** [jashkenas/underscore#2118]
It can be useful (particularly in chains and composition) to have the inverse of `some` available. The main justification for this would be `iteratee` cases where you can't simply call `negate`.

The way this can be implemented is

```js
_.none = function(list, fn, context) {
   return !_.any(list, fn, context);
};
```

```js
_.none([{ a: 1, b: 2 }, { a: 2, b: 3 }], {b: 4}) // true
_.none([{ a: 1, b: 2 }, { a: 2, b: 3 }], {b: 3}) //false
```

Sure this can be done as a mixin but it's simple enough and pretty common case

Thoughts?

**Comment by jashkenas** [comment]
Why add `none` when you can just do `!_.any` ?

"There aren't any X that ..." is a pretty readable way to write this.

**Comment by stevematney** [comment]
I agree that `!_.any` is a pretty simple way to read this, but it seems easier to process mentally if you don't have to parse the `!`. There are fewer roadblocks in thinking when you don't have to compute the opposite of something.

**Comment by jashkenas** [comment]
And if we did this, wouldn't we want inverses of all our predicates?

**Comment by stevematney** [comment]
I don't really have an opinion on that. All I was commenting about was the simplicity of reading `_.none` vs `!_.any`. If you think that is good reasoning, and you think it would be easier to read other explicit opposites instead of `!` opposites, then you can decide to implement them. It's your package. :wink:

**Comment by jridgewell** [comment]
I'm not sure it's necessary. `_.none`, on the other hand, actually hides an optimized algorithm by using `_.any` under the hood. Every time I think of a `none` function, I always think of `!every` which doesn't end iteration early.
