### ISSUE TITLE
Change 'underscore-min.map' file name to 'underscore.min.js.map'

### ISSUE THREAD

**Issue by ArtemDevart** [jashkenas/underscore#2119]
'min.js' is standard extension for map files, some tools do not work with differ extensions.

**Comment by jashkenas** [comment]
`underscore-min.js.map` sounds fine to me.

**Comment by ArtemDevart** [comment]
Sorry, '.min.js' is for minified script, '.min.js.map' is for map.

**Comment by jashkenas** [comment]
Then, I don't think so.

> some tools do not work with differ extensions

What tools exactly?

**Comment by ArtemDevart** [comment]
Bundle Transformer do not understands -min.js extension (https://bundletransformer.codeplex.com/)
I have a lot of third-party scripts in my project, all of them except Underscore have .min.js extension. I think this is tacit convention.

**Comment by jashkenas** [comment]
It's not. In `file.min`, `.min` is not a valid file extension.

Open a ticket on Bundle Transformer, instead of here.
