### ISSUE TITLE
Need partition like function that splits an object into two

### ISSUE THREAD

**Issue by Pyrolistical** [jashkenas/underscore#2121]
The `partition` function is under the collection category, so I expected to be able to partition an object into two objects.  But what it current does it partitions the object members.

I want a function that is similar to `partition` but returns two objects.

For example

    var data = {
        a: true,
        b: false,
        c: true
    };
    var result = _.newPartitionObjectFunction(data, function(value, key) {
        return value;
    });

Expected result

    [
        {
            a: true,
            c: true
        },
        {
            b: false
        }
    ]

**Comment by jashkenas** [comment]
Sounds fine, but not for core Underscore. Try a plugin.
