### ISSUE TITLE
isObject returns true when _.isObject([1,2,3,4])

### ISSUE THREAD

**Issue by lvaldovinos** [jashkenas/underscore#2123]
Hi there!

Quick question about isObject function, i got the following example:

```javascript
var _ = require('underscore'); 
console.log(_.isObject([1,2,3])); //returns true
```

I know Arrays in javascript aren't truly arrays, they're object-like arrays. so this result makes sense, however what if i'd like to check if a variable is truly an object, meaning it could be either a function or an object literal {}.

so what if i'd like to get this:

```javascript
var _ = require('underscore'); 
console.log(_.isObject([1,2,3])); //returns false
console.log(_.isObject(function(){})); //returns true
console.log(_.isObject({ example : 1})); //returns true
```

Is there already a function where i can get the above behavior?

I saw isObject implementation:
```javascript
// Is a given variable an object?
_.isObject = function(obj) {
    var type = typeof obj;
    return type === 'function' || type === 'object' && !!obj;
  };
```
what do you think if isObject is implemented like this?:
```javascript
// Is a given variable an object?
_.isObject = function(obj) {
    var type = typeof obj;
    return type === 'function' || type === 'object' && !!obj && !(_.isArray(obj));
  };
```
with the above change you'd get the following results?:

```javascript
console.log(_.isObject([1,2,3,4,5,6])); //false
console.log(_.isObject(function(){})); //true
console.log(_.isObject({})); //true
```

**Comment by jridgewell** [comment]
That would be a pretty significant breaking change, so it's unlikely to happen. And as you've stated, arrays are objects which can have arbitrary properties added to them, which is the point of `_.isObject` (and the same reason functions are, too).

If you want to check if something is a plain object, you'll have to use a combination of `_.isObject`, `_.isArray(obj)`, and `_.isFunction`.

```javascript
var obj = {}, arr = [], fn = function() {};
_.isObject(obj) && !_.isArray(obj) && !_.isFunction(obj);
_.isFunction(fn);
_.isArray(arr);
```
