### ISSUE TITLE
isMatch deep comparison

### ISSUE THREAD

**Issue by DERIIIFranz** [jashkenas/underscore#2125]
As of 1.8.2 isMatch() doesn't support deep comparison of two objects. At line 1082 it says:

`attrs[key] !== obj[key]`

shouldn't it rather be:

`!_.isEqual(attrs[key],obj[key])`

?

**Comment by jridgewell** [comment]
`isMatch` is exactly the same in [v1.8.2](https://github.com/jashkenas/underscore/blob/1.8.2/underscore.js#L1065-L1075) as it was in [v1.8.0](https://github.com/jashkenas/underscore/blob/1.8.0/underscore.js#L1060-L1070), and uses the same comparison as `matches` in [v1.7.0](https://github.com/jashkenas/underscore/blob/1.7.0/underscore.js#L1177-L1188).

**Comment by DERIIIFranz** [comment]
how does that answer my question?

**Comment by jridgewell** [comment]
Oh, I took the `As of 1.8.2` to mean you thought the behavior had changed.

With the notable exception of `_.isEqual`, underscore has no other function that deals with deep comparisons.

**Comment by DERIIIFranz** [comment]
That's why I thought it would be useful to add the possibility of deep comparison privided by `_.isEqual`

**Comment by orensol** [comment]
Agree with @DERIIIFranz, isMatch should provide the option to deep match.

**Comment by jdalton** [comment]
@DERIIIFranz @orensol For deep matching see [lodash/isMatch](https://github.com/lodash/lodash/blob/4.14.1-npm/isMatch.js) or [lodash.ismatch](https://www.npmjs.com/package/lodash.ismatch).

**Comment by kittee** [comment]
what a shame

**Comment by linorabolini** [comment]
I just needed to compare objects recursively, so I extended it a bit. It is a custom one but it might be useful for someone. It supports recursive object check:

function(object, attrs, deep) {
    var keys = Object.keys(attrs), length = keys.length;
    if (object == null) return !length;
    var obj = Object(object);
    for (var i = 0; i < length; i++) {
      var key = keys[i];
	  if(deep && typeof attrs[key] === 'object') {
		if(!isMatch(obj[key], attrs[key])) return false;
      } else if (attrs[key] !== obj[key] || !(key in obj)) return false;
    }
    return true;
  };


// isMatch({a:2, b:{c:2}}, {a:2, b:{c:2}})   -> false
// isMatch({a:2, b:{c:2}}, {a:2, b:{c:2}})   -> true

// isMatch({a:2, b:{c:2}, d:[3]}, {a:2, b:{c:2},d:[3]})   -> false
// isMatch({a:2, b:{c:2}, d:[3]}, {a:2, b:{c:2},d:[3]}, true)   -> true
