### ISSUE TITLE
deep pluck

### ISSUE THREAD

**Issue by kohesion** [jashkenas/underscore#2126]
Could pluck be extended to do this?

For this object:
icecream = [
{
    producer: 'breyers',    
    details: {
        flavor: 'vanilla',
        color: 'white',
        spicy: false
    },
},
{
    producer: 'ben and jerries',
    details: {
        flavor: 'chocolate',
        color: 'brown',
        spicy: false
    },
},
{
    producer: 'generic',
    details: {
        flavor: 'cookies&cream',
        color: 'grey',
        spicy: false
    }
}]

_.pluck(icecream, 'details.color'); => ['white', 'black', 'grey']

**Comment by jridgewell** [comment]
Please check the [previous requests](https://github.com/jashkenas/underscore/issues?q=is%3Aissue+deep+pluck+is%3Aclosed).
