### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by odeke-em** [jashkenas/underscore#2128]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with underscore. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable underscore on @Sourcegraph by going to https://sourcegraph.com/github.com/jashkenas/underscore and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by jridgewell** [comment]
Hmm, seems maintainers can't give permission on personal repos, only the repo owner. Ping @jashkenas.

**Comment by akre54** [comment]
They really need a webhook set up for every single public repository? Why can't they cache / poll by default? Seems kinda wasteful.

**Comment by jashkenas** [comment]
Done.

**Comment by odeke-em** [comment]
Thank you everyone!
