### ISSUE TITLE
debounce function

### ISSUE THREAD

**Issue by elie29** [jashkenas/underscore#2129]
http://underscorejs.org/docs/underscore.html#section-82

Why testing timeout is necessary in later function while it is set to null?
at line 821:
![image](https://cloud.githubusercontent.com/assets/11255270/6893692/413c9e34-d6cf-11e4-9348-9483f7bc3115.png)

**Comment by akre54** [comment]
See #1629 for background. In the future, try the mailing list, the IRC channel, StackOverflow or the Gitter room for questions like this.

**Comment by elie29** [comment]
Ok thank you.
