### ISSUE TITLE
Chunk function

### ISSUE THREAD

**Issue by hhoechtl** [jashkenas/underscore#2130]
It would be really great to have a *chunk* function which splits an array into n equal parts.

Currently something like this can be done with the following code:

    _.chain(container.parameter).groupBy(function (el, idx) {
        return Math.floor(idx / 4);
    }).toArray().value();

But having this as ```_.chunk(array, numberOfChunks);``` would be really great.

**Comment by Florian-R** [comment]
See #1919 for a currently discussed PR.
