### ISSUE TITLE
_.isEmpty returns `true` for `true!?

### ISSUE THREAD

**Issue by elycruz** [jashkenas/underscore#2133]
Shouln't _.isEmpty return `false` for `true` (simliar to `empty` function in php: 
```
"" (an empty string)
0 (0 as an integer)
0.0 (0 as a float)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
$var; (a variable declared, but without a value)
```)

Or like lines 109-193 here:
https://github.com/elycruz/sjljs/blob/master/src/sjl/sjl-util-functions.js ?

**Comment by michaelficarra** [comment]
No, it shouldn't. Read the previous issues.

**Comment by jridgewell** [comment]
From the docs:

> Returns true if an **enumerable object** contains no values (no enumerable own-properties). For strings and array-like objects _.isEmpty checks if the length property is 0.

Please [check before](https://github.com/jashkenas/underscore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+isEmpty) opening an issue.

**Comment by elycruz** [comment]
k, apologies guys.

**Comment by elycruz** [comment]
and thanks for your help and speedy response on this :+1:
