### ISSUE TITLE
isUndefined Speed

### ISSUE THREAD

**Issue by unwitting** [jashkenas/underscore#2136]
`_.isUndefined` is defined as:

```javascript
// Is a given variable undefined?
_.isUndefined = function(obj) {
  return obj === void 0;
};
```

What's the justification for comparing to `void 0` instead of `undefined` itself? I made a [small jsperf](http://jsperf.com/is-undefined-methods) and it certainly comes out slightly faster to:

```javascript
return obj === undefined;
```

Is it because saving the 3 characters is seen as more valuable than the little bit of speed, or is there something subtler that I'm missing? 'Cus I'd hazard that `undefined` gzips really well :)

**Comment by jridgewell** [comment]
I'm not showing any speed boosts...

Additionally, `undefined` is a variable, not a literal like `true`, `false`, or `null`. In sloppy-mode javascript, the `undefined` variable can be reassigned to something that is not the `undefined` value. `void 0` is guaranteed to return the `undefined` value.

**Comment by JosephClay** [comment]
Why not pass `undefined` via the IIFE? Then `void 0` could be minified into a single character.

**Comment by michaelficarra** [comment]
Send a PR.

**Comment by JosephClay** [comment]
Will do

**Comment by JosephClay** [comment]
Hmm, it seems that using a safe undefined reference my be [significantly slower](http://jsperf.com/is-undefined-encapsulation) within an encapsulation.

Also, there's virtually no file size difference after gzipping...there's only 11 `void 0` usages in the lib.

**Comment by michaelficarra** [comment]
@josephclay I think you're missing the point that it's *safe*.

**Comment by JosephClay** [comment]
@michaelficarra I'm assuming that `void 0` is also safe based on @jridgewell 's comment. That would make this a stylistic change with a performance regression. 

Unless I'm still missing the point. I did just started drinking my morning coffee :)

**Comment by michaelficarra** [comment]
`void 0` is what I was referring to. I think we have a pronoun miscommunication here.

**Comment by jridgewell** [comment]
I'm confused too...

> @michaelficarra : @josephclay I think you're missing the point that it's safe.

I think "it" is `void 0` here? But @JosephClay is conceding that there's no point in changing this.

**Comment by JosephClay** [comment]
@jridgewell Yes. I'm conceding.

**Comment by michaelficarra** [comment]
Okay I think I understand now.

**Comment by unwitting** [comment]
Fair enough - `undefined` isn't trustably `undefined`, so we need a way to consistently return `undefined`. Seeing as underscore attempts to provide just such a thing in a standard form with `noop`, would it not be more maintainable to compare to `_.noop()`?

**Comment by unwitting** [comment]
(Honestly not trying to troll here - just noticed a bit of inconsistency (at least to my eyes) in what is an awesome and very widely-used utility library - the sort of library that can and should try to be as clean and performant as possible)

**Comment by unwitting** [comment]
To ramble on more, I thought the ability to assign a value to undefined and have it stick was last in ES3?

**Comment by jridgewell** [comment]
It'd be much slower to invoke `_.noop` than to just use `void 0`. From the jsperf, it's as fast as a literal.

Also, Underscore runs on ES3.

**Comment by unwitting** [comment]
@jridgewell I see a (small, but positive) speed gain in calling `noop()` in the much-reduced test case: http://jsperf.com/void-vs-noop - it's certainly no slower.

**Comment by unwitting** [comment]
OK, as for the ES3 / assigning to undefined thing, I can see wanting to protect against that. But in terms of creating a satisfactory reliable `undefined`, it looks to me like defining the way to do that once and then consistently using it would be preferable.

**Comment by jashkenas** [comment]
![image](https://cloud.githubusercontent.com/assets/4732/7048614/214863b4-dde2-11e4-8533-879b904cffd8.png)
