### ISSUE TITLE
Equivalent to "val != null"

### ISSUE THREAD

**Issue by sateffen** [jashkenas/underscore#2144]
Hey,

I've run into a "problem", that I've got across multiple projects. In JSHint we prevent the !=, so we need to do !== (script equal).

Because of this, I'm used to creating a mixin, which just is like:

    _.mixin({
        isDefined: function (aValue) {
            return aValue !== null && aValue !== undefined;
        }
    });

I use this mixin in every project with underscore again, so I think it is worth to tell you about this. Maybe some other people know my situation, and it's a nice idea for underscore by default, and I didn't see another request for this.

Additionally, this is a better way then relaying on the 'val != null' behavior.

Any thoughts?

**Comment by jridgewell** [comment]
We've gotten one request so far: #2051.

However, there's nothing wrong with `== null`. There's even a [flag](http://jshint.com/docs/options/#eqnull) for allowing just it in jshint.
