### ISSUE TITLE
proposal: remove sourceMappingUrl from distributed version of underscore.js

### ISSUE THREAD

**Issue by nikolas** [jashkenas/underscore#2145]
jQuery removed their sourcemap comment a while ago:
* http://bugs.jquery.com/ticket/14415
* http://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/

In the mean time, I need to remember to remove the comment every time I update underscore.js if I want to prevent the 404 error.

**Comment by jashkenas** [comment]
Sourcemaps are also a little less interesting these days because of Chrome's ability to "decompile" and pretty-print minified JS. Sounds fine.

**Comment by lieut-data** [comment]
This is a problem for applications that directly inject `underscore-main.js` into their build pipeline and then try to use the `X-SourceMap` header for the overall file. Chrome, in particular, sees the inline comment and trumps any value specified in the `X-SourceMap` header.

I'd like to also propose that this comment be removed as such.
