### ISSUE TITLE
isArrayLike returns true if object contains a property named 'length'

### ISSUE THREAD

**Issue by m-zhou** [jashkenas/underscore#2149]
var property = function(key) {
    return function(obj) {
      return obj == null ? void 0 : obj[key];
    };
      };
    var MAX_ARRAY_INDEX = Math.pow(2, 53) - 1; 
    var getLength = property('length'); 
    var isArrayLike = function(collection) { 
      var length = getLength(collection); 	
      return typeof length == 'number' && length >= 0 && length <= MAX_ARRAY_INDEX; 
    };

`console.log(isArrayLike({one: 1, two: 2, three: 3}));`
->false
    `console.log(isArrayLike({length: 1, two: 2, three: 3}));`
->true

Another example:
`_.each({one: 1, two: 2, three: 3}, console.log);`
->1 "one" [object Object]
->2 "two" [object Object]
->3 "three" [object Object]

`_.each({length: 1, two: 2, three: 3}, console.log);`
->undefined 0 [object Object]

`_.each({one: 1, length: 2, three: 3}, console.log);`
->undefined 0 [object Object]
->undefined 1 [object Object]

**Comment by d10** [comment]
This is intentional.
