### ISSUE TITLE
underscore is sometimes a string in opera

### ISSUE THREAD

**Issue by joker-777** [jashkenas/underscore#2151]
Hi,

sometimes `_` is a string in opera under Windows which then results into
```
TypeError: string is not a function
```
Have you experienced similar errors? Do you know why this could happen?

Thanks for your awesome library,

Johannes

**Comment by jashkenas** [comment]
Some other script is overwriting the `_` variable. Try using `_.noConflict()` in your app.

**Comment by joker-777** [comment]
Thanks for your quick reply. Doesn't this mean that we have to find a variable where we are certain that no external plugin/extension would overwrite it? Then we would have to replace all `_` with this new variable. Is there no other way to ensure that this doesn't happen?

**Comment by jridgewell** [comment]
You can already do that with `#noConflict`

```html
<script src="underscore.js"/></script>
<script>
    var myUnderscoreVar = _.noConflict();
</script>
```

Either way, it's untenable to choose a globally unique name. Using a module system will prevent these issues, or open an issue against whatever's clobbering `_`.
