### ISSUE TITLE
Difference of two NodeLists returns every element

### ISSUE THREAD

**Issue by murphybob** [jashkenas/underscore#2156]
The _.difference method should return an array containing only elements which are present in the first array but not in any of the subsequent array.  If you pass it 2 NodeLists it always returns all the elements in the first list regardless of which elements appear in both.

```javascript
    divs = document.querySelectorAll("div");
   _.difference(divs, divs);
```

returns an array which contains every element from 'divs'.  It would be super if difference could handle NodeLists as if they were arrays, as it's a useful case. The core logic of the function works on NodeLists so

```javascript
_.filter(divs, function(el){ return !_.contains(divs, el); });
```

returns the expected result.

**Comment by PatrickStankard** [comment]
I've learned that [Underscore isn't meant to address host objects](https://github.com/jashkenas/underscore/issues/1138#issuecomment-19110640), so I think the best thing you can do is to `_.toArray()` the `NodeList`s before using `_.difference()`, which would work as you'd expect:

```js
var divsArray = _.toArray(document.querySelectorAll('div'));
_.difference(divsArray, divsArray); // []
```

**Comment by akre54** [comment]
Yep, @PatrickStankard is right here.
