### ISSUE TITLE
Example of _.unzip on _.homepage wrong?

### ISSUE THREAD

**Issue by smartmuki** [jashkenas/underscore#2159]
_.unzip(["moe", 30, true], ["larry", 40, false], ["curly", 50, false]);
=> [['moe', 'larry', 'curly'], [30, 40, 50], [true, false, false]]

This is actually the output of zip. 
Unzip returns : 
=> [['m', undefined, undefined], ['o', undefined, undefined], ['e', undefined, undefined]]

The test was run on  Underscore.js 1.8.3 

Thanks.

**Comment by carltonf** [comment]
I think it's a homepage typo.
