### ISSUE TITLE
The link to the development version on the homepage goes to a minified version

### ISSUE THREAD

**Issue by maniexx** [jashkenas/underscore#2166]
The link which is supposed to go to a development version with plentiful comments, in fact links to a minified version.

**Comment by megawac** [comment]
Can't reproduce - it links to [http://underscorejs.org/underscore.js](http://underscorejs.org/underscore.js) - perhaps try clearing your cache?

**Comment by maniexx** [comment]
For me, the version at http://underscorejs.org/underscore.js is still minified, no matter what browser I use. Sure, it's a different link than the minified version, but not a development version with comments.

**Comment by michaelficarra** [comment]
@maniexx: Post the output of curl with -v enabled to a gist. This resource is not minified. I will be very surprised if what you see is minified.

**Comment by maniexx** [comment]
Sorry, this seems to indeed have been a caching issue. Somehow it happened on both my browsers, which misled me. Sorry for bothering you.
