### ISSUE TITLE
_.template function does not accept inline data variable.

### ISSUE THREAD

**Issue by aamir2007** [jashkenas/underscore#2173]
As title suggests _.template function does not accept inline data variable. It was working fine previously. But since I tried version 1.8 as it supports _.findkey but it stopped working with inline Data variables for the _.template function.

**Comment by jridgewell** [comment]
We removed the data from `_.template`, you now have to invoke the returned function.

```javascript
_.template(templateString)(data);
_.template(templateString, options)(data);
```

**Comment by aamir2007** [comment]
Hello jridgewell,

Thanks for your response and clarification. I am aware of this change. But what about those apps which are previously using data variable inline with _.template function. They will stop working something that happened with my app. It has so many template calls and will require to revise all of them. So all existing apps that are using data variable inline does not support the latest version of underscore.js 
I think there should have been a way for backward compatibility as this is a great framework and is being used in many modern apps and should be taken care of the backward compatibility while disclosing new versions. Currently it's giving impression of immature framework.
