### ISSUE TITLE
I want to _.each Loop break from Middle.

### ISSUE THREAD

**Issue by higunjan** [jashkenas/underscore#2174]
Hello their,
       I have some array and matching into some string For that array I used _.each loop . Now I have to break the loop when found result. Is that Possible any way. I know that for-Each doesn't provide that Functionality. If any Idea what I have to DO next.

**Comment by Florian-R** [comment]
Just use [_.some](http://underscorejs.org/#some). Anyway, please answer questions on Stackoverflow or IRC.
