### ISSUE TITLE
How to sortBy by second level (subkey) of JSON object?

### ISSUE THREAD

**Issue by mangowebdesign** [jashkenas/underscore#2186]
I have an example JSON array I would like to sort. However, I would like to sort by attributes.Country (a second level) rather than a first level like label.

```javascript
[
   {
      "label":"Ha Dae-sung",
      "id":"268",
      "attributes":{
         "Country":"South Korea"
      }
   },
   {
      "label":"Maxi Pereira",
      "id":"486",
      "attributes":{
         "Country":"Uruguay"
      }
   },
   {
      "label":"Manabu Saito",
      "id":"441",
      "attributes":{
         "Country":"Japan"
      }
   }
]
```

I can sort just fine on the first level using _.sortBy. For instance, to sort by just the label.

```javascript
searched = _.sortBy(searched, "label"); 
```

However, I want to get a sorted array by Country within attributes. How would I set up a second level sort?

**Comment by missedtheboat** [comment]
Getting an array sorted by country can be achieved by using a function as the iteratee. This should work for you -

```
searched = _.sortBy(searched, function(obj) { return obj.attributes.Country; });
```

**Comment by mangowebdesign** [comment]
thank you so much! this worked!
