### ISSUE TITLE
`func.apply` in `_.once` and `_.before` is breaking my asynchronous validations with Judge

### ISSUE THREAD

**Issue by zacharyabresch** [jashkenas/underscore#2195]
Hi. I have been using [Judge][1] for some client-side validations on a Rails project and experienced some errors. Initially I thought it was something to do with my code or the Judge gem but eventually I traced it back to the `underscore.js` library which is packaged with Judge. I upgraded the Underscore version which did *not* resolve the problem (I was hopeful it was just a version issue).

You can view my issue on the Judge repo [here][2] but I'll reproduce my post here as well.

***

Hi. I've been working on a Coffeescript class to handle Judge validations. It is based off a Javscript I found [here][3]. It's throwing errors related to Underscore.js.

When I instantiate my class `judgment = new JudgeJudy({form: $("#new_suggestion")})` I'm seeing this error in the console:

```
Uncaught TypeError: func.apply is not a function
```

and it references line 683 in the Underscore.js library.

***

Here's that Coffeescript:

```coffeescript
# This class was inspired by code found
# here: http://blog.bananacoding.com/blog/client-side-form-validation-using-judge-gem

@JudgeJudy = class JudgeJudy
  constructor: (@options)->
    @form = @options.form
    @validate_form()

  valid: (element, deferred)->
    $(element).removeClass('error').addClass('valid')
    deferred.resolve()

  invalid: (element, deferred)->
    $(element).removeClass('valid').addClass('error')
    deferred.reject()

  validate_form: ->
    that = @
    @form.on 'submit', (event) ->
      event.preventDefault()
      $('.error_container').empty()

      defers = []

      that.form.find('.form-control').each (index, element)->
        defers.push(that.validate_input_async(element))

      $.when.apply($, defers).done ->
        that.form.unbind 'submit'
        that.form.submit()

  validate_input_async: (element)->
    deferred = new $.Deferred()

    q = judge.validate element,
      valid:
        @valid element, deferred
      invalid:
        @invalid element, deferred

    deferred.resolve() if q.validations.length
    deferred
```

I was poking around the Judge repository and noticed that the Underscore version in use is 1.4.4 but Underscore.js is currently at 1.8.3. I'm not sure if it's my code, Underscore, or something else but I'm wondering how you would recommend I update this Underscore library to the latest version to see if that resolve my issue. 

I struggled for a whole day thinking it was *my* call to `apply` on `$.when` that was throwing the error but then I got smart and actually looked at the error message closely. :smile_cat: 

If you've got any feedback or ideas I'm *all* ears!!

***

Anyone have any ideas on what could be causing this issue?

[1]:https://github.com/joecorcoran/judge
[2]:https://github.com/joecorcoran/judge/issues/59
[3]:http://blog.bananacoding.com/blog/client-side-form-validation-using-judge-gem

**Comment by zacharyabresch** [comment]
As a side note, I upgraded the Underscore library to version 1.8.2 using the [underscore-rails][1] gem to no avail. Haven't gone the route of manually upgraded to 1.8.3 yet.

[1]:https://github.com/rweng/underscore-rails

**Comment by jridgewell** [comment]
The error is in your code:

```js
    q = judge.validate element,
      valid:
        @valid element, deferred
      invalid:
        @invalid element, deferred
```

This doesn't create two callback functions, it _calls_ `#valid` and `#invalid`. See the [compiled JS](http://coffeescript.org/#try:deferred%20%3D%20new%20%24.Deferred()%0A%0Aq%20%3D%20judge.validate%20element%2C%0A%20%20valid%3A%0A%20%20%20%20%40valid%20element%2C%20deferred%0A%20%20invalid%3A%0A%20%20%20%20%40invalid%20element%2C%20deferred).

**Comment by zacharyabresch** [comment]
OMG you freaking :rocket:!!! This is what I get for coding in isolation for so long. You were totally right. In case anyone needs to know, this is the fix that did it. 

```coffeescript
q = judge.validate element,
      valid: (element)=>
        @valid element, deferred
      invalid: (element)=>
        @invalid element, deferred
```

Thanks so much. I can actually call this feature complete and move on.
