### ISSUE TITLE
Documentation Doesn't Include Built-in Array Methods

### ISSUE THREAD

**Issue by machineghost** [jashkenas/underscore#2200]
Underscore includes `concat`, `join`, and `slice` methods (taken from the built-in JS equivalents), but there's no mention of this feature in the documentation.  I think the documentation used to mention these methods, and it seems like it would be nice to (at least briefly) mention of them so that new users can be aware that they exist (without having to read the source code).

**Comment by akre54** [comment]
[From the docs:](http://underscorejs.org/#chaining)
> ### Chaining
...
In addition, the [Array prototype's methods](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Array/prototype) are proxied through the chained Underscore object, so you can slip a reverse or a push into your chain, and continue to modify the array.

**Comment by machineghost** [comment]
Would it be possible to add a sub-heading for "Array.prototype Methods" or something to that effect?  Right now if you are going by the table of contents there is nothing to indicate that chaining involves anything other than `chain` and `value`.

**Comment by akre54** [comment]
Go for it. Open a pull.
