### ISSUE TITLE
toArray increasing order keys

### ISSUE THREAD

**Issue by vyhuhol** [jashkenas/underscore#2201]
Hello,

Thank you very much for such a great project.

I found one interesting undocumented feature of toArray.
If you try to convert object, where the keys are numbers. to Array will convert them in increasing order.

var ob = {'4':1,'2':2,'1':3}
var b = _.toArray(ob)
//[3 2 1]

Can you confirm that this is a consistent behavior?

**Comment by jridgewell** [comment]
That's browser implementation specific, and not guaranteed. It just happens most browsers will sort keys on an object, then iterate over them in sorted order.

**Comment by jdalton** [comment]
Iteration order is now specified in ES2015.

**Comment by vyhuhol** [comment]
I am using it in node.js from console

**Comment by jdalton** [comment]
Yap, it's been largely consistent across engines for a while.

**Comment by jridgewell** [comment]
Awesome, I wasn't aware object iteration was defined.
