### ISSUE TITLE
Add isElement and noConflict tests

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2206]
Based on [coveralls](https://coveralls.io/builds/2734426/source?filename=underscore.js) tests for `_.isElement` and `_.noConflict` are missing.

The `_.isElement` test is missing because of running the node flavor but could be hit if adjusted for phantomjs.

**Comment by jgonggrijp** [comment]
`_.isElement` is tested, just not in Node where coverage testing with nyc is easiest. `_.noConflict` is not part of our source code anymore as of #2826.
