### ISSUE TITLE
_.reduce() doesn't work on objects with numeric attributes

### ISSUE THREAD

**Issue by binarykitchen** [jashkenas/underscore#2207]
I tried something like

```
_.reduce(@props.cosList, (cos) -> console.log cos)
```

whereas

```
@props.cosList = {
  0: Object ...
  1: Object ...
};
```

but `reduce()` somehow isn't iterating. Any clues?

**Comment by michaelficarra** [comment]
I cannot reproduce this. Feel free to re-open with a minimal reproduction case.

**Comment by binarykitchen** [comment]
ah, i found the bug on my side - all good now
