### ISSUE TITLE
_.max should ignore null values

### ISSUE THREAD

**Issue by trose89** [jashkenas/underscore#2218]
_.max currently has strange behavior if the dataset you're evaluating contains nulls.

Basically you can run into some indeterminate behavior depending on the order of your data
sooo...
```
_.max([null, 0]) => null
```
but
```
_.max([0, null]) => 0
```

While you _could_ just go ahead and filter your data, I don't really see any advantages to leaving it this way.

Cause: line 310
```
for (var i = 0, length = obj.length; i < length; i++) {
    value = obj[i];
    if (value > result) {
        result = value;
    }
}
```

Both `(null > 0)` and `(0 > null)` evaluate to false.

I'm willing to push a PR with some unit tests but I just wanted to get some other opinions first

**Comment by megawac** [comment]
I think the going advice for this case is if you have a dataset that could have `null` and numbers in it is to do a `compact` prior to computing the max (as `0 == null`)

```js
_.max(_.compact(array));
```

**Comment by braddunbar** [comment]
Filtering is fine, though I might argue that no one ever wants the current implementation. Is there any reason someone might want the maximum unless a null value exists in an implementation-specific position? I recently ran into a Real Life Bug™ due to this and had to use `d3.max`/`d3.min` instead.

**Comment by jdalton** [comment]
Coercion: Takes the good as well as the bad.

**Comment by michaelthe** [comment]
i think a good balance will be to add a filter argument to max like so 
```javascript
_.max([2, 5, 20] , function(value, key){ return value < 10 });
// result:  5
```
this way you can either filter the dataset or bound the result.

**Comment by jdalton** [comment]
> i think a good balance will be to add a filter argument to max like so

`_.max` and `_.min` already accepts a callback.

**Comment by jashkenas** [comment]
> I recently ran into a Real Life Bug™ due to this and had to use d3.max/d3.min instead.

Strong stuff.

**Comment by jgonggrijp** [comment]
Message from the future: this was not a bug. `+null` evaluates to `0`.
