### ISSUE TITLE
Tests missing from nodejs.org package

### ISSUE THREAD

**Issue by orlitzky** [jashkenas/underscore#2220]
Hello, I'm working on creating a distro package for underscorejs and we'd like to run the test suite before we install anything. The tarball I get from github has the `test` directory, but the one from npmjs.org doesn't. I think this is because of the 'files' entry in package.json? If so, might you include the tests?

**Comment by orlitzky** [comment]
Ah, I just noticed `docs` is missing too.

I can always grab these from github, but it's nice to have everything available through the npm registry because then we can script the creation of new packages.

**Comment by akre54** [comment]
I'm not sure what you mean by "script the creation of new packages", but it seems like your use case would be better served by simply cloning the git repository. npm is doing too much (and giving you too little) for your needs.

**Comment by orlitzky** [comment]
I'm creating a distro package for underscore.js. Using git is undesirable, because now every end user needs to have git installed before he can install underscore. That adds between 20 and 100 dependencies to the list, all to fetch a few files. It's easier to just grab the tarball from the github releases page where it's not missing the tests/docs.

I'm only bugging you because the default "get everything from npmjs.org, build it, test it, and install it" code is already written. Having to get underscore from a different place means we can't use the default implementation, but it's not a big deal.

**Comment by michaelficarra** [comment]
Underscore is far from the only package not including its tests in the npm distribution. It's considered a best practice. You were going to have to deal with this eventually.
