### ISSUE TITLE
Documentation: Unable to scroll sidebar in Safari

### ISSUE THREAD

**Issue by alexking** [jashkenas/underscore#2222]
In Safari (tested 8.0.5), if you scroll the documentation content by at least a page, you're no longer able to scroll the navigation sidebar. Scrolling the sidebar works on initial page load, and it also works if you scroll the content back to the top and move your mouse in and out of the sidebar. 

I'm pretty sure it has to do with the `#sidebar` having `position: fixed`, which Safari is traditionally terrible with. It seems like scrolling the main page is actually moving the scrollable area of the sidebar out of view. I haven't been able to find a solution for this bug yet, but I thought I'd at least log it for now.

**Comment by akre54** [comment]
Thanks for bringing this up. We are [aware of this](https://github.com/jashkenas/backbone/issues/3416) but fixing the bug in Safari would [break our docs page](https://github.com/jashkenas/backbone/issues/3416#issuecomment-74766410).
