### ISSUE TITLE
Feature request: AtLeast, AtMost

### ISSUE THREAD

**Issue by falafflepotatoe** [jashkenas/underscore#2223]
heres an easy one, i always hate typing this one out:

 - atLeast (cnt, value, array) returns bool
 - atMost (cnt, value, array)  returns bool

example:

    animals = [ 'cat','dog','bear','cat' ]
    if (_atLeast(2, 'cat', animals))
      feedcats()

replaces

    animals = ['cat','dog','bear','cat']
    cnt = 0;
    for (animal of animals){
      if (animal == 'cat'){
        cnt += 1
      }
    }
    if (cnt > 2){
         feedcats()
    }

**Comment by michaelficarra** [comment]
```js
_.atLeast = function(pred, n, list) {
  return _.filter(list, pred).length >= n;
}
_.atMost = function(pred, n, list) {
  return _.filter(list, pred).length <= n;
}
```

I don't think these are either particularly common or substantially more succinct than their implementation.

For very large lists, I guess this implementation would be more efficient, though I still don't think this is commonly needed:

```js
_.atLeast = function(pred, n, list) {
  var i = 0, l = list.length;
  while (n > 0) {
    --n;
    for (; i < l; ++i) {
      if (pred(list[i])) continue;
    }
    return false;
  }
  return true;
}
```
