### ISSUE TITLE
_.has({}, []) should return true

### ISSUE THREAD

**Issue by reggi** [jashkenas/underscore#2225]
`_.has({}, [])` and `_.has({})` should technically return true, because the object does have nothing?

**Comment by megawac** [comment]
`_.has` doesn't take an array or undefined as the second argument so returning false seems correct

**Comment by akre54** [comment]
I think you're misunderstanding the use of `has`. It's only really used to check if the key (a string) exists in the object. An array isn't an empty value, and neither is Undefined.

**Comment by reggi** [comment]
Thanks all.

I create a `hasOnly` mixin to return true if object has only the provided keys

```
_.mixin({
  hasOnly: function(obj, keys){
    if(_.difference(_.keys(obj), keys) == 0) return true
    return false
  },
})
```

So when you run `console.log(_.hasOnly({}, []))` you are kind of expecting `true` I realize it's not the same for `_.has`. At the time of writing this issue I was using `_.has` for a more complicated version of this mixin.
