### ISSUE TITLE
lastIndexOf doc looks wrong

### ISSUE THREAD

**Issue by kswope** [jashkenas/underscore#2230]
>
lastIndexOf_.lastIndexOf(array, value, [fromIndex]) 
Returns the index of the last occurrence of value in the array, or -1 if value is not present. Pass fromIndex to start your search at a given index.

The behavior and the docs to match.  lastIndexOf with a fromIndex doesn't even make sense.

```
 log( _.lastIndexOf( [ 0, 1, 2, 3, 4 ], 2, 0 ) ) //=> -1                                                                                           
 log( _.lastIndexOf( [ 0, 1, 2, 3, 4 ], 2, 1 ) ) //=> -1                                                                                           
 log( _.lastIndexOf( [ 0, 1, 2, 3, 4 ], 2, 2 ) ) //=>  2                                                                                           
 log( _.lastIndexOf( [ 0, 1, 2, 3, 4 ], 2, 3 ) ) //=>  2                                                                                           
 log( _.lastIndexOf( [ 0, 1, 2, 3, 4 ], 2, 4 ) ) //=>  2


```

**Comment by megawac** [comment]
The behaviour matches the documentation though could be worded better. The `[fromIndex]` indicates the index the search will begin at and then decrements from that value.

If you want to, please submit a pull request with better wording

**Comment by kswope** [comment]
What am I missing? if you have an array

```
[0,1,2,3,4,5,6,7,8,9]
```
If you want the last index of 6, what does it matter where you start your search from, it will always be the last - unless you start at 7 of course.

The behavior looks like fromIndex should be upToIndex, or stopSearchingIndex

Look at my example here

```
 log( _.lastIndexOf( [ 0, 1, 2, 3, 4 ], 2, 0 ) ) //=> -1                                                                                           
```

Why is this returning -1 if the search is starting at 0?

I think the search is stopping at 0, which is why when you set the upToIndex to 2, you get your first hit

```
log( _.lastIndexOf( [ 0, 1, 2, 3, 4 ], 2, 2 ) ) //=>  2                                                                                           
```

**Comment by megawac** [comment]
I think we mostly summarized mozilla's documentation, again feel free to submit a commit with changes clarifying the docs

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf

**Comment by kswope** [comment]
>
The lastIndexOf() method returns the last index at which a given element can be found in the array, or -1 if it is not present. The array is searched BACKWARDS, starting at fromIndex.

Forgot the backwards part, that explains why its so confusing.
