### ISSUE TITLE
Enable the creation of more maintainable variadic functions

### ISSUE THREAD

**Issue by mlanza** [jashkenas/underscore#2235]
It's common when defining functions to handle a varying number of arguments.  I've seen all sorts of code that attempts to figure out from the arguments what was intended by the invocation and it sometimes is not pretty.

Here's code I took straight out of transducers-js:

    transducers.transduce = function(xf, f, init, coll) {
        if(arguments.length == 3) {
            coll = init;
            if(typeof f == "function") {
                throw new Error("If given only three arguments f must satisfy "+
                                "the ITransformer interface.");
            } else {
                init = f["@@transducer/init"]();
            }
        }
        f = typeof f == "function" ? transducers.wrap(f) : f;
        xf = xf(f);
        return transducers.reduce(xf, init, coll);
    };

Notice that part of the logic is devoted to shuffling arguments.  This convoluting practice is by no means infrequent.  I recommend a simple fix.  By providing a dead simple means of dispatching based on the number of arguments actually passed we could better rewrite the above method as:

    transducers.transduce = variadic(null, null, function(xf, f, coll){
      if(typeof f == "function") {
        throw new Error("If given only three arguments f must satisfy "+
                          "the ITransformer interface.");
      }
      return transducers.transduce(xf, f, f["@@transducer/init"](), coll);
    }, function(xf, f, init, coll) {
        f = typeof f == "function" ? transducers.wrap(f) : f;
        xf = xf(f);
        return transducers.reduce(xf, init, coll);
    };

It's far and away easier to read and it makes it much easier to see when the error checking is necessary.  The performance hit is a small price to pay to improve the maintainability of the function.  Consider the cost a developer pays when trying to understand argument shuffling; even 10 seconds would be a significant hit when you consider how widely the practice is used and how many functions are affected.  This issue can be eliminated.

Notice that omitted arities are obvious (via `null`).  We don't handle arity 0 and 1.  This causes attempted invocations at that arity to fail directly as they should.  Notice also that this style allows self-reference so that an implementation of one artiy can use another.  Here's the actual method:

    function variadic(){
      var fs = arguments;
      return function variadic(){ //curry a named fn to aid debugger introspection
        return fs[arguments.length].apply(this, arguments);
      }
    }

The dispatch logic with this approach is damn simple and incredibly obvious.  It forces the increasingly more complex arities toward the bottom.  I know few functions accept 0 arguments; however, having to add lead nulls is a small price to pay to have such a straightforward implementation.

Here's Clojure's `range` implemented using this approach.  It does use the zero arity.

    var range = variadic(function(){
      var MAX_INT = 9007199254740992;
      return range(0, MAX_INT);
    }, function(end){
      return range(0, end);
    }, function(start, end){
      return range(start, end, end > start ? 1 : -1);
    }, function(start, end, step){
      return iterate(function(prev){
        var next = prev + step;
        if (next < end)
          return next;
      }, start);
    });

Now see if you can rewrite it without `variadic` and produce as good a result.

**Comment by jdalton** [comment]
Variadic methods aren't really an issue for Underscore. It's not like it goes against their philosophy or something. Also this seems heavy on the fp side of things which is fine but doesn't mesh well with Underscore considering there's not even a `_.curry` at the moment. I think this would be a great candidate for a mixin.
