### ISSUE TITLE
_.unzip desc on the doc is wrong?!

### ISSUE THREAD

**Issue by magicly** [jashkenas/underscore#2238]
on the http://underscorejs.org/#unzip,  
unzip_.unzip(*arrays) 
The opposite of zip. Given a number of arrays, returns a series of new arrays, the first of which contains all of the first elements in the input arrays, the second of which contains all of the second elements, and so on. Use with apply to pass in an array of arrays.

_.unzip(["moe", 30, true], ["larry", 40, false], ["curly", 50, false]);
=> [['moe', 'larry', 'curly'], [30, 40, 50], [true, false, false]]

But when eval 
```
_.unzip(["moe", 30, true], ["larry", 40, false], ["curly", 50, false]);
```
the result is:
```
[["m", undefined, undefined], ["o", undefined, undefined], ["e", undefined, undefined]]
```

I think the doc should be 
_.unzip([['moe', 'larry', 'curly'], [30, 40, 50], [true, false, false]])
=>["moe", 30, true], ["larry", 40, false], ["curly", 50, false]

the input and out put reverse...

**Comment by akre54** [comment]
Indeed it should. Good catch. Want to open a pull request?

**Comment by jridgewell** [comment]
@akre54 Shouldn't we leave this open until we get a PR?
