### ISSUE TITLE
_.findWhere returns the first element in array if prob value is `falsy` 

### ISSUE THREAD

**Issue by oaleynik** [jashkenas/underscore#2240]
Is it the expected behaviour when passing the `falsy` value as the second argument to the `_.findWhere` it returns the first element from the array?

For instance:

```javascript
var list = [{a: 1}, {a:2}, {a:3}];
var prob = null; // undefined, 0, false or {}
var result = _.findWhere(list, prob);

// result is {a: 1}
```

For me it is not correct. At https://github.com/jashkenas/underscore/blob/master/underscore.js#L1116 if attrs.length is 0 `underscore` thinks object matches prob. And it will be always the case for the `falsy` values 'cause prob will be converted to the empty object by `_.extendOwn` and than to the empty array of `attrs` via `_.keys`

**Comment by jdalton** [comment]
`prob` is seen as empty so you're choosing to match everything (so it hits the first element).

**Comment by oaleynik** [comment]
@jdalton sounds like it is expected behaviour. Unfortunately it is not the first time I see when `underscore` consumers use `_.findWhere` in the wrong way. So this ticket is just for the future reference (probably will be better to cover it in documentation, or throw error when `prob` has unexpected type). Closing this for now.
