### ISSUE TITLE
Array methods

### ISSUE THREAD

**Issue by raymond-lam** [jashkenas/underscore#2241]
The fact that `Array.prototype` methods are part of `_.prototype` is quite convenient. I was wondering if there was a reason that these methods are not part of `_` itself. 

In terms of symmetry/consistency it might make sense if `_.push(foo, bar)` were equivalent to `_(foo).push(bar)` just as `_.first(foo)` is equivalent to `_(foo).first()`

**Comment by raymond-lam** [comment]
Also worth noting that the Array methods are [not documented](http://underscorejs.org) besides in the annotated source.

**Comment by akre54** [comment]
It's because they're meant to be used while chaining. `_.push(arr, item)` isn't all that useful when `arr.push(item)` is more succinct. They're currently documented, [albeit subtly](http://underscorejs.org/#chaining) under chaining.

**Comment by raymond-lam** [comment]
What about with the arguments object? I could see _.slice(arguments, 1) being a nice symmetric complement to _(arguments).slice(1) (which is certainly a nice alternative to Array.prototype.slice.call(arguments, 1) ).
