### ISSUE TITLE
_.sortBy option for sorting null values to end

### ISSUE THREAD

**Issue by jvincilione** [jashkenas/underscore#2244]
Currently, _.sortBy doesn't sort null values. I believe an optional param to decide what to do with null and possibly undefined (which currently defaults to end) would be a good feature. 

It's a pretty simple addition, and I have already coded the feature into a project I'm working on, and can a do a PR if you believe this is a feature worth adding.

**Comment by megawac** [comment]
Hey, there are a number of issues currently open related to sort order for spurius values (namely NaN and undefined) #1768 https://github.com/jashkenas/underscore/pull/2041  #2042  and others.

We're probably going to leave `null` as is; but it should be easy enough to handle in the comparator function
