### ISSUE TITLE
_.sortBy used `index` param for stable sort but it may be an object key.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2246]
Currently `_.sortBy` uses the `index` param for its support of stable sorting but when iterating an object that value is a key. The method should track a separate variable for the index.

**Comment by megawac** [comment]
This is sort of mixed bag as this makes assumptions about the sort order of `Object.keys`. I'm honestly not sure if changing this would be a win

**Comment by jdalton** [comment]
There are enough environments where iteration order is de facto that it shouldn't matter. A note on the label this is more of a bug fix than a change as the method is already documented to perform a stable sort.

```js
    var index = 0;
    return _.pluck(_.map(obj, function(value, key, list) {
      return {
        value: value,
        index: index++,
        criteria: iteratee(value, key, list)
      };
    })
```

**Comment by jridgewell** [comment]
Seems good to me. @jdalton, want to open a PR?
