### ISSUE TITLE
_.findWhere is not a function

### ISSUE THREAD

**Issue by medaamarnadh** [jashkenas/underscore#2248]
Hi , I am using underscore js in my web application through bower components which is version 1.8.3.
Underscore is working fine generally . I was getting an error when i uglify this underscore.js with other files .
The error _.findWhere is not a function . 

In my browser console i gave Object.keys(_) .In that array i did not found findWhere function .

Please help me

**Comment by akre54** [comment]
I just tried installing with bower and everything seems fine. You may have a duplicated Underscore dependency in your app.

Try the mailing list, StackOverflow, or search on bower's issues for some solutions. Underscore's github issues are for bugs with the library only.

**Comment by medaamarnadh** [comment]
Hey thank you for the response. I solved the issue already . This is because of flotr.js .This problem will arise when we uglify underscore.js and after flotr.js in this orders. But i solved the issue by  changing the order . 

The reason is in flotr.js it is using var  _ internally in its library files .

Anyway thank you for the response .

**Comment by akre54** [comment]
In the future, use [`_.noConflict`](http://underscorejs.org/#noConflict) or try a build tool like browserify or webpack. It's a much more resilient solution to this kind of thing.
