### ISSUE TITLE
_.uniq iteratee function does not seem to transform values

### ISSUE THREAD

**Issue by sndsgn** [jashkenas/underscore#2256]
`_.uniq( [7, 7, 11, 23], true, function(value) {return value * 3;} );
--> [7, 11, 23]
`

Does the iteratee parameter passed to <strong>_.uniq</strong> transform values? In the source, the values being pushed to the result array do not seem to interact with the iteratee.

<pre>
    <code>
    _.uniq = function(array, isSorted, iteratee, context) {
        if (!_.isBoolean(isSorted)) {
          context = iteratee;
          iteratee = isSorted;
          isSorted = false;
        }   
        var result = []; 
        var seen = []; 
        for (var i = 0, length = getLength(array); i < length; i++) {
          var value = array[i],
              computed = iteratee ? iteratee(value, i, array) : value;
          if (isSorted) {
            if (!i || seen !== computed) <strong>result.push(value);</strong>
            seen = computed;
          } else if (iteratee) {
            if (!_.contains(seen, computed)) {
              seen.push(computed);
              <strong>result.push(value);</strong>
            }   
          } else if (!_.contains(result, value)) {
            <strong>result.push(value);</strong>
          }   
        }   
        return result;
      };  
  </code>
</pre>

<a href='http://underscorejs.org/#uniq'>From the site:</a>

<em><strong> If you want to compute unique items based on a transformation, pass an iteratee function.</strong></em>

**Comment by jdalton** [comment]
It is based on the transformation the transformation is not returned in the result.

**Comment by sndsgn** [comment]
Are you saying that you can assign the transformed values to a variable? The variable seems to return the original values. Is there an example that you are aware of as I have not found one where the iteratee returns values based on the transformation?
