### ISSUE TITLE
`_.isNaN` returns true for whatever created with `new Number()` instead of just `NaN` and `new Number(NaN)`

### ISSUE THREAD

**Issue by debutt** [jashkenas/underscore#2257]
// All => true
    _.isNaN(new Number(3))
    _.isNaN(new Number(Infinity))
    _.isNaN(new Number('donut'))

If `_.isNaN` is intended to return `true` for only `NaN` and `new Number(NaN)`, I think in line `1304`, `obj !== +obj` should be replaced with `obj != +obj`.

Correct me if I'm wrong : )

**Comment by michaelficarra** [comment]
I don't understand what you're trying to say.

**Comment by bjmiller** [comment]
I don't know if his proposed solution will work.  But, if `_.isNaN(new Number(3))` returns true, that's probably a bug.

**Comment by megawac** [comment]
Feel free to send a PR with the change to `obj != +obj`

**Comment by debutt** [comment]
If we change the code to `obj != +obj`, `_.isNaN` still returns true for things like `new Number('dice')`, but I guess that's effectively the same as `NaN` in operations : )

**Comment by debutt** [comment]
Since `!=` won't make it through the build, I suggest we can use the good old `isNaN` with `_.isNumber`, thus

    _.isNumber(obj) && isNaN(obj)

`_.isNumber` makes sure `obj` is a *number*, primitive or wrapped, and then `isNaN` makes sure only `NaN` and `new Number(NaN)` pass the test.
