### ISSUE TITLE
Tests missing from npm release tarballs

### ISSUE THREAD

**Issue by davexunit** [jashkenas/underscore#2258]
I noticed that the official release tarballs on the npm registry do not include the test suite files, which means that one cannot run `npm test` to independently verify that the released code passes the test suite on one's own computer.  I think it would be good to adjust `package.json` to specify that the tests should be included in the release tarball.  Thoughts?

Thanks!

**Comment by michaelficarra** [comment]
You can download the full releases from here: https://github.com/jashkenas/underscore/releases

npm is used to distribute only what is necessary to rely on underscore as a dependency of your own project.
