### ISSUE TITLE
In most cases, _.isFinite is defined twice

### ISSUE THREAD

**Issue by debutt** [jashkenas/underscore#2263]
Can't say that's very efficient.

**Comment by megawac** [comment]
Is finite is defined once, here https://github.com/jashkenas/underscore/blob/master/underscore.js#L1298

**Comment by debutt** [comment]
Sorry, I got distracted when I opened the issue, it's _.isFunction not _.isFinite.

**Comment by jdalton** [comment]
The second time `_.isFunction` is defined is for buggy enviros only else they get the simple form.

**Comment by debutt** [comment]
On the contrary, the second time it's defined is for the non-buggy environments—for environments other than Chrome 12-, Safari 8, and IE 11, in which `_.isFunction` can take advantage of the `typeof` operator for better performance. So in most cases, it is defined twice.

Correct me if I'm wrong : )

**Comment by jdalton** [comment]
> Correct me if I'm wrong : )

Oh well, same diff. Either way the cost is nill.

**Comment by debutt** [comment]
Alright, just thought that's something can be improved : )
