### ISSUE TITLE
[Discussion] Best practices for fetching deep value in an object

### ISSUE THREAD

**Issue by paramaggarwal** [jashkenas/underscore#2268]
What we know till now:
1. Using strings to manipulate keys in JS is bad practice. (ref: ["string programming"](https://github.com/jashkenas/underscore/search?q=%22string+programming%22&type=Issues&utf8=✓))
2. Both `underscore-contrib` and `lodash` implement `getPath` for this.
3. People are confused about this. (ref: #555, #712, #1137, #1169, #1659, #1822, #1889, #1998)

What are the best practices around safely fetching `object.child.child.child.child.name` with purely the use of `_` methods?

**Comment by jdalton** [comment]
Maybe
```js
var o = { 'a': { 'b': { 'c': 3 } } };
_.reduce(['a', 'b', 'c'], _.partial(_.result, _, _, void 0), o);
```

**Comment by rafde** [comment]
> 1. Using strings to manipulate keys in JS is bad practice. (ref: "string programming")
Why? It's convenient and smaller than `['object', 'child', 'child', 'child', 'child', 'name']` vs `object.child.child.child.child.name` which is more telling that the former.

**Comment by megawac** [comment]
@rafde because it becomes tricky to interpret some of the path nuance, edge cases

```js
var x = {"a['x.a.\y']": 1};

x["a['x.a.\y']"]
```

**Comment by jdalton** [comment]
I had Underscore's stance until user demand for it was overwhelming. Turns out edge cases are manageable and devs dig the shorter syntax. Baking it into core means devs get it in `_.pluck`, `_.filter`, `_.result`, `_.invoke`, `_.has`, and many other methods which would be cumbersome or not-possible otherwise.

**Comment by rafde** [comment]
> var x = {"a['x.a.\y']": 1};

Fair statement. Although I have no idea why anyone would make a key name like that. But apparently it's possible so it's really a nice to have.

**Comment by jdalton** [comment]
@rafde Issues can be avoided by checking if a path like `'x.a.\y'` exists as a single prop before crawling.

**Comment by jashkenas** [comment]
I think it would be nice to continue to avoid string programming. That was actually one of the original motivations for releasing Underscore in the first place — kinda like Oliver Steele's Functional JavaScript (http://osteele.com/sources/javascript/functional/) ... but without all the string programming.

**Comment by jdalton** [comment]
You could spin it that its less string programming and more paths (less magic than say 'x*x').
There just isn't a good alternative for a lack of this feature. With CS you could do
```js
_.map(a, o -> o?.a?.b?.c?);
```
But that's still more typing than
```js
_.map(a, 'a.b.c');
```
And then CS won't do for:
```js
_.has(o, 'a.b.c');
_.invoke(col, 'a.b.c');
_.result(o, 'a.b.c');
_.property('a.b.c');
```

**Comment by jdalton** [comment]
A recent tweet  for this feature took off on twitter:
<a href="https://twitter.com/wesbos/status/633301405445427200"><img width="584" alt="tweet image" src="https://cloud.githubusercontent.com/assets/4303/9368951/306ec962-467b-11e5-937d-0d593f3b79d4.png"></a>
