### ISSUE TITLE
Possible makeObjectsPerformSelector port

### ISSUE THREAD

**Issue by briantracy** [jashkenas/underscore#2274]
Objective-C's `NSArray` class had a great method called `-makeObjectsPerformSelector:` that would force each object in an array to to call a given method. I would love to see this functionality in JS and think that underscore is a great place for it. The signature could look something like `function (array, fn, argumentsToFn...)`. Would anyone else like to see this?

**Comment by jridgewell** [comment]
This is already possible with `_.invoke`, though it's not been documented.

```js
function something(a, b) { return a + b; };
var result = _.invoke(colleciton, something, 1, 2);
```

Want to submit a PR for documentation?
