### ISSUE TITLE
_.extend and _.default both miss keys in the "leaf" nested objects

### ISSUE THREAD

**Issue by wvxvw** [jashkenas/underscore#2282]
This may be related to #1574 (I'm not exactly sure what the OP had in mind).

Below are examples of current (incorrect) behavior:

``` javascript
_.extend({ x: { y: { z: 1 } } }, { x: { y: { q: 2 } } });
{ x: { y: { q: 2 } } }
```

``` javascript
_.defaults({ x: { y: { z: 1 } } }, { x: { y: { q: 2 } } });
{ x: { y: { z: 1 } } }
```

`$.extend()` also does it wrong (just for the reference, obviously I don't mean you need to fix it :) )

``` javascript
$.extend({ x: { y: { z: 1 } } }, { x: { y: { q: 2 } } });
{ x: { y: { q: 2 } } }
```
----
What I expect to happen:

``` javascript
_.extend({ x: { y: { z: 1 } } }, { x: { y: { q: 2 } } });
{ x: { y: { q: 2, z: 1 } } }
```
----
After some research I discovered there's also a proper version of this function in JQuery:

``` javascript
$.extend(true, { x: { y: { z: 1 } } }, { x: { y: q 2 } } });
{ x: { y: { q: 2, z: 1 } } }
```
Now I wonder why other options are needed.

**Comment by akre54** [comment]
Do a search for [`_.extend deep`](https://github.com/jashkenas/underscore/search?q=extend+deep&type=Issues&utf8=%E2%9C%93).

**Comment by jdalton** [comment]
@wvxvw See [lodash.merge](https://www.npmjs.com/package/lodash.merge) or via [require('lodash/object/merge')](https://github.com/lodash/lodash/tree/3.10.1-npm/object).

**Comment by wvxvw** [comment]
@jdalton I realize that the way I put it, it's a little vague. But my point is that "shallow" `extend` is really not all that useful / I cannot imagine when would you need this kind of behavior (as opposed to "deep").

@akre54 the original Underscore design doesn't generalize well. So, if I can offer my opinion, this is a much better design: http://clhs.lisp.se/Body/f_merge.htm which extends this to sequences, where merging hash-tables would be only a particular case. This also explains why it didn't occur to me to search for an "improved" version - I take it as a given that a utility function needs to be more generic than what it currently is, so I didn't think about looking for a more special kind of it.

**Comment by akre54** [comment]
@jdalton tacky.

@wvxvw for all the reasons mentioned in #162 and others. Think about *why* you want to deep extend. Chances are you can do it better by hand.

**Comment by jdalton** [comment]
@akre54 Naw. `_.merge` will happen as part of [Underdash](https://github.com/underdash/underdash) anyway. It's super handy.

**Comment by wvxvw** [comment]
@akre54 I don't really need to think why I need the functionality of `merge` / `extend`, because I know why I need it. And yes, in most cases I can write code slightly better than the Underscore's original code because it will fit my personal taste and requirements, but I really didn't file this ticket to tell you this :) Underscore is used almost ubiquitously in JavaScript world and having better utility functions in it is in my best interest. For the same reason, I'd like to avoid importing say, both Lodash and other clones (if there are any) - I'd like to have one library that does it right, instead of trying to fix what one library does by using another library (with, potentially, same or even grater amount of problems).
