### ISSUE TITLE
Feature proposal: sortBy with order

### ISSUE THREAD

**Issue by mjeanroy** [jashkenas/underscore#2290]
Hi,

I would like to suggest a feature with the `sortBy` utility: define order with a simple convention:
- If first argument is a string and start with `-`, then sort is a descendant order.
- If first argument is a string and start with `+` or with anything else, then sort is an ascendant order.

For instance:

```javascript
var stooges = [{name: 'moe', age: 40}, {name: 'larry', age: 50}, {name: 'curly', age: 60}];
_.sortBy(stooges, 'name'); // equivalent to _.sortBy(stooges, '+name');
// => [{name: 'curly', age: 60}, {name: 'larry', age: 50}, {name: 'moe', age: 40}];

_.sortBy(stooges, '-name');
// => [{name: 'moe', age: 40}, {name: 'larry', age: 50}, {name: 'curly', age: 60}];
```
I can see two drawbacks:
- This is some kind of string programming: I agree this is something we should try to avoid.
- Anyone can define a key `-name` to any object: weird, but it is possible.

I think, it could be easier to use than chaining `sortBy` with a `reverse` operation.
Backbone collection could also benefit from this feature.

What do you think ?

**Comment by akre54** [comment]
The string name is just for the simplest cases. If you want anything more advanced -- like reverse ordering, say -- you should pass a sorter function. We start heading down a very slippery slope when we allow this kind of string programming.

**Comment by jdalton** [comment]
Something like [_.sortByOrder](https://lodash.com/docs#sortByOrder) avoids the `-name` thing but still allows sorting values in descending order. Under the hood `_.sortBy` ends up using a base function shared by both.

**Comment by akre54** [comment]
Let's not bloat the API. This is fine as a mixin.

**Comment by jdalton** [comment]
I found the demand for it had risen enough to include in core and because much of the internals is shared bloat isn't an issue.

**Comment by akre54** [comment]
What's your metric for inclusion? I've seen you cite "demand" with similar numbers that you've rejected due to "lack of demand". The difference appears to be your opinion. Which is fine, but let's not pretend there's any kind of quantitative reasoning going on here.

**Comment by jdalton** [comment]
Demand in lodash may be different than underscore. My default reaction to any feature request in lodash is to close it with a let's wait and see. Then as more and more requests come in, via issues, tweets, or :+1:s, I'll open it for PRs or implementation discussions.

**Comment by akre54** [comment]
Ok then can we drop the "demand" criteria? Five people +1'ing a bad feature doesn't balance out to one person writing a clear explanation (with real world examples) of a good feature.

**Comment by jdalton** [comment]
Demand is an important criteria to help weed out requests it's not the only criteria.

**Comment by mjeanroy** [comment]
Hi,

Thank you for your response.

> If you want anything more advanced -- like reverse ordering, say -- you should pass a sorter function

It's not possible to use a sorter function with `_.sortBy` (or I missed something).
You can use a sorter function with `Array.prototype.sort`, but `_.sortBy` is much more useful since it produce a stable sort whatever the browser for free (and this is probably the only reason I use underscore to sort an array).

But you're probably right, this is easy to add as a mixin.

> Something like `_.sortByOrder` avoids the `-name` thing but still allows sorting values in descending order. 

Thank you, I didn't know about this feature in lodash !
