### ISSUE TITLE
Support astral symbols in _.toArray

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2296]
```js
var string = 'I 💕 the 🍂';
Array.from(string);
// => [ "I", " ", "💕", " ", "t", "h", "e", " ", "🍂" ]

[...string]
// => [ "I", " ", "💕", " ", "t", "h", "e", " ", "🍂" ]

_.toArray(string);
// => [ "I", " ", "", "", " ", "t", "h", "e", " ", "", "" ]
```

**Comment by lucasfanning** [comment]
:+1:

**Comment by lucasfanning** [comment]
![image](https://cloud.githubusercontent.com/assets/5374165/9857050/b422ddde-5aee-11e5-9066-591b9c7f0828.png)

for me this works.

**Comment by jdalton** [comment]
@lucasfanning Yes an array to an array would work. That's not the issue.

**Comment by lucasfanning** [comment]
@jdalton , I'm sorry

**Comment by jdalton** [comment]
@lucasfanning no worries!

**Comment by akre54** [comment]
That's kind of cheating, `[...string]` and `Array.from(string)` [are equivalent](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=var%20string%20%3D%20'I%20%F0%9F%92%95%20the%20%F0%9F%8D%82'%3B%0A%5B...string%5D). 

Also, `_.toArray`, like most Underscore methods, isn't really meant to be used on strings. Might be better for Underscore.string.

**Comment by jdalton** [comment]
May want to change the language of the code comment for `_.toArray` as
```js
// Safely convert anything iterable into a real, live array.
```
as `iterable` has a meaning in ES6.

**Comment by michaelficarra** [comment]
Agreed with @jdalton, this needs to be fixed.
