### ISSUE TITLE
Create a feature to find all keys and replace the values

### ISSUE THREAD

**Issue by snowmac** [jashkenas/underscore#2300]
I want a function that takes a key as a string, a dataset and a function to apply to that value. 

Example: imagine you need to iterate through a set of data and add left padding to a customer number in a collection / array of objects or single object: 

var customers = [  {customerID:"wrongFormat"}  ];
var updateCustomerFormat = function(value) { return "0000" + value; };  
customers  = _.update("customerID", customers, updateCustomerFormat);

**Comment by dperrymorrow** [comment]
If I am understanding you correctly, you can already accomplish that with ```_.map``` 

```javascript
var customers = [
  {customerID:"wrongFormat"} 
];

var updateCustomerFormat = function(value) { 
  value.customerID += "0000"; 
  return value;
};

console.dir(_.map(customers, updateCustomerFormat));
```

http://jsbin.com/barixoloxe/edit?html,js,console,output

**Comment by jgonggrijp** [comment]
If you want to avoid copying the array you can also use `_.each`:

```js
_.each(customers, function(value) {
    value.customerID = '0000' + value.customerID;
});
```

I don't think this use case warrants a whole new function.
