### ISSUE TITLE
why array maxlength is Math(2, 53)?

### ISSUE THREAD

**Issue by janeluck** [jashkenas/underscore#2313]
1.8.3,line 144,
```js
var MAX_ARRAY_INDEX = Math.pow(2, 53) - 1;
```
I found the Maximum size of an Array in Javascript is **Math(2, 32)-1**, [Maximum size of an Array](http://stackoverflow.com/questions/6154989/maximum-size-of-an-array-in-javascript).
why?

**Comment by akre54** [comment]
Good question. `2^53 - 1` was [taken from the ES6 spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-tolength), but [in ES5 most array operations](https://es5.github.io/#x15.4) go through [`ToUint32`](https://es5.github.io/#x9.6) effectively limiting the max range.

Given that Underscore targets ES3, our options are to do a runtime test of your environment on initialization or clamp to a value acceptable for ES3/5. Both have drawbacks. Opinions? @jridgewell @megawac @braddunbar

**Comment by jridgewell** [comment]
I don't see why we should limit it: you can still create an array-like with indexes greater than 2^32. That the environment doesn't support true arrays with that index doesn't change that.

**Comment by jdalton** [comment]
The array-like check in [ToLength](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-tolength) uses [MAX_SAFE_INTEGER](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-number.max_safe_integer) as its value because it's not limited to arrays (it's array like objects too). Arrays still have a [max length](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-array-constructor) of `Math.pow(2,32)-1`

**Comment by akre54** [comment]
Okey doke. Good to know.

**Comment by akre54** [comment]
So we're saying that you could create an array-like object with a length and an index under 2^53, and we'd iterate on it, but over, and we wouldn't?

**Comment by jridgewell** [comment]
> but over, and we wouldn't?

Yup, because you can't safely add to any number > 2^53. It's not really the maximum array-like index, it's the maximum number.

```js
i = Math.pow(2, 53); // => 9007199254740992
i + 1; // => 9007199254740992 (same number)
i + 2; // => 9007199254740994

**Comment by akre54** [comment]
> Yup, because you can't safely add to any number > 2^53. 

You also can't with ES3 and 2^32, right? Or am I missing something.

**Comment by jdalton** [comment]
The max array length of arrays hasn't changed. So if you where to try to use `Array#map` with an array-like object whos length is more than `Math.pow(2,32)-1` then it would error when attempting to populate the array. However, other methods like `Array#forEach` would work when called as `Array.prototype.forEach.call(someLargeArrayLikeObject, fn)`.

**Comment by jdalton** [comment]
ES6 basically removed the cap for non-array array-like objects for methods that don't produce arrays (so `every`, `some`, `reduce`, `reduceRight`, `find`, `findIndex`, `indexOf`, `lastIndexOf`, etc.)

**Comment by jridgewell** [comment]
> You also can't with ES3 and 2^32, right? Or am I missing something.

Tested on IE6 VM:

```js
i = Math.pow(2, 53) - 2; // => 9007199254740990
i + 1; // => 9007199254740991
i + 2; // => 9007199254740992
```

**Comment by jdalton** [comment]
The 2^32 limit is for Uint32 and not related to the max safe integer.
