### ISSUE TITLE
_.has an array of keys

### ISSUE THREAD

**Issue by taxigy** [jashkenas/underscore#2315]
I suggest it would be handy, in particular for HTTP query parsing, for `_.has` to accept *an array of keys* as the second parameter, e.g.

```javascript
> _.has({a: 1, b: 2, c: 3}, ['a', 'b']);
true
> _.has({a: 1, b: 2, c: 3}, ['a', 'x']);
false
```

So it would check whether *all of the keys* are present in a given object.

**Comment by jridgewell** [comment]
`_.every(['a', 'b'], _.partial(_.has, {a: 1, b: 2, c: 3}))`. We generally leave composibility up to the end developer.
