### ISSUE TITLE
Is it possible to make "_" not global?

### ISSUE THREAD

**Issue by JulienBonnin-ABTasty** [jashkenas/underscore#2316]
Hi :)

My issue is that I developed a third-party tag (full vanilla JS) used by many of my customer's websites. Some of them already have a use for a global "_" variable (not always an alias for Underscore.js) and even when they use Underscore it's often not in noConflict mode (I can't ask them to modify their code for me).

I wanted to integrate Underscore to my tag for a nice refactoring (knowing my tag is wrapped in a closure of course). However, it seems the _ variable is in the window object when I load the library, and I fear it will override some of my customers variables. How can I restrict the Underscore library to my closure scope ?

**Comment by JulienBonnin-ABTasty** [comment]
Okay sorry...

I just discovered that Underscore kept the previous value of "_" and restored it if we use noConflict 

window['_'] = "my value";
// INSERTING UNDERSCORE LIBRARY
var __ = _.noConflict();

console.log(_); // return "my value"

**Comment by akre54** [comment]
Yup, even better: use a module loader and you avoid the whole sticky mess in the first place.
