### ISSUE TITLE
predicate based `matcher`

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2318]
This is more for discussion than anything but what are you alls thoughts on a version of `matcher` that accept predicates per prop.

``` js
var objects = [{ 'a': { 'b': 1 } }, { 'a': {} }];
_.reject(objects, _.conforms({ 'a': _.isEmpty });
// => [{ 'a': { 'b': 1 } }]
```

**Comment by jdalton** [comment]
Bikeshedding names here, maybe `_.asserts` or `_.asserter`.

**Comment by jdalton** [comment]
Got it! `_.conforms`.

**Comment by jgonggrijp** [comment]
Closing for lack of popular demand. This might be a nice addition to an extension library like Underscore-Contrib instead.
