### ISSUE TITLE
_.extend Nested objects

### ISSUE THREAD

**Issue by faeli** [jashkenas/underscore#2322]
##### code
```
var res = _.extend({name:'Rich',books:{name:'',count:{page:1},topic:{name:'history'}}},{age:10,books:{name:'0 or 1',topic:{count:4}}});
 
console.log(res);

```
##### result
<img width="230" alt="screen shot 2015-10-14 at 7 31 28 pm" src="https://cloud.githubusercontent.com/assets/2375057/10482358/35f63e0a-72aa-11e5-9c75-a9103ce7d58e.png">

**Comment by akre54** [comment]
https://github.com/jashkenas/underscore/search?q=deep+extend&type=Issues&utf8=%E2%9C%93
