### ISSUE TITLE
IsArrayLike should not use 'length' property

### ISSUE THREAD

**Issue by nvd-ai** [jashkenas/underscore#2324]
I am passing an object literal to _.each for iteration. The object literal has a 'length' property. I expect _.each to iterate over the object literal as an object and not as an array. But IsArrayLike() checks for a length property and incorrectly detects the object literal as an array. As a result, I get wrong iteration over the object literal. 

I am changing the 'length' property to 'len' to make sure that iteration is done correctly. But if you consider that a developer does not need to know internals of 'each' function, 'length' is a single case that causes incorrect behavior in 'each' function.

  var isArrayLike = function(collection) {
    var length = getLength(collection);
    return typeof length == 'number' && length >= 0 && length <= MAX_ARRAY_INDEX;
  };

 _.each = _.forEach = function(obj, iteratee, context) {
    iteratee = optimizeCb(iteratee, context);
    var i, length;
    if (isArrayLike(obj)) {
      for (i = 0, length = obj.length; i < length; i++) {
        iteratee(obj[i], i, obj);
      }
    } else {
      var keys = _.keys(obj);
      for (i = 0, length = keys.length; i < length; i++) {
        iteratee(obj[keys[i]], keys[i], obj);
      }
    }
    return obj;
  };

**Comment by jridgewell** [comment]
https://github.com/jashkenas/underscore/issues?utf8=%E2%9C%93&q=is%3Aclosed+each+length

**Comment by jdalton** [comment]
Still no `_.forOwn` and `_.forIn`?

**Comment by jridgewell** [comment]
> Still no _.forOwn or _.forIn?

Not yet...

**Comment by jdalton** [comment]
It's probably about time to reconsider adding them. Dlosing issues as duplicate with no direction or solution given to the user is kind of a negative. Underscore has taken a step the direction of `_.forOwn` and `_.forIn` with the addition of `_.allKeys`. It would also help complete the set of object-specific alternatives such as `_.pick` for `_.filter`, `_.omit` for `_.reject`, and `_.mapObject` for `_.map`.
