### ISSUE TITLE
Can we get `_.pluck` to convert ObjectId's to strings?  Otherwise it returns `undefined`

### ISSUE THREAD

**Issue by niftylettuce** [jashkenas/underscore#2330]

**Comment by jdalton** [comment]
Can you provide an example?

**Comment by niftylettuce** [comment]
For example, with Mongoose we get returned ObjectId's.

If I have an array such as:

```js
var randomArray = [
  { product: ObjectId("12312312312312312312312") },
  { product: ObjectId("12312312312312312312312") },
  { product: ObjectId("12312312312312312312312") }
];
```

Then if I call:

```js
_.pluck(randomArray, 'product');
```

The output is:

```js
[ undefined, undefined, undefined ]
```

There's not really a one-liner to transform property types either, e.g.
convert toString() on all product properties

On Tue, Oct 27, 2015 at 8:14 PM, John-David Dalton <notifications@github.com

**Comment by niftylettuce** [comment]
Note that if I call `_.pluck(randomArray.toObject(), 'product')` it works fine - but the comparison here <https://github.com/jashkenas/underscore/blob/master/underscore.js#L136-L140> just returns `undefined` instead of the original property.

**Comment by niftylettuce** [comment]
Nevermind, this isn't an issue.  My query was wrong.  I was trying to call `_.pluck` on an Array of Arrays.  I had to call `_.flatten` as such:

```js
_.pluck(_.flatten(_.pluck(orders, 'items')), 'product'));
```

Oops.
