### ISSUE TITLE
IE8 and func.apply

### ISSUE THREAD

**Issue by kachkaev** [jashkenas/underscore#2332]
I've spotted a pretty hard-to-localise bug in IE8, it is about the internal use of func.apply() in underscore. Here is ```_.throttle``` as an example:

```js
  _.throttle = function(func, wait, options) {
    var context, args, result;
    var timeout = null;
    var previous = 0;
    if (!options) options = {};
    var later = function() {
      previous = options.leading === false ? 0 : _.now();
      timeout = null;
      result = func.apply(context, args);    // <---------------------------------------- case 1
      if (!timeout) context = args = null;
    };
    return function() {
      var now = _.now();
      if (!previous && options.leading === false) previous = now;
      var remaining = wait - (now - previous);
      context = this;
      args = arguments;
      if (remaining <= 0 || remaining > wait) {
        if (timeout) {
          clearTimeout(timeout);
          timeout = null;
        }
        previous = now;
        result = func.apply(context, args);  // <---------------------------------------- case 2
        if (!timeout) context = args = null;
      } else if (!timeout && options.trailing !== false) {
        timeout = setTimeout(later, remaining);
      }
      return result;
    };
  };
```

It may turn out that ```args``` will be null in ```case 1```, which leads to an exception. This is because ```func.apply()``` must be either called with one argument or with an array as a second argument. Unfortunately, IE8 does not know what to do with ```null``` (see [MSDN](https://msdn.microsoft.com/en-us/library/4zc42wh1%28v=vs.94%29.aspx)). The message says ```object expected```.

This workaround fixed the issue for me:
```js
result = func.apply(context, args || []);
```
Setting ```args``` to ```undefined``` (not ```null```) does not seem to do the job. I guess similar issues may be hidden elsewhere in the code.

**Comment by megawac** [comment]
Do you have a reproducible case for this bug?

**Comment by kachkaev** [comment]
Sorry, I don't have a standalone one – the code I was debugging was a part of an app. Any case when this line has been called should reproduce it (there are two occurrences):
```js
if (!timeout) context = args = null;
``

**Comment by kachkaev** [comment]
Maybe the safest solution will be replacing any ```func.apply(context, args)``` with ```func.apply(context, args || []);```, but that will eat a bit more memory. Another option is smth like this:

```js
var safeFuncApply = function(func, context, args) {
    if (args) {
        return func.apply(context, args);
    } else {
        return func.apply(context);
    }
};
// ...
// in _.throttle
result = safeFuncApply(func, context, args);
```

But that's an extra function call.

**Comment by megawac** [comment]
Looking at the source, it shouldn't be possible for args=null as args=arguments. In the later function it may be possible for args=null to occur. I'll see if I can repro

**Comment by megawac** [comment]
@kachkaev I can't identify any cases which will trigger this issue, both through debugging cases for `args == null` and going over the code. After reviewing the implemetation of throttle, I can't see anyway for func to be applied with null args.

If you have a repro case I'd be very interested in going over it

**Comment by kachkaev** [comment]
My guess is that some peculiarity of handling JS threads in IE8 may cause a call of ```later()``` after ```if (!timeout) context = args = null```. Not sure how exactly this may occur, just remember that the calls of a throttled function were very frequent when the exception was observed. After I replaced ```// case 1``` with ```result = func.apply(context, args || [])```, the bug disappeared.

Use of IE8 is quite rare now, but if someone else comes across the same issue, they'll know where to leave a comment :–)

**Comment by megawac** [comment]
Do you know which version you were using? Could of been a bug with an older
version

**Comment by kachkaev** [comment]
That was IE8 on Win XP, which I recently downloaded from modern.ie as a VirtualBox VM.

**Comment by megawac** [comment]
Sorry, I mean version of underscore. Was it latest?

**Comment by kachkaev** [comment]
1.8.3
