### ISSUE TITLE
value_ only returns a reference to an Object instead of Extracting its value

### ISSUE THREAD

**Issue by idrissou** [jashkenas/underscore#2336]
The following line varA=_(varB).value() is only a new reference to varB.
When I change something in varB or vice versa, it does change as well in varA. This leads me to say that value does not extract the value of an object as the one expects. 

It acts exactly the same as the following expression condensedData=tempArray.

**Comment by michaelficarra** [comment]
Yeah, this is the intended behavior. Underscore does not do a deep copy of objects you give to it. That would be both prohibitively expensive and unexpected for most users.

**Comment by idrissou** [comment]
Thanks for the swift reply. Yeah the name is a bit misleading. I have a question if you don't mind: what is the point of this function then if it acts exactly as an assignment? some thing like varA=varB.

**Comment by michaelficarra** [comment]
@idrissou The underscore function wraps the given value in an object to give you the ability to call underscore functions on the object as if they were methods of the given value. After the operations have been performed, the resulting value may be extracted from this object. If no operations are performed, there's no reason the extracted value must not be the input value.

**Comment by idrissou** [comment]
Ah okey. Makes sense. Thanks
