### ISSUE TITLE
Release newest version to npm

### ISSUE THREAD

**Issue by m90** [jashkenas/underscore#2343]
The last time underscore was published to npm seems to be a long time ago (i.e. April 2015).

I just ran into trouble when browserifying/babelifying an application because of this: https://github.com/jashkenas/underscore/commit/7fc15e5816dc02371517c4cb16a28e35f5b9a857

1.8.3 would tell me that `root` is undefined in the bundled file and throw at accessing `root._`. When I pull from the github repo the build will be ok.

Could we get all this fine stuff here: https://github.com/jashkenas/underscore/compare/1.8.3...master released to npm?

**Comment by jridgewell** [comment]
Ping @braddunbar, do you have npm access to Underscore?

**Comment by jdalton** [comment]
To check see [here](https://www.npmjs.com/package/underscore/access).

**Comment by jdalton** [comment]
A newer release won't likely be out for weeks or months depending on Jeremy's travel plans. You can however reference your npm dep to a commit hash. We'll [track tasks](https://github.com/jashkenas/underscore/issues/1841) for release in a dedicate issue.
```json
"underscore": "jashkenas/underscore#616b1f8"
```
