### ISSUE TITLE
enhance `isArray` to enforce an element type

### ISSUE THREAD

**Issue by eliOcs** [jashkenas/underscore#2344]
Thought it would be useful if you could check if a variable is an Array and at the same time check if its elements are of a certain type:

    _.isArray(["a", "b", "c"], String)
    true

    _.isArray(["a", "b", 3], String)
    false

**Comment by jridgewell** [comment]
I'm not sure that align with the name "isArray". Instead:

```js
_.isArray(arr) && _.every(arr, _.isString)
```

**Comment by eliOcs** [comment]
:+1: It may be useful to include that example in the `isArray` documentation section
