### ISSUE TITLE
Shouldn't add new parameter in global scope

### ISSUE THREAD

**Issue by ssehacker** [jashkenas/underscore#2346]
for (i = 0, length = obj.length; i < length; i++) {
        iteratee(obj[i], i, obj);
      }

we will find variable "length"  used in for expression, and it's in global scope,but didn't be deleted at last.

**Comment by jridgewell** [comment]
This is from `_.each`? `length` and `i` are defined on [Line 161](https://github.com/jashkenas/underscore/blob/e7221cb/underscore.js#L161)

**Comment by ssehacker** [comment]
But you can find it in min(line 313), max(line 338) function as well, it's not defined in this functions.

**Comment by michaelficarra** [comment]
@ssehacker That's not true.

**Comment by ssehacker** [comment]
@michaelficarra not true? what do you mean?  https://github.com/jashkenas/underscore/blob/e7221cb/underscore.js#L313 And you will get a global variable named "length", just try it on console of.browser.

**Comment by jdalton** [comment]
Naw @ssehacker, it's not. The line you pointed to:
> for (var i = 0, length = obj.length; i < length; i++) {

Has `var i = 0, length - obj.length` which is the local declaration and not global.

**Comment by jdalton** [comment]
I believe tests are now running with guards to detect accidentally leaked globals so if this was an issue it would have been caught.

**Comment by ssehacker** [comment]
@jdalton  ops, sorry , it's my mistake. I took semicolon as comma.
