### ISSUE TITLE
about _.isObject change

### ISSUE THREAD

**Issue by awesomes-cn** [jashkenas/underscore#2350]
In 1.1.7 version 
```
_.isObject = function(obj) {
    return obj === Object(obj);
  };
```

In  1.7.0+ version
```
_.isObject = function(obj) {
    var type = typeof obj;
    return type === 'function' || type === 'object' && !!obj;
};
```
I find the two way to realize isObject  is the same,why make this change?

**Comment by jdalton** [comment]
There [was a V8 JIT bug](https://code.google.com/p/v8/issues/detail?id=2291) with `obj === Object(obj)` but that didn't [motivate](https://github.com/jashkenas/underscore/issues/605) them [to change](https://github.com/jashkenas/backbone/issues/1543). It was a [micro-opt](https://github.com/jashkenas/underscore/commit/fa1427d709e4d005c8de9d3a7e5734e304ac6d0f) that did it.
