### ISSUE TITLE
maintenance mode

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2362]
I've read a couple time that Underscore is "mostly done". I'm wondering if we should document that in the readme or site. This would give a clear signal to those opening issues and also allow us to clean up many of the older/stale issues and PRs as `wontfix`. This would also focus future contributions on things like unit test cleanup and general maintenance, instead of new features or expanding.

Thoughts? \@megawac, @jridgewell

**Comment by jdalton** [comment]
Thoughts?

**Comment by jdalton** [comment]
\@megawac, @jridgewell

**Comment by jdalton** [comment]
:party:

**Comment by jdalton** [comment]
I'll take that as a "no not yet". I talked with @megawac off thread and the gist was that Underscore isn't ready for maintenance mode just yet.

**Comment by akre54** [comment]
Stop trolling.

**Comment by jdalton** [comment]
Naw, not trolling. Clarifying the state of the lib is a good thing.

**Comment by akre54** [comment]
"Please use the mailing list for questions and discussion. Github issues are for bugs and features suggestions only." You know better.

**Comment by jdalton** [comment]
There's an Underscore mailing list? We should document it on the site.
