### ISSUE TITLE
_.flatten errors on arrays with circular references.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2363]
```js
var arr = [1, 2, 3];
arr.push(arr);

_.flatten(arr);
// => Uncaught RangeError: Maximum call stack size exceeded(…)flatten
```

Result could be:
```js
[1, 2, 3, 1, 2, 3]
```

**Comment by michaelficarra** [comment]
Certainly not. This should fail in exactly the way it does.

**Comment by jdalton** [comment]
Other Underscore methods have guards for things like circular references.

**Comment by megawac** [comment]
I agree with @michaelficarra this should result in an infinite array and thus an error.

Currently lodash (master) produces `[1, 2, 3, 1, 2, 3, [1, 2, 3]]` which is clearly an incorrect result

**Comment by jdalton** [comment]
Folks, Lodash `_.flatten` is shallow by default.
