### ISSUE TITLE
_.template: allow undefined keys

### ISSUE THREAD

**Issue by mren** [jashkenas/underscore#237]
When the template function needs an element that is not defined it returns an Error.
It would be great if the template function would act equivalent as if the value of the element is undefined

```
_.template('<%= foo %>', {foo: undefined});
```

returns "", but

```
_.template('<%= foo %>', {});
```

returns a ReferenceError

The reason I'm requesting this is, that I usually use underscore to template my views. But sometimes the attributes of the model are not yet available.
In this case the application returns an error, it would be better if the template function would be more lax.

**Comment by djkmiles** [comment]
Avoided by using `_.templateSettings.variable = "rc";` then prefixing with that chosen variable prefix of `rc`.

**Comment by A-Tran** [comment]
@nikmartin You don't actually have to write it as nested ifs, you can use the && statement! 
``` if (data.bar && data.bar.bat) { 
   ... do something
}``` 
which I think is completely reasonable, given that the use case for this would be, if data contains the bar element (meaning bar may or may not be there), as would be the case with bat. And if your application suggests that maybe, `bat` is in every `bar`, and we are looking for a `foo` which might be in a `bat`, then its also safe to say
``` if (data.bar && data.bar.bat.foo) {
    ... do something
}```
Which will only give you an undefined reference error if there is a case where `bar` exists and `bat` doesn't exist.

And if you're used to other high-level programming languages where you can just say 
```if (data.bar.bat.foo) ``` and have that cover every case, and well, I'm no expert, but to check if foo is a property of bat I imagine you would need to have to be able to locate bat somewhere in memory, meaning that  the same sequential checking that you think is  'horrible' is required, whether it happens in the background or in your code. (? Not too certain about my statement in this last paragraph but fairly confident, would love to be corrected if I'm wrong)

**Comment by andrewpurkett** [comment]
Why doesn't _.undefined() even work within templates? This is absurd

**Comment by jdalton** [comment]
@andrewpurkett 
There's a nice JS 101 post on undeclared variable access [over on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Evaluating_variables) and bit on [with-statements and reference errors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with#Description).

**Comment by paztis** [comment]
It's an old subject, but you always can access all variables with arguments[0]

<%= arguments[0].foo %> works if foo is undefined

**Comment by naholyr** [comment]
![image](https://user-images.githubusercontent.com/214067/37777582-339ed206-2de8-11e8-8b8b-acaa68c49292.png)

```js
_.template('<%= obj.undef %>')({}) // empty string
```

Minifiers should not break that as it's a static string, but can we reasonably rely on that? It's arguaby more elegant than `arguments[0]`.

**Comment by velikayikci** [comment]
let value 'Hello <% obj.foo.bar %>';
try {
                    _.template(value, {  });
                } catch (e) {
                    if ((e.message as string).includes('Cannot read properties of undefined')) {
                        value = value.replace(/<%.*%>/, ''); // remove beetween <% %>
                }
                
               // value = Hello

**Comment by paztis** [comment]
This is on when you've only one variable in your template

**Comment by jgonggrijp** [comment]
@velikayikci 

> ```js
>     _.template(value, {  });
> ```

Please note that this only compiles the template. It doesn't render it. Unless you're using a very old version of Underscore.

To anyone still running into issues like these, two words of advice.

Firstly, [explicitly setting the `variable` when compiling the template](https://underscorejs.org/#template) will let you access arbitrary unset properties on the root data object unpunished and also give you better performance.

```js
var withoutVariable = _.template('<%= foo %>');
withoutVariable({ foo: 1 }); // renders '1'
withoutVariable({ bar: 1 }); // error

var withVariable = _.template('<%= root.foo %>', { variable: 'root' });
withVariable({ foo: 1 }); // renders '1'
withVariable({ bar: 1 }); // fine, renders 'undefined'
```

I like naming this variable `root`. Another common choice is `data`. I also liked a suggestion earlier in this issue thread to use `o`.

Secondly, Underscore nowadays has [`has`](https://underscorejs.org/#has) and [`get`](https://underscorejs.org/#get). Using these in your templates will let you access arbitrarily nested properties in the data, no nested `if` statements required.

```js
var templateText = `
<%= _.get(root, ['foo', 'bar', 'baz'], 'oops') %>
Two-syllable properties <% 
if (_.has(root, ['foobar', 'barbaz'])) { 
    %>present<%
} else {
    %>absent<%
} %>
`;

var compiledTemplate = _.template(templateText, { variable: 'root' });

compiledTemplate({
    foo: {
        bar: {
            baz: 'hello',
        },
    },
    foobar: {
        barbaz: null,
    },
});
// renders 'hello\nTwo-syllable properties present'

compiledTemplate({});
// renders 'oops\nTwo-syllable properties absent'
```
