### ISSUE TITLE
Adding ability for deep object property lookup (_.get)

### ISSUE THREAD

**Issue by patrickml** [jashkenas/underscore#2370]
This is simular to that of lodash and i believe there is a big use for this functionality to be added to the core. One of the biggest benefits of this is that you no longer have to check for undefined up the object chain like so

Before `this.object && this.object.one && this.object.one.two`
Now `_.get(this.object, 'one.two')`

I found most of this on another post I cannot remember who did it but this is very useful

```js
_.mixin({
  get: function (obj, key) {
      var type = typeof key;

    if (type == 'string' || type == "number") {
      key = ("" + key).replace(/\[(.*?)\]/,/\[(.*?)\]/, function (m, key) { //handle case where [1] may occur
        return '.' + key.replace(/["']/g,/["']/g, ""); //strip quotes
      }).split('.');
    }
    for (var i = 0, l = key.length; i < l; i++) {
      if (typeof obj !== 'undefined' && _.has(obj, key[i])) obj = obj[key[i]];
      else return undefined;
    }
    return obj;
  }
});
```

**Comment by akre54** [comment]
This has been proposed and rejected a few times (search for "string programming" or "deep path" and you'll find #2268, #1169, #1266 and others). Also check out underscore-contrib.

**Comment by NarHakobyan** [comment]
use underscore.get module

`const {get} = require('underscore.get');`
