### ISSUE TITLE
A build issue with npm & browserify

### ISSUE THREAD

**Issue by linwenjun** [jashkenas/underscore#2371]
I use npm install the underscore and browserify + react to build my application
but once I require the underscore, the source map can't work,unless i comment this line
https://github.com/jashkenas/underscore/blob/master/underscore.js#L1503
source += text.slice(index, offset).replace(escaper, escapeChar);

and this is my gulp task scripts

gulp.task('browserify', function(done) {
  glob('src/app.js', function(err, files) {
    if(err) done(err);

    var tasks = files.map(function(entry) {
      return browserify({
          entries: [entry],
          debug: true
        })
        .transform('babelify', {presets: ['es2015', 'react']})
        .bundle()
        .pipe(source(entry))
        .pipe(buffer())
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(uglify())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./dist'));
    })
    es.merge(tasks).on('end', done);
  })
})

**Comment by captbaritone** [comment]
What happens if you try to create a build that is just underscore using your setup? Does the source-map for that work?

**Comment by akre54** [comment]
This looks like it's a bug in your bundler. We're not doing anything particularly nonstandard here.
