### ISSUE TITLE
non-string programming form of _.get

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2372]
I figured I'd float this by.

One of the reasons cited for not adding deep property getter and setter methods is wanting to avoid string programming.

Ruby has added [Array#dig](http://ruby-doc.org/core-2.3.0_preview1/Array.html#method-i-dig) and [Hash#dig](http://ruby-doc.org/core-2.3.0_preview1/Hash.html#method-i-dig) (thanks @braddunbar for the heads up).

Underscore could take a note from Ruby (as it's done with other methods) and have `_.get` and `_.set` methods which accept an array of properties to walk. No string magic needed. The use of an array, instead of individual arguments like Ruby's `Hash#dig`, allows for adding a `defaultValue` param after too.

```js
var object = {};
_.get(object, ['a', 'b', 'c'], 'defaultValue');
_.set(object, ['a', 'b', 'c'], 'newValue');
```

This deep property getter/setter support can also easily make its way into `_.pluck`, `_.result`, and other methods that access properties in the future if so desired too.

Related to:
#2370, #2268, #1169, #1266

**Comment by akre54** [comment]
I can dig. Sort of like Immutable's [`getIn`](https://facebook.github.io/immutable-js/docs/#/Iterable/getIn) / `keyPath` methods.

Are we already overloading these APIs too much though?

**Comment by jdalton** [comment]
The `_.get` and `_.set` methods don't exist in Underscore at the moment. The `_.result` method could be expanded to accept an array as the `property` param and others can be addressed on a case by case.

**Comment by jridgewell** [comment]
I'd love to see these in the collection functions.

> Are we already overloading these APIs too much though?

I don't think so. I see this as translating primitives into the correct function for collection functions, with a few special cases for `_.result` and friends.
