### ISSUE TITLE
Checkmarx Issue - Divide by Zero

### ISSUE THREAD

**Issue by callmekatootie** [jashkenas/underscore#2378]
Hello,

We are using underscorejs in our application and we ran Checkmarx against it. It returned a security issue with the minified script:

|#|Issue|Code in question|
|---|---|---|---|---|
|1|Divide by zero|var e, u, i = 1 / 0,|
|2|Divide by zero|o = 1 / 0;|
|3|Divide by zero|(o > u || 1 / 0 === u && 1 / 0 === i) && (i = n, o = u)|
|4|Divide by zero|var e, u, i = -1 / 0,|
|5|Divide by zero|o = -1 / 0|
|6|Divide by zero|(u > o || u === -1 / 0 && i === -1 / 0) && (i = n, o = u)|
|7|Divide by zero|return x(n, t, 1 / 0)|

Note that this is in the minified version - the actual source code makes use of Infinity instead of dividing by zero.

We just wish to check if this is a valid issue or a false positive.

**Comment by jridgewell** [comment]
This isn't an issue in JS because it gives `Infinity` (or `-Infinity` for `-1 / 0`) and doesn't throw an error.

**Comment by callmekatootie** [comment]
Thank you for your quick response.
