### ISSUE TITLE
_.isEqual optimization: compare array length ASAP

### ISSUE THREAD

**Issue by vendethiel** [jashkenas/underscore#2400]
`_.isEqual`'s helper function [checks the length of the arrays it's comparing](https://github.com/jashkenas/underscore/blob/a8c29420dc9e5decbbea2dff7e50527af70c8c03/underscore.js#L1234) when it's figured out it's comparing two arrays together.

This step, however, happens after [aStack/bStack has been initialized (and aStack has been filled)](https://github.com/jashkenas/underscore/blob/a8c29420dc9e5decbbea2dff7e50527af70c8c03/underscore.js#L1218-L1229).

Is there a specific reason it's this way, or would a PR (..that doesn't break the tests) changing it be welcome?

**Comment by michaelficarra** [comment]
Sure, that sounds good.

**Comment by akre54** [comment]
Closed for #2406
