### ISSUE TITLE
_.unescape() doesn't handle numeric HTML entities.

### ISSUE THREAD

**Issue by barbastan** [jashkenas/underscore#2401]
E.g., `_.unescape` should convert `&#39;` to an apostrophe.  
lodash handles these.

**Comment by jdalton** [comment]
Hi @barbastan! 

It's just a difference in implementation. Underscore escapes single quotes to `&#x27;` and so unescapes that instead.

**Comment by barbastan** [comment]
Hi!  The problem is that there are web pages out there that use &#39, so I
am unable to unescape those pages using underscore. I would argue that it
should convert both &#x27 and &#39.

Barbara

On Wed, Dec 30, 2015 at 9:28 PM, John-David Dalton <notifications@github.com

**Comment by megawac** [comment]
Hi, it looks like you're looking for a robust htnl entity decoder. I'd suggest taking a look at https://github.com/mathiasbynens/he as this is kind of beyond the scope of underscore

**Comment by barbastan** [comment]
Thanks!  I'll look into https://github.com/mathiasbynens/he later today.
Also, I can use lodash; it supports what I need.

Thanks again.

Barbara
