### ISSUE TITLE
_.each not working properly when an object have property length

### ISSUE THREAD

**Issue by juneidysoo** [jashkenas/underscore#2407]
Apparently the _.each checks if one object is an array by checking length property. This problem occurs when I have an object in this structure:
```javascript
var obj = {
   length: 0,
   /* Other properties */
}
```

**Comment by jdalton** [comment]
Hi @juneidysoo!

The `_.each` method is a Collection method which means it works on array-like objects and objects. It prioritizes array-like objects over objects.

**Comment by juneidysoo** [comment]
If so, then how can I iterate an object that has properties length with underscore?

**Comment by jridgewell** [comment]
We don't have a way in underscore. lodash has `_.forIn` for this case.

**Comment by juneidysoo** [comment]
Thank you so much! The support response is super fast! Keep up the great work :D
