### ISSUE TITLE
_.delay,why "this" been set to null? 

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2408]
```javascript
_.delay = function(func, wait) {
    var args = slice.call(arguments, 2);
    return setTimeout(function(){
      return func.apply(null, args);   //how about func(args);
    }, wait);
};
```

if the argument "func" have been bound something to it as "this" object,should we change it to null here?
if your ansar is yes,why not change this sentence ```return func.apply(null, args);``` simply to  ```func(args);``` here?

**Comment by Pavnii** [comment]
No,I don't think null is used for  the "func"  being bound to "this" object.That is, "this" is an extra, often implicit parameter.The value of "this" depends on mode it is used.

Sloppy mode: this refers to the global object (window in browsers).
    function sloppyFunc() {
        console.log(this === window); // true
    }
    sloppyFunc();
	
Strict mode: this has the value undefined.
    function strictFunc() {
        'use strict';
        console.log(this === undefined); // true
    }
    strictFunc();

And it's not possible to skip arguments this way. You can omit passing arguments only if they are trailing parameters.

**Comment by Pavnii** [comment]
Yes,I think it is changed to null in that place because "func" is bound to "this" object .As syntax of apply() method is : fun.apply(thisArg, [argsArray]).Unlike in usual function call where "this" is an extra and implicit parameter,to make function call via apply() or call() you have to explicitly specify the value of "this".Otherwise parameter you pass will be assigned to "this".

function myFunc(arg1) {       
        console.log(this); //b
        console.log(arg1); //undefined
    }
    myFunc.apply(['b']);

In general it's not possible to skip arguments this way. You can omit passing arguments only if they are at the end of the parameter list.

**Comment by michaelficarra** [comment]
The `this` value of bound functions will not be changed by `apply`. Next time please include an example with the behaviour you expect and the behavior you are currently observing. This will make it easier to understand what is being requested.

**Comment by jridgewell** [comment]
@michaelficarra: I think he's asking why we don't apply with the outer function's `this`?

```js
  _.delay = restArgs(function(func, wait, args) {
    var _this = this;
    return setTimeout(function() {
      return func.apply(_this, args);
    }, wait);
  });
```

**Comment by Pavnii** [comment]
Sorry for the confusion !!He is just asking what is the necessity of making a function call via apply?
Why just we call function ````func(args)````  as  ```this```  arguement is ````null```` anyway.Well  that is my question too!!

**Comment by jridgewell** [comment]
Because it can have multiple `args`:

```js
function add(a, b, c) {
  return a + b + c;
}

// Calls `add` with (1, 2, 3) after 10
_.delay(add, 10, 1, 2, 3);
