### ISSUE TITLE
whereIn

### ISSUE THREAD

**Issue by fsebbah** [jashkenas/underscore#2411]
Hi,
I search a possibilitie to extract values with an array from on criteria.
Sample :
_.whereIn (list,{criteria:[x,y,z]})
Thanks for your help,
Franck

**Comment by jridgewell** [comment]
You're probably looking for [`_.filter`](http://underscorejs.org/#filter).

**Comment by fsebbah** [comment]
Tks for your reply,
I tried with filter
var s = _.filter(listId,
	function(alias){
	var x=_.where(listWorkers,{companies:alias});
		return x;
	});
In return, s = alias and not x ???

**Comment by captbaritone** [comment]
@fsebbah I'd be happy to help you, but I'm having trouble understanding your goal. Could you provide an example in the following format:

1. An example input.
2. An example argument.
3. The output you would expect from the function.

I'm guessing the result will be some combination of `_.filter` and `_.contains`, but if you supply these three items, I can probably give you an actual example.
