### ISSUE TITLE
please tell me what's the purpose of this sentence

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2413]
sorry but I wonder why this sentence exist in the method _.throttle
```if (!timeout) context = args = null;```
what's the purpose?

**Comment by jridgewell** [comment]
To allow `context` and `args` to be garbage collected, but only if the invocation above it didn't call the throttled function.

**Comment by akre54** [comment]
Github repos aren't your personal question and answer service. Please use StackOverflow, the Gitter channel or the mailing list.
