### ISSUE TITLE
_.isElement should add a property existing detect

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2416]
```javascript
  _.isElement = function(obj) {
    return !!(obj && obj.nodeType === 1);
  };
```
is it necessary to add ```!!``` before ```obj && obj.nodeType === 1```?
and to avoid an exception been thrown,we should add a detection for the property "nodeType" first.
```javascript
  _.isElement = function(obj) {
    return (obj && "nodeType" in obj && obj.nodeType === 1);
  };
```

**Comment by jridgewell** [comment]
It's to coerce a Boolean return value. Imagine if `obj` was `null`.

No need for the `in` check, though.
