### ISSUE TITLE
Offer _.zipWith(arrays, iteratee)

### ISSUE THREAD

**Issue by mcandre** [jashkenas/underscore#2423]
`zipWith` is a common extension of `zip` in functional programming languages. It applies a given function `iteratee` over each tuple constructed by zipping the arrays.

Sure, this is a convenience function, but a very convenient one for FPL-ers!

**Comment by curtiscali** [comment]
Hey @mcandre I'm willing to try an take a crack at this to help contribute. I'd like to clarify what exactly you'd like to use `iteratee` for though. For example: do you want it to return a value like for `map` or just be a general function like `each` that doesn't necessarily have a return value? Better yet could you give an example code snippet of the type of usage you had in mind?

**Comment by jgonggrijp** [comment]
This wouldn't add any expressive power to Underscore. You can just do `_.chain(arrays).unzip().map(iteratee).value()`. You can also wrap that expression in a new function, call it `zipWith` and add it to the Underscore object with `_.mixin`. You can then even chain it.

Granted, a function that combines both steps into one and that avoids the intermediate array would offer a performance advantage. It's not going to be significant unless you zip-map millions of objects in a hot loop, but it might be just useful enough to add it to an extension library like Underscore-Contrib.
