### ISSUE TITLE
Feature Request - Iteratee for difference / union / without

### ISSUE THREAD

**Issue by hunterSThompson** [jashkenas/underscore#2427]
It would be cool to be able to override default with an iteratee in difference, set, and the other set operations in Underscore.

For example:

```javascript
var obj1 = {id: 1, name: "John"};
var obj2 = {id: 2, name: "Bob"};
var obj3 = {id: 3, name: "Steve"};

var list1 = [obj1, obj2, obj3];
var list2 = [obj1, obj2];

var difference = _.difference(list1, list2, function(x, y) { return x.Id == y.Id });
// difference -> [obj3]
```

Would this be useful to anyone else?  Can start working on a patch if so.

**Comment by akre54** [comment]
This seems like it'd be useful. Send that patch!

**Comment by jdalton** [comment]
Dup of #2311.

**Comment by binarykitchen** [comment]
Me too would welcome this feature. Looking at the long thread in #2311 doesnt help. Can't someone summarize the solution here?
