### ISSUE TITLE
the method "chain" of _ instance,where did it been defined?

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2428]
https://github.com/jashkenas/underscore/blob/master/underscore.js#L1559
in this line,there is an instance function(prototype function) ```chain``` been invoked.
but i just found there is only a static function(none prototype function) defined in the source code.
https://github.com/jashkenas/underscore/blob/master/underscore.js#L1545

**Comment by michaelficarra** [comment]
https://github.com/jashkenas/underscore/issues/2419#issuecomment-173268689

**Comment by megawac** [comment]
It's defined on line #L1159 and #L1566
