### ISSUE TITLE
deep and shallow operations

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2434]
some methods will treat the object in a deep operation behavior,like ```_.isEqual```
while some will in a shallow behavior,like ```_.each```
and i found that there are some methods to which you can pass on a Boolean value to specify deep or shallow
so i suggest that we should add more details in the documentation
maybe a list in a individual paragraph,or a tag picture after every method name to indicate that 
sorry for my english

**Comment by victorwpbastos** [comment]
`_.where` and `_.findWhere` with deep search would be amazing!

**Comment by akre54** [comment]
"Deep" anything is a difficult problem in Javascript, and it's almost always better to write these operations by hand if you know your object's shape ahead of time. There's some good discussion in #162 and several others for more background.

`_.isEqual` is a special case, and is broadly useful enough that including it in Underscore makes sense. I'm not sure it makes sense for a deep `_.each` to be included, however. Maybe as a mixin / contrib package.
