### ISSUE TITLE
why QUnit test for _.reduce can't pass

### ISSUE THREAD

**Issue by wendaosanshou** [jashkenas/underscore#2443]
if i test reduce function just like
```javascrit
sum = _.reduce([1, 2, 3], function(memo, num){ return memo + num * 3 });
assert.equal(sum, 18, 'can reduce with multiply three');
```
there will not pass:
![qunit-reduce error](https://raw.githubusercontent.com/wendaosanshou/pic-repository/master/qunit-error.png)

bug if i set the mome a init number
```javascrit
sum = _.reduce([1, 2, 3], function(memo, num){ return memo + num * 3 },0);
assert.equal(sum, 18, 'can reduce with multiply three');
```
it's ok.
who can tell me why?

**Comment by captbaritone** [comment]
If you don't pass a starting value, `_.reduce' shifts (or the object equivalent of shifts) the first item off of the array and uses that as the initial value. So in the first case, the multiplication is not applied to the `1` value.

He relevant code is here: https://github.com/jashkenas/underscore/blob/master/underscore.js#L195
