### ISSUE TITLE
When you guys say chaining

### ISSUE THREAD

**Issue by McFarts** [jashkenas/underscore#2444]
Is that basically the same as an async operation?

Pretty much, all chaining will be done in the order the method's are called, right?

**Comment by akre54** [comment]
> Is that basically the same as an async operation?

No, completely synchronous.

> Pretty much, all chaining will be done in the order the method's are called, right?

Yep (see [the source](https://github.com/jashkenas/underscore/blob/1.8.3/underscore.js#L1471-L1534)).

(In the future please use StackOverflow, the mailing list, or the Gitter channel for questions. Github issues are for maintaining the framework only).

**Comment by McFarts** [comment]
Awww I see. Sorry, I always post on Github as a habbit subconsciously, thanks for info!
