### ISSUE TITLE
_.isScalar

### ISSUE THREAD

**Issue by undercloud** [jashkenas/underscore#2446]
You can add new feature ```_.isScalar()``` like http://php.net/manual/en/function.is-scalar.php

**Comment by michaelficarra** [comment]
Since this is not PHP, you're going to have to describe what you mean here. Also list some example input/output pairs and use cases.

**Comment by akre54** [comment]
It [looks like](http://phpepl.herokuapp.com?code=echo%20is_scalar(3)%20%3F%20'true'%20%3A%20'false'%3B%0Aecho%20%22%5Cn%22%3B%0Aecho%20is_scalar(array(1%2C2%2C3))%20%3F%20'true'%20%3A%20'false'%3B) you're asking for [`_.isObject`](http://underscorejs.org/#isObject).

```php
echo is_scalar(3) ? 'true' : 'false'; // true
echo "\n";
echo is_scalar(array(1,2,3)) ? 'true' : 'false'; // false
```

```js
console.log(_.isObject(3)); // false
console.log(_.isObject([1,2,3])); // true
```
