### ISSUE TITLE
isMap, isSet, isWeakSet, isWeakMap

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2449]
Additional ES6 type methods for isMap, isSet, isWeakSet, isWeakMap as companions to `_.isSymbol`.

**Comment by akre54** [comment]
Sure, feel free to open a pull!

**Comment by jdalton** [comment]
Let's leave it open for outside folks who may want to do the PR.

**Comment by akre54** [comment]
Sure thing. Or you could do it!

**Comment by jdalton** [comment]
Dude. Stop with the label hijinks. You are not the lead dev on this. If I want to create a label to help direct devs then I'll do it. You will not be removing it.

**Comment by jdalton** [comment]
Srsly go get your alpha male kicks somewhere else.

**Comment by akre54** [comment]
Nobodys hung up on anything. I thought it was a glitch that it got re-added. Chill.

**Comment by jdalton** [comment]
:ok_hand:

**Comment by akre54** [comment]
> Srsly go get your alpha male kicks somewhere else.

🤔

**Comment by bjmiller** [comment]
Should there be a single method that returns true for both Map and WeakMap? (And, similar for sets?). Or, should it be idiomatic to use `(_.isMap || _.isWeakMap)`?

**Comment by jdalton** [comment]
I think weakmaps are different enough to warrant a separate method. If you want a weak map you probably need its weak reference sugar.

**Comment by akre54** [comment]
You really need to stop deleting my comments / editing your comments to change the discussion context. 

This isn't about moderating, you just really don't like people disagreeing with you.

**Comment by jdalton** [comment]
Public bickering doesn't serve the good of the project. Sorry moderation stands.

**Comment by jdalton** [comment]
Public bickering doesn't serve the good of the project. It's gross & derails threads. Moderation stands.

**Comment by jdalton** [comment]
Public bickering doesn't serve the good of the project. It's gross & derails threads. Moderation stands.

**Comment by jdalton** [comment]
Adam this is beyond ridiculous.

**Comment by akre54** [comment]
Back to the issue at hand, I'm fine with them as separate methods.

**Comment by jdalton** [comment]
Public bickering doesn't serve the good of the project. It's gross & derails threads. Moderation stands.

**Comment by MahmudH** [comment]
Me and my friend George(gwpmad) are going to try to work on this now.

**Comment by jdalton** [comment]
Awesome, thank you!

**Comment by gwpmad** [comment]
@jdalton We're just doing this now, do we need to make any changes to the minified version?

**Comment by akre54** [comment]
@gwpmad, nope. We minify / add docs when we release new versions. Just add the code and some tests.
