### ISSUE TITLE
Add map/set support to isEqual

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2451]
It'd be great if `_.isEqual` supported comparing maps and sets.

**Comment by aebrow4** [comment]
I'm working on this.

**Comment by targumon** [comment]
Any progress/update? (I'd love to assist, but don't want to make a redundant PR)

**Comment by BrokeRU** [comment]
Here is my solution for Map objects: https://gist.github.com/BrokeRU/5ece2a775b4c3f576425d5fb30b09736

**Comment by jgonggrijp** [comment]
Special case of #2147.
