### ISSUE TITLE
_.omit and symbols

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2457]
ES6 Symbols work out of the box in many Underscore methods like `_.has` and `_.pick`, however `_.omit` needs special attention for support.

``` js
function Foo() {
  this.a = 0;
  this[symbol1] = 1;
}
var symbol1 = Symbol('a');
var symbol2 = Symbol('b');
Foo.prototype[symbol2] = 2;

var foo = new Foo;
var actual = _.omit(foo, 'a');

actual[symbol1] // should be 1 but is `undefined`
actual[symbol2] // should be 2 but is `undefined`
```

**Comment by edwardkerry** [comment]
I'm taking a look a this, hope to submit a PR tomorrow.

**Comment by jdalton** [comment]
Rock! Thank you!

**Comment by jdalton** [comment]
Besides omitting correct symbols it should also not coerce them to strings:
```js
var o = { 'Symbol(a)': 'boo', 'Symbol(b)': 'baz' };
_.omit(o, Symbol('a'));
// => { 'Symbol(b)': 'baz' }
```

**Comment by harshitharao** [comment]
@jdalton @edwardkerry https://github.com/jashkenas/underscore/pull/2789 is the fix PR. Can you check once

**Comment by jgonggrijp** [comment]
Closing for the same reason as #2789.
