### ISSUE TITLE
why not use Array.prototype.includes?

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2458]
why not use `Array.prototype.includes` to implement the method `_.includes`?

**Comment by captbaritone** [comment]
For one, `Array.prototype.includes` is not supported in IE (see the compatibility chart here): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

In the future, these sorts of questions would be better raised in the [Gitter](https://gitter.im/jashkenas/underscore).
