### ISSUE TITLE
_.where and date

### ISSUE THREAD

**Issue by irvgk** [jashkenas/underscore#2467]
I tried to compare two objects like below but its not giving expected result. 

```
function Foo(){
 
  var sampleSource = [
  	{a:"Test 1", b: 123, c:new Date(2006)},
  	{a:"Test 2", b: 555, c:new Date(2008)}
  ];
  test = {a:"Test 1", b: 123, c:new Date(2006)};

  var machedRecords = _.where(sampleSource, test);
  console.log(machedRecords); // this is printing empty array
}
```

[Plunker](https://plnkr.co/edit/LOAO5hiuqq3VoPlyzzhH?p=preview)

**Comment by captbaritone** [comment]
This is because dates in JavaScript are objects, and objects are compared by reference not by value.

This StackOverflow answer has some more information and possible solutions: http://stackoverflow.com/a/7606839/1263117

**Comment by jdalton** [comment]
@irvgk If you're wanting partial deep comparisons you can try using the [lodash.filter](https://www.npmjs.com/package/lodash.filter) package:
```js
var where = require('lodash.filter');

var sampleSource = [
  {a:"Test 1", b: 123, c:new Date(2006)},
  {a:"Test 2", b: 555, c:new Date(2008)}
];
where(sampleSource, {c:new Date(2006)});
// => [{a:"Test 1", b: 123, c:new Date(2006)}]

**Comment by captbaritone** [comment]
Just a note that 2006 will be interpenetrated as "the number of milliseconds since 1 January 1970 00:00:00 UTC (Unix Epoch)." [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

    new Date(2006);
    // => Date 1970-01-01T00:00:02.006Z

I'm guessing this was just an artifact introduced by simplifying your use case (thanks for that!) but I figured I'd call it out so that others don't get confused.

**Comment by jdalton** [comment]
FWIW the deep partial comparisons work with [moment.js](http://momentjs.com/) too
```js
var sampleSource = [
  {a:"Test 1", b: 123, c: moment([2006])},
  {a:"Test 2", b: 555, c: moment([2008])}
];
where(sampleSource, {c:moment([2006])});
// => // => [{a:"Test 1", b: 123, c: moment([2006])}]
moment([2006]).toDate();
// date object of Sun Jan 01 2006 00:00:00 GMT-0800 (PST)
```
