### ISSUE TITLE
Map not behaving properly

### ISSUE THREAD

**Issue by keystonestrategy** [jashkenas/underscore#2469]
GridComponent model has reference id (field is componentid) to Component model

```
_.map(components,function (component){
			var foo = (new Component())._id;
			component.componentid = foo;
			var gc = new GridComponent(component);
			
			assert(typeof gc.componentid !== 'undefined');

		})
```

fails yet

```
_.map(components,function (component){
			var foo = (new Component())._id;
			var testComponent = JSON.parse(JSON.stringify(component));
			testComponent['componentid'] = component._id;
			
			var gc = new GridComponent(testComponent);
			
			assert(typeof gc.componentid !== 'undefined');

		})
```

passes

**Comment by captbaritone** [comment]
@keystonestrategy Could you please simplify your example to not depend on your application specific code? It's nearly impossible for us to tell where the failure is given that you have not shown us the code that sets the value you are testing.

**Comment by akre54** [comment]
It would help if you created a JSFiddle or CodePen example that shows us exactly where the error is happening.

**Comment by captbaritone** [comment]
Closing for now.

@keystonestrategy, feel free to comment on the closed issue if you have an example for us to look at. We can always re-open the issue.
