### ISSUE TITLE
how about a upsert in underscore

### ISSUE THREAD

**Issue by harryi3t** [jashkenas/underscore#2471]
I would like to have a [mongoDb's upsert][1] like function in underscore too.

#### parameters
```javascript
_.upsert(DESTINATION_ARRAY, SOURCE_OBJECT, KEY)
```

 - DESTINATION_ARRAY: The array that will be searched and will get updated.
 - SOURCE_OBJECT: The object that will get searched in the `DESTINATION_ARRAY`
 - KEY: `SOURCE_OBJECT` will be searched based on this key value in the `DESTINATION_ARRAY`.

#### example usage:
```javascript
var employees = [
 {id:1,name:"emp1"},
 {id:2,name:"emp2"}
];

var updatedEmp1 = {id:1, name:"updated_emp1", foo:'bar'};
var updatedEmployees = _.upsert(employees, updatedEmp1, 'id');
// Now the updatedEmployees is
 updatedEmployees = [
 {id:1,name:"updated_emp1", foo:"bar"},
 {id:2,name:"emp2"}
];
```

#### Example code to achieve this as of now using existing `_` functions:
```javascript
_.upsert = function (destArray, sourceObj, key) {
 var oldObject = _.find(destArray,
   function (emp) {
     return emp[key] === sourceObj[key];
   }
 );
 if (oldObject)
   _.extend(oldObject, sourceObj);
 return destArray;
}
```

[1]: https://docs.mongodb.org/manual/reference/method/Bulk.find.upsert/

**Comment by michaelficarra** [comment]
:-1:. What you want can already be accomplished with

```js
employees[_.findIndex(employees, _.pick(updatedEmp1, "id"))] = updatedEmp1;
```

If you want to define your own `upsert` helper, just

```js
_.mixin({ upsert: function(list, el, primaryKey) {
  list[_.findIndex(list, _.pick(el, primaryKey))] = el;
  return list;
});
```

**Comment by harryi3t** [comment]
@michaelficarra Thanks for showing the right way to achieve this. :+1:
