### ISSUE TITLE
Is there a reason that the callback function doesn't handle regexes?

### ISSUE THREAD

**Issue by olleicua** [jashkenas/underscore#2474]
It would be great to have:

```javascript
_.select(['abc', 'def'], /ab/) // [ 'abc' ]
```

And it seems like an easy addition:

```javascript
var cb = function(value, context, argCount) {
  if (value == null) return _.identity;
  if (_.isFunction(value)) return optimizeCb(value, context, argCount);
  if (_.isObject(value)) return _.matcher(value);
  if (_.isRegExp(value)) return function(obj) { return !!value.exec(obj) };
  return _.property(value);
};
```

**Comment by akre54** [comment]
Sure, looks great. In the future, please just open one or the other an issue or pull request, no need to open two of them.

**Comment by jdalton** [comment]
Seems like this would be a good reason to use `_.iteratee` to be used internally instead.
That way if folks want to customize shorthands they can just overload `_.iteratee`.

**Comment by captbaritone** [comment]
Closing in favor of the related PR: #2475

FYI: We are discussing allowing users to customize _.iteratee here: https://github.com/jashkenas/underscore/pull/2480
