### ISSUE TITLE
why the code are different although both are 1.8.3 version?

### ISSUE THREAD

**Issue by hanzichi** [jashkenas/underscore#2477]
I love underscore.js and want to read the code, but I wonder which one I should read. This one <https://github.com/jashkenas/underscore/blob/master/underscore.js> or this one <https://github.com/jashkenas/underscore/blob/master/docs/underscore.html> , could you help me ?

**Comment by meleslilijing** [comment]
Both, fighting!

**Comment by jridgewell** [comment]
https://github.com/jashkenas/underscore/blob/master/underscore.js is the current edge, with unreleased changes.

https://github.com/jashkenas/underscore/blob/master/docs/underscore.html is the latest release.
