### ISSUE TITLE
there may be some problems with  _.debounce 

### ISSUE THREAD

**Issue by hanzichi** [jashkenas/underscore#2478]
in this file <https://github.com/jashkenas/underscore/blob/master/underscore.js>

I think there may be some issues in _.debounce function, if we use like this

```
var lazyLayout = _.debounce(function() {
	console.log(123)
	} , 300, true);

window.onresize = lazyLayout;
```

there will be only one '123' in the console after resizing the window several times.

**Comment by akre54** [comment]
I can't reproduce.

![screenshot 2016-03-23 09 48 09](https://cloud.githubusercontent.com/assets/931368/13987110/684c6f40-f0dc-11e5-9108-7ccdd89cbadd.png)

**Comment by jridgewell** [comment]
> I can't reproduce.

Same. @hanzichi: Are you waiting the 300 ms before resizing again?

**Comment by hanzichi** [comment]
@akre54 @jridgewell I find this problem when using <https://github.com/jashkenas/underscore/blob/master/underscore.js>, not the min one or anyone else, you have use this one the same? very happy to see your reply! thanks!

**Comment by jridgewell** [comment]
Ooo, there is a bug.
