### ISSUE TITLE
Should _.each process it's iteratee through _.iteratee?

### ISSUE THREAD

**Issue by captbaritone** [jashkenas/underscore#2487]
Now that users can customize `_.iteratee`, @jridgewell [suggested](https://github.com/jashkenas/underscore/pull/2480#issuecomment-200964845) that we should transform `_.each`'s iteratee through `_.iteratee`.

I don't personally see a use case for this, but I figured we should discuss it.

Since the existing paradigm for `_.iteratee` is to transform and _return_ (but not mutate) each value in the collection, and `_.each` ignores the return from it's iteratee, what value would this provide?

Is there some reasonable use case where one would customize `_.iteratee` such that it would mutate the items passed to it?

On the other hand, I guess it doesn't really cost us anything to do it, so why not?

**Comment by jridgewell** [comment]
API simplicity is the biggest win. If I override `_.iteratee` to do something, why should all the collection methods _except_ `_.each` work?

**Comment by akre54** [comment]
I'm inclined to agree with @captbaritone here. It's perfectly fine for `_.each` to behave differently given that it doesn't have a meaningful return value. @jridgewell what were you thinking of the use cases for this?

**Comment by jridgewell** [comment]
An `result` like modification, so `_.iteratee` will call the method if it's a method:

```js
_.iteratee = _.wrap(_.iteratee, function(iteratee, value, context) {
  if (typeof value === 'string') return function(obj) {
    return _.result(obj, value);
  };
  return iteratee(value, context);
});
```

**Comment by jdalton** [comment]
>  An result like modification, so _.iteratee will call the method if it's a method:

Wouldn't that just create a bunch of functions that wouldn't get executed in the `each`?

**Comment by jdalton** [comment]
Ah nm they would provide the string which would then call the method on each element in the collection.

**Comment by akre54** [comment]
So you'd use it like `_.each(foo, 'bar')`? This is essentially a `map` without a return value, right?

**Comment by jdalton** [comment]
It's `_.invoke`.

**Comment by captbaritone** [comment]
I don't really see a strong case here. I'm going to close the issue. I'd be happy to reopen the issue if there seems to be some compelling reason, or other interest.
