### ISSUE TITLE
_.memoize hasher result cannot be a symbol.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2497]
Because the `_.memoize` hasher is resolved with `'' +` it will throw an error if the hasher result is a Symbol. A similar issue exists in `createEscaper`.

**Comment by jdalton** [comment]
A similar issue exists in `createEscaper`.

**Comment by CodeFalling** [comment]
But `createEscaper` just won't work with `symbol`, what should we do here?

**Comment by blacklovebear** [comment]
Does "memoize" spell wrong???  I'm confused

**Comment by jgonggrijp** [comment]
Duplicate of #1862.
