### ISSUE TITLE
coalesce

### ISSUE THREAD

**Issue by cavitkeskin** [jashkenas/underscore#2504]
I think coalesce function should be useful.
this function returns first argument that is not null or undefined.

**Comment by captbaritone** [comment]
Could you give an example use case?

**Comment by akre54** [comment]
I think @cavitkeskin is referring to something like [SQL's `COALESCE` statement](https://docs.oracle.com/cd/B28359_01/server.111/b28286/functions023.htm). This is easy enough to accomplish in plain JS with the logical `||` operator:

```js
const result = a || b || c;
```

If you need something more advanced than that (specifically only the first non-null / undefined result), use `find`: 

```js
const result = [a, b, c].find(obj => obj != null);
```
