### ISSUE TITLE
_.has, other property methods, and -0.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2505]
Unlike other integer keys `-0` is coerced to `"0"` when converted to a string:
```js
_.has({ '-0': 'a' }, -0); // false
```

**Comment by CodeFalling** [comment]
So dose '+0',

```js
console.log(_.has({ '+0': 'a' }, +0)); // false
console.log(_.has({ '0': 'a' }, +0)); // true
console.log(_.has({ '0': 'a' }, -0)); // true
```

But this just default behavior of JavaScript, should we change this?

```js
var obj = {
  '-0': '-0 here',
  '+0': '+0 here'
}
obj[+0]; // undefined
obj['+0']; // '-0 here'

obj['0'] = 'just 0';
obj[+0]; // 'just 0'
obj[-0]; // 'just 0'

```

**Comment by jdalton** [comment]
The difference is that negative zero is detectable.

**Comment by CodeFalling** [comment]
What do you mean `detectable` ? I didn't understand the difference of `-0` and `+0` here.

**Comment by jdalton** [comment]
`1 / -0` is `-Infinity`.

**Comment by akre54** [comment]
Got a real world case of this biting someone?

**Comment by jashkenas** [comment]
This seems a little bit too silly to support.
