### ISSUE TITLE
_.functions function should consider about IE < 9

### ISSUE THREAD

**Issue by hanzichi** [jashkenas/underscore#2511]
If the key is `toString`, so we cannot enum the key?

as below:

    var obj = {
      a: function() {

      },

      toString: function() {

      }
    };

    var ans = _.functions(obj);
    alert(ans); // IE 8 alert `a

**Comment by hanzichi** [comment]
@akre54 @jridgewell @megawac could you help me?  That's really trouble me .. thanks in advance !

**Comment by megawac** [comment]
What version of underscore are you using? This has been fixed since 1.8 I believe

Works in emulation mode at any rate
![](http://puu.sh/ovPVO/1222153aa7.png)

**Comment by hanzichi** [comment]
I just use the current version. I think _.functions doesn't consider about IE < 9 as _.keys does. see here <https://github.com/jashkenas/underscore/blob/master/underscore.js#L1033-L1039> maybe I am wrong,  really thanks for your answer !

**Comment by jridgewell** [comment]
https://github.com/jashkenas/underscore/issues/2512 is the real issue.
