### ISSUE TITLE
There may be some problem with _.keys function

### ISSUE THREAD

**Issue by hanzichi** [jashkenas/underscore#2512]
code as below:

```javascript
function Fn() {
  this.name = 'hanzichi';
  this.age = 30;
  this.toString = Fn.prototype.toString;
}

var obj = new Fn();

var ans = _.keys(obj);

alert(ans);
// Chrome name,age,toString
// IE 8 name,age
```

**Comment by hanzichi** [comment]
And in the function `collectNonEnumProps `:

```javascript
var collectNonEnumProps = function(obj, keys) {
  var nonEnumIdx = nonEnumerableProps.length;
  var constructor = obj.constructor;
  var proto = _.isFunction(constructor) && constructor.prototype || ObjProto;

  // Constructor is a special case.
  var prop = 'constructor';
  if (_.has(obj, prop) && !_.contains(keys, prop)) keys.push(prop);

  while (nonEnumIdx--) {
    prop = nonEnumerableProps[nonEnumIdx];
    if (prop in obj && obj[prop] !== proto[prop] && !_.contains(keys, prop)) {
      keys.push(prop);
    }
  }
};
```

I think `prop in obj` may always return `true`, it may be needless,  is that right?

**Comment by hanzichi** [comment]
@akre54 @jridgewell @megawac could you help me?  That's really trouble me .. thanks in advance !

**Comment by megawac** [comment]
This also works in 1.8

**Comment by jridgewell** [comment]
This is only an issue in IE 8 and below. We can try walking the constructor chain to grab (what may be) the prototype chain, but that's fraught with issues too. I think this one's just too old to bother with.

**Comment by jdalton** [comment]
Even es5-shim won't help with that case.

**Comment by hanzichi** [comment]
Thanks! You really help me a lot, I think IE < 9's too old to bother with,hah..

BTW, *Constructor is a special case.*  What will cause if considering it the same as `toString` ? I have tried, and find both `_.has(obj, prop)` and `obj[prop] !== proto[prop]` are ok for them. Could you help me please? with full thanks!

And I think `prop in obj` and ` !_.contains(keys, prop)` may be needless, it that right?

**Comment by hanzichi** [comment]
Excuse me, may disturb you again @akre54 @jridgewell @megawac @jdalton But that's the question I really wonder.. see above thanks a lot ! I really want to understand function `collectNonEnumProps ` a lot

**Comment by mattdiamond** [comment]
@hanzichi are you still wondering about this?

**Comment by hanzichi** [comment]
@mattdiamond maybe I am

**Comment by megawac** [comment]
I think this is just one of those things we can't fix.

**Comment by anotherleon** [comment]
**I think I found a another Bug:**
if  obj.constructor was overwirtten，and constructor.ptototype.toString = null
eg:
```
var Func = function() { }; Func.prototype.toString = null;  var obj = { constructor: Func };
var keys = [];
collectNonEnumProps(obj, keys)
console.log(keys) // return value is =>["constructor", "toString"]
```
I think the problem is  `var proto = (_.isFunction(constructor) && constructor.prototype) || ObjProto; ... if(...obj[prop] !== proto[prop]...) `
Am I understanding this right?
