### ISSUE TITLE
_.pairs and maps

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2517]
I was working with maps and reached for a `_.pairs` method to get its key-value pairs and thought it would be handy to support.

``` js
var m = new Map([['a', 1], ['b', 2]]);
_.pairs(m);
// => [['a', 1], ['b', 2]]
```

**Comment by penDerGraft** [comment]
I would be up for working on this. Are you thinking this would just add a `for..of` loop in the existing `_.pairs` method, assuming it is an `instanceof Map`?

**Comment by jdalton** [comment]
Yep! I was thinking just for maps at the moment, using `_.isMap`.

**Comment by akre54** [comment]
You can't use `for...of` in old envs. The best bet is probably to use `Array.from(m.entries())` if the type is Map or Set.

**Comment by penDerGraft** [comment]
Looks like there are several compatibility issues with different versions of node. in `v0.10.*` and below, there's an error parsing `for..of`. in `v.0.12.*`, Map is defined, but `Array.from` is not supported. 

I think the best way to handle it is to iterate from 0 to `map.size` and push `entries().next()` into the return array. Any other ideas?

**Comment by jdalton** [comment]
fyi I [created poll](https://twitter.com/jdalton/status/725375742570188800) to see what folks expected the behavior of maps to be.
Results are ~50/50.
<img width="60%" src="https://cloud.githubusercontent.com/assets/4303/14969016/ce9e19c6-1074-11e6-82d2-120e5908a769.png">

**Comment by jridgewell** [comment]
Why would it be `[]`?

**Comment by jdalton** [comment]
That's what the current draft spec has its behavior as.
It just iterates over an object's own enumerable keys.

**Comment by jridgewell** [comment]
Well, I should have read the spec. I was expecting something like the Reflect API, were it's just what `Map#entries` does.

**Comment by jdalton** [comment]
Ya, I think it's kinda goofy for a method called `entries` to not return a map's entries.

**Comment by jgonggrijp** [comment]
Special case of #2147.
