### ISSUE TITLE
Comparison Operators ===

### ISSUE THREAD

**Issue by oscarmorrison** [jashkenas/underscore#2522]
Throughout Underscore strict equality operator === is not always used,
and primarily only == is used. Isnt this more inefficient and generally considered bad practice as it
does a type conversion before comparing? 

Example:
https://github.com/jashkenas/underscore/blob/master/underscore.js#L69

(New OS Contributor)

**Comment by michaelficarra** [comment]
`==` is safe when used against null or to compare two values that are known to have the same type. All usages in underscore should be safe. Feel free to let us know if you think you've found one that isn't.

**Comment by oscarmorrison** [comment]
Thanks @michaelficarra for the follow up
