### ISSUE TITLE
_.mapKeys to map object keys

### ISSUE THREAD

**Issue by arypbatista** [jashkenas/underscore#2526]
Map object keys.

```
let _ = require('underscore');

module.exports = (o, f) =>
  _.object(
    _.map(
      _.pairs(o), (keyValue) => [f(keyValue[0], keyValue[1]), keyValue[1]]
    )
  );

```

**Comment by akre54** [comment]
Try `_.keys` with a `_.map`.

**Comment by arypbatista** [comment]
I want to have a function that returns an object with mapped keys.

`mapKeys :: ( Object, KeyMappingFunction ) -> Object`

This is more than combining `_.keys` and `_.map`.

**Comment by jdalton** [comment]
See [lodash/mapKeys](https://github.com/lodash/lodash/blob/4.11.2-npm/mapKeys.js) or [lodash.mapkeys](https://www.npmjs.com/package/lodash.mapkeys).
