### ISSUE TITLE
proposal: add rejectFirst

### ISSUE THREAD

**Issue by DanielYWoo** [jashkenas/underscore#2533]
reject() iterates the whole list, can we stop once a matching one is found?

**Comment by MatthewVita** [comment]
Can you include a use case example?

**Comment by DanielYWoo** [comment]
Suppose you have a big list and you want to remove the first matching element, or you are sure that the list does not contain duplicated elements, using reject would traverse the whole list which is somehow slow. rejectFirst() should stop and return the first matching element.

**Comment by MatthewVita** [comment]
Not trying to be difficult, but this sounds like something that would best fit in underscore-contrib http://documentcloud.github.io/underscore-contrib/#why-underscore-contrib

My reasoning is that it is very specific/not very common (not saying it isn't useful).

I would appreciate another opinion here, however.

**Comment by Florian-R** [comment]
If #1545 was landed, we could have this almost for free I presume, but this PR seems stalled.

**Comment by akre54** [comment]
Yeah this sounds like a great fit for Underscore-contrib or a mixin for your own project. The primitives are all already there, you just gotta build on them.
