### ISSUE TITLE
Font Roboto distributed without full text of Apache 2.0 license

### ISSUE THREAD

**Issue by vlna** [jashkenas/underscore#2535]
`underscore/docs/public/fonts/` contains Apache 2.0 licensed Roboto fonts (see https://github.com/google/roboto and https://www.google.com/fonts/specimen/Roboto)

According Apache 2.0 license full text of license must be included.

`give any other recipients of the Work or Derivative Works a copy of this License`

Solution: include full text of license from https://github.com/google/roboto

**Comment by jridgewell** [comment]
This is a `docco` [issue](https://github.com/jashkenas/docco/issues/263). Mind opening there?
