### ISSUE TITLE
Aller fonts (probably) distributed without proper license

### ISSUE THREAD

**Issue by vlna** [jashkenas/underscore#2536]
`underscore/docs/public/fonts/` contains commercially licensed Aller fonts (see https://www.daltonmaag.com/aller and https://www.fontsquirrel.com/fonts/Aller)

Solution: remove/replace all Aller fonts or add information about Aller font license

**Comment by jridgewell** [comment]
This is a `docco` [issue](https://github.com/jashkenas/docco/issues/263), mind opening there?

**Comment by vlna** [comment]
It is issue of everyone who redistributes these fonts. It creates risk of counter-action of copyright holder against underscore development team and/or individual developers.
