### ISSUE TITLE
To add feature of clearing all object attributes

### ISSUE THREAD

**Issue by mariaczi** [jashkenas/underscore#2544]
Hi,

It would be really worth to add function `_.reset` or `_.clear`.
What I mean is that quite often there is need to clear all attributes values of object,
but without deleting this object like `obj = {}`.

**Comment by akre54** [comment]
What's the use case?

**Comment by mariaczi** [comment]
In Angular, VueJS, REACT etc you have object with all data props for every
form which you have.
After sending this data successful you need to clear content of properties,
but not erase whole model.

2016-06-15 14:05 GMT+01:00 Adam Krebs <notifications@github.com>:

**Comment by akre54** [comment]
Thanks but no thanks. I think this is either something you should be doing yourself (like with `Object.keys(obj).forEach(key => obj[key] =  undefined)`), or the framework should be able to handle passing new objects. Backbone, for instance, does it [this way](https://github.com/jashkenas/backbone/blob/1.3.3/backbone.js#L541-L546).
