### ISSUE TITLE
Some questions for source code！

### ISSUE THREAD

**Issue by Zhang-Yida** [jashkenas/underscore#2547]
First, thx for you repo, this gives me so much help. And when I read the source code, I had some questions. The code below, could you please give me some help about why you define _ with these code?
`// Create a safe reference to the Underscore object for use below.`
`  var _ = function(obj) {`
`    if (obj instanceof _) return obj;`
`    if (!(this instanceof _)) return new _(obj);`
`    this._wrapped = obj;`
`  }`

thx again!

**Comment by akre54** [comment]
We want the `_` variable to be accessible as both a function and an object&mdash;you should be able to call the methods using either `_.each(arr, fn)` or `_(arr).each(fn)`. This bit of code allows us to handle both cases.
