### ISSUE TITLE
Problem in iframe element createAssigner for IE/EDGE

### ISSUE THREAD

**Issue by sea-kg** [jashkenas/underscore#2549]
If undescore.js loaded in iframe for IE/EDGE

    SCRIPT5: Access deby.
    File: underscore.js, line: 1057, column: 49

It's happend when underscore loaded in iframe and it try work with 'frameElement'

My propose is just ignore problem key:

          if(key == "frameElement") { // ignore this key
             console.warn('undescore.js - frameElement skiped')
             continue;
          }

And insert in this function

	  var createAssigner = function(keysFunc, defaults) {
		return function(obj) {
		  var length = arguments.length;
		  if (defaults) obj = Object(obj);
		  if (length < 2 || obj == null) return obj;
		  for (var index = 1; index < length; index++) {
			var source = arguments[index],
				keys = keysFunc(source),
				l = keys.length;
			for (var i = 0; i < l; i++) {
			  var key = keys[i];
			  if(key == "frameElement") { // ignore this key
				 console.warn('undescore.js - frameElement skiped')
				 continue;
			  }
			  if (!defaults || obj[key] === void 0) obj[key] = source[key];
			}
		  }
		  return obj;
		};
	  };

And now work fine

**Comment by captbaritone** [comment]
It seems to me that Underscore is behaving properly in this instance. Could you give an example of a benign usage of Underscore that results in this error? Perhaps using jsfiddle.net ?

**Comment by sea-kg** [comment]
Hello, 
I am sorry that not said about "backbone" + "crossdomain frame".
And prepare page  http://files.sea-kg.com/bugs/underscore/2549/
Tested on IE11 - will reproduce.

[bug_underscore_2549.zip](https://github.com/jashkenas/underscore/files/383246/bug_underscore_2549.zip)

**Comment by jashkenas** [comment]
So, sounds like a Backbone thing then?
