### ISSUE TITLE
_.isObject for functions is true?

### ISSUE THREAD

**Issue by sateffen** [jashkenas/underscore#2551]
Hey,

why the fudge is `_.isObject(function() {}) === true`? This makes no sense. If function is an object, array should be one as well, otherwise it's pretty inconsistent. To check, whether it's a function or not they should use `_.isFunction`.

Can someone explain this to me?

Cheers

**Comment by jridgewell** [comment]
It's because you can `fn.prop = 'value'`, making them "objects".

> If function is an object, array should be one as well, otherwise it's pretty inconsistent.

They both are. 😉

**Comment by sateffen** [comment]
Right, `typeof []` is an object, I wasn't there for a moment.

Seeing it from that point of view, you're right. And while driving home, I came across something else: A class (`class foo {}`) should be an object as well, but `typeof foo` is still `function`, because it's a prototype (so basically an 

I should have known this :-D Sorry for the unnecessary issue

Cheers
