### ISSUE TITLE
Documentation: max/min don't work for non-numerical values

### ISSUE THREAD

**Issue by sawalls** [jashkenas/underscore#2552]
```javascript
>>_.max(['a string', 'AN EARLIER STRING'])
-Infinity
```

It isn't obvious to me from the documentation that this wouldn't work. I would guess that `max` would work for anything with a well-defined `<` and `>` operator. Looking at the source, it won't work for anything that doesn't compare correctly to -Infinity, though.

I think the documentation should include something about this.

**Comment by akre54** [comment]
Feel free to open a documentation change pull. That'd be a lovely addition.
