### ISSUE TITLE
_.object returning unexpected result with one letter in key/value

### ISSUE THREAD

**Issue by brunolemos** [jashkenas/underscore#2558]
```
var arr = ['aaa', 'bbb']
var result = _.object(arr);
```

Current result: `{ a: 'a', b: 'b' }`
Expected result: `{ 'aaa': undefined, 'bbb': undefined }`

Workaround: 
```
var result = _.object(arr, {});
```

The second parameter isn't supposed to be required, is it?

Underscore 1.8.3
Node.js 6.2.1

**Comment by brunolemos** [comment]
Duplicated of #1147, but that's still an awkward behaviour that should be fixed (better handling the missing second parameter).

**Comment by akre54** [comment]
Yup. That's not the purpose of `_.object`.

You could write this as a `reduce` and perhaps mix it into your own copy of Underscore:

```js
_.reduce(['aaa', 'bbb'], (obj, key) => {
  obj[key] = true
  return obj
}, {})
```
