### ISSUE TITLE
Live & Interactive code snippets for underscore.js

### ISSUE THREAD

**Issue by viebel** [jashkenas/underscore#2559]
It would be very cool and very helpful to `underscore.js` beginners to add live and interactive code snippets to http://underscorejs.org/, with the klipse plugin.

Here is a demo of the klipse plugin: http://blog.klipse.tech/javascript/2016/06/20/blog-javascript.html
Disclaimer: I'm the klipse author.

**Comment by akre54** [comment]
What'd you have in mind? We already include Underscore on the page for users to play around with in the console.

**Comment by viebel** [comment]
The console is nice. I'm talking about transforming all the code snippets and making them interactive. Like I demonstrated it here http://blog.klipse.tech/javascript/2016/06/20/blog-javascript.html

Does it make sense?

**Comment by akre54** [comment]
Personally I like the minimalism of the examples we have currently but if you can find a way to implement klipse in an unobtrusive / lightweight way I think it could be a cool extra feature for the docs. I'll wait for other maintainers to weigh in though.

**Comment by viebel** [comment]
What do you mean exactly by "unobtrusive / lightweight way"?

**Comment by akre54** [comment]
Your examples look great, but we don't want to add the heavyweight CodeMirror editor and its dependencies to all 117 examples the page (with associated styling, syntax highlighting, etc). Perhaps better would be to turn our `<pre>` tags into `<textarea>`s and have the `eval`'d result output below the textearea?

**Comment by viebel** [comment]
It makes sense.
Do you mean something as minimalist as this: https://jsfiddle.net/viebel/8sqewz7j/9/ ?

Of course, you will provide the css for `textarea` and result.

**Comment by akre54** [comment]
Yup, that's basically what I had in mind. Styled to look similar to what we have currently except maybe interactive.

**Comment by viebel** [comment]
I have added the `minimalistic_ui` option to the `klipse_settings`.

In your case, you will have to set something like that:

```javascript
 window.klipse_settings = {
            minimalistic_ui: true,
            selector_eval_js: 'textarea',
```
This is the url of the new version of the klipse plugin: http://app.klipse.tech/plugin_prod/js/klipse_plugin.min.beta.js

(It's a beta version and I have not yet removed the code mirror code from it.)

Let me know if the `minimalistic_ui` option works for you.

Maybe it's better to continue this conversation by email: viebel@gmail.com

**Comment by akre54** [comment]
Forgive me but now that I'm thinking about it -- what does klipse give us over just changing the existing `pre`s to `textarea`s? Your JSFiddle demonstrates pretty much all we'd need.

If we can help it, we're trying to avoid *any* external dependencies, particularly for something as simple as this use case.

**Comment by viebel** [comment]
Ok. Then go for it!

If you mention somewhere that [KLIPSE](https://github.com/viebel/klipse)  has been a source of inspiration for you guys at `underscore.js`, I'd be really happy....
