### ISSUE TITLE
No clone the array in arrays

### ISSUE THREAD

**Issue by alejonext** [jashkenas/underscore#2562]
When cloning a Array it is within another

```javascript
var array = [ 
   ['a', 'b' ],
   ['c', 'd' ],
];
var cloneArray = _.clone(array);
cloneArray[0][0] = 'E';
console.log(array);
```
In console
```
[ 
   ['E', 'b' ],
   ['c', 'd' ],
]
```
**Is a reference** and not a a clone

**Comment by NickNaso** [comment]
Function **clone** in underscore return a shallow copy of the object or the array. It does not return deep copy of all objects and arrays. See: http://underscorejs.org/#clone If you want a deep clone you create your own function using clone.

**Comment by jdalton** [comment]
@alejonext Try `require('lodash/cloneDeep')` or [lodash.clonedeep](https://www.npmjs.com/package/lodash.clonedeep).
