### ISSUE TITLE
Improves `_.without` performance

### ISSUE THREAD

**Issue by AndrewZ1989** [jashkenas/underscore#2563]
In the current implementation of `_.without` complexity is O(n*m), where n - size of first array, m - size of second array. 
I suggest using following algorithm:
  1. Sort second array ( O(m*log(m)) ).
  2. For each element in first array: a.) Evaluate goldenSectionSearch(a) - implementation of golden section search algorithm, which returns 'true' if element contained in the second (sorted) array ( complexity is O(n*log(m)) ).

As a result, complexity is O(n*log(m)).

Of course, we can introduce certain heuristics (for example, use an old implementation for arrays of small dimension).

P.s.: In C# language complexity of similar function 'Except' in class 'Enumerable.cs' is O(n)...but she uses O(m) additional memory. Maybe we see in this direction too?

**Comment by AndrewZ1989** [comment]
Of course, when we sort the array (or arrays), we change the input arguments and get side effects. This is not good.

But it can be done even if the optimization in C#?

**Comment by captbaritone** [comment]
Thanks for your interests Andrew!

I don't believe `_.without` currently presents a performance bottleneck for us. Therefore the bar for any change is going to be fairly high:

1. It does not introduce any change in behavior.
2. It does not add any complexity to the code base.
3. It does not increase the minified/gzipped side of the library.

If you think you can achieve your improvement with these criteria, feel free to open a pull reqest.
