### ISSUE TITLE
proper way to handle import and typings with lodash/fp

### ISSUE THREAD

**Issue by Brakkar** [jashkenas/underscore#2564]
Hi,
in an es2015 node / typescript environment:

> import * as _ from 'lodash/fp'

Says it can't find the module.
And the require version looses all the typings.

So what's the proper way to use lodash/fp with proper import and typings ?

**Comment by michaelficarra** [comment]
This is not the lodash repo, nor is this a bug.

**Comment by Brakkar** [comment]
Sorry, please delete this.

**Comment by jdalton** [comment]
@Brakkar You can head on over to the [Lodash gitter chat](https://gitter.im/lodash/lodash) for help.
