### ISSUE TITLE
feature request: initialize and push into array

### ISSUE THREAD

**Issue by rianwouters** [jashkenas/underscore#2566]
Often times you want to push something into an array, but initialize it if it isn't yet:

a = a || []
a.push (v)

Why not offer this as  a= _.push(a, v)

Implementation:

_.push = function(a,v) { a= a || []; a.push(v); return a }

**Comment by jaikamat** [comment]
I wouldn't mind tackling this @rianwouters if everyone is OK with it?

**Comment by rianwouters** [comment]
even better:

_.push = function(a,v) { (a || a = []).push(v); return a }

**Comment by akre54** [comment]
Yup this is cool, but it's much better suited to a mixin than as part of core Underscore. Might be a good fit for Underscore-contrib.
