### ISSUE TITLE
_.property behaviour can be changed when redefining toString

### ISSUE THREAD

**Issue by zoltan-mihalyi** [jashkenas/underscore#2567]
For example: 

```javascript
var obj = {toString:function(){return 'x';}};
var prop = _.property(obj);
prop({x:1}); //1
obj.toString = function(){return 'y';};
prop({x:1}); //undefined
```

The _.matcher method copies the properties object to avoid a similar problem, therefore the _.property should create an immutable string in the same way.

**Comment by akre54** [comment]
... why are you redefining `toString`?

**Comment by akre54** [comment]
Also more to the point, `_.property` is meant to be used with a string argument. Its behavior is undefined for an object.
