### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by nazarhussain** [jashkenas/underscore#257]
I am getting this error in my application, while using this library:

`Uncaught SyntaxError: Unexpected identifier`

My code is 

`window.JST['product_icon'] = _.template('<div\nid="product_icon_<%= product.id %>"\nclass="product_icon itemSpacer"\ndata-product-id="<%= product.id %>">\n\n  <div\n  class="sticker item hide"\n  <% if (product.images and product.images.length) { %>\n  style="background-image:url(\'/assets/products/<%= product.images[0].id %>/small/<%= product.images[0].attachment_file_name %>\');"\n  <% } %>>\n\n    <div class="data-container">\n      <small class="id"><%= product.id %></small>\n      <div class="description">\n        <div class="background"></div>\n        <div class="text">\n          <a href="#" class="add-to-cart">\n            Add to cart\n          </a><br/>\n          <a href="<%= \'/products/\' + product.permalink %>" class="view-sticker-details">\n            View this sticker\n          </a>\n          <br/>\n          <a href="#" class="FPO-load-brands">\n            View all brand Stickers\n          </a>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n');`

I tried every thing but can not identify the problem. Please help me its urgent.

**Comment by viliush** [comment]
lisencijos$

**Comment by pratishtha25-gif** [comment]
i am having the same error please help!

**Comment by pratishtha25-gif** [comment]
> "Unexpected identifier" means that you have a variable you're trying to reference that hasn't been declared. Make sure you pass all the variables you're trying to use into your template.

you have copied it right
