### ISSUE TITLE
_.random(Infinity) should be 0 to largest finite value.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2571]
I noticed that `_.random(Infinity)` returns `Infinity` but it could treat it as `min` of `0` and `max` of largest finite value.

**Comment by Sarke** [comment]
Heh, "largest finite value" is not the same as `Infinity`.

What you want is `_.random(Number.MAX_SAFE_INTEGER)`

**Comment by jashkenas** [comment]
> Heh, "largest finite value" is not the same as Infinity.
> 
> What you want is _.random(Number.MAX_SAFE_INTEGER)

Agreed. I think that `_.random(Infinity)` returning Infinity is more what I'd expect to happen.
