### ISSUE TITLE
Node JS FREEZES when _.template is evaluated and a ReferenceError happens

### ISSUE THREAD

**Issue by JOscarEduardo** [jashkenas/underscore#2572]
I've found a weird behavior with [http://underscorejs.org/](http://underscorejs.org/) in Node JS:

When a reference error happens when we evaluate a template function, Node JS will FREEZE!

Examples:

**EXAMPLE 1: HAPPY DAY SCENARIO:**

```
var template = "<%= test %>";
var compiledTemplate = _.template(template);
var result = compiledTemplate({test:1});
console.log(result);

//RESULT (both BROWSER and NODE JS):
//1
```

**EXAMPLE 2: COMPILE ERROR SCENARIO (an extra = before closing):**

```
var template = "<%= test =%>";
var compiledTemplate = _.template(template);
var result = compiledTemplate({test:1});
console.log(result);

//RESULT (both BROWSER and NODE JS):
//uncaughtException { [SyntaxError: Unexpected token )]
```

**EXAMPLE 3: EVALUATION ERROR SCENARIO (test is not defined):**

```
var template = "<%= test %>";
var compiledTemplate = _.template(template);
var result = compiledTemplate({no_test_defined:1});
console.log(result);

//RESULT (BROWSER):
//Uncaught ReferenceError: test is not defined
//RESULT (NODE JS):
//Node JS FREEZES - nothing happens, neither and error is thrown, neither the flow goes on

```
Anybody had ever get a similar behavior? Any hints for solution? I really need to catch the exception in a try/catch block...

Cheers!

Oscar

**Comment by SqrTT** [comment]
Hi @JOscarEduardo,
Examples works fine(as expected) for me.

```
$ node test.js 
undefined:6
((__t=( test ))==null?'':__t)+
        ^

ReferenceError: test is not defined
    at eval (eval at <anonymous> (/home/sqrtt/tmp/node_modules/underscore/underscore.js:1454:20), <anonymous>:6:9)
    at template (/home/sqrtt/tmp/node_modules/underscore/underscore.js:1461:21)
    at Object.<anonymous> (/home/sqrtt/tmp/test.js:5:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
sqrtt@laptop:/home/sqrtt/tmp
$ node --version
v6.4.0

```

Probably you are render template in `Promise` with ignoring fail case.

**Comment by akre54** [comment]
I can't reproduce. Make sure you're not inside a Promise as @SqrTT said.

**Comment by JOscarEduardo** [comment]
Hi!

Thanks, guys!!

After some troubleshoot I could finally found what was the problem.

When I run this inside Webstorm DEBUGGER, this behavior happens (Node JS FREEZES). When I run it in command line, i works as expected. I will search in Webstorm issues if hey have something.

Cheers!!!!

Oscar
