### ISSUE TITLE
Why using `slice.call(obj)` when `_.isArray(obj)` is true?

### ISSUE THREAD

**Issue by ahonn** [jashkenas/underscore#2574]
In `_.toArray`:

```
if (_.isArray(obj)) return slice.call(obj);
```
Why using `slice.call(obj)` when `_.isArray(obj)` is true?
Why not just return obj ? I don't understand, please tell me :)

**Comment by jridgewell** [comment]
It's to create a new instance of an array, so modifications do the original do not affect the returned value.

**Comment by ahonn** [comment]
Oh, I get it. Thank you for your response : )
