### ISSUE TITLE
Include underscore.js in the homepage

### ISSUE THREAD

**Issue by priomsrb** [jashkenas/underscore#2577]
Sometimes I want to quickly try out an underscore method. To do this I open up my JavaScript console on underscorejs.org. However, _ is not defined on the page.

Would be cool very convenient if I could use the JavaScript/Developer console to test out underscore.

**Comment by captbaritone** [comment]
`_` should be defined on the page. See the last three lines of `index.html`.

https://github.com/jashkenas/underscore/blob/master/index.html#L3245

**Comment by priomsrb** [comment]
Whoops you're right. My console was in the context of an addon for some reason. Thanks for the quick response.
