### ISSUE TITLE
https certificate issue 

### ISSUE THREAD

**Issue by pravinweb** [jashkenas/underscore#2578]
Hi Team,

Thanks for this great library

Could you please fix below issue for HTTPS
<img width="928" alt="f09c9524-654d-11e6-82d5-43fb36b1c8a2" src="https://cloud.githubusercontent.com/assets/14888335/17809648/be4ecc48-6635-11e6-9ead-e3f4cc871ae2.png">

Thanks,
Pravin

**Comment by captbaritone** [comment]
I'm not able to reproduce. Could you try again? If it persists, could you include a screen shot of the SSL certificate details?

**Comment by pravinweb** [comment]
Hi Captbaritone  

you will be able to see this issue when you hit URL - https://underscorejs.org/underscore-min.js. It gives "Your connection is not secure" page.

Screenshot is all ready added above

Note: 
Bug Reproduce Environment
Mac OSX El Capitan Chrome and Firefox

Thanks,
Pravin

**Comment by anthony-redFox** [comment]
![image](https://cloud.githubusercontent.com/assets/4757846/17853112/64fc0fe4-6873-11e6-85e3-14d118ee4347.png)

Is very strange that for  https://underscorejs.org get certificate for github.com

**Comment by Florian-R** [comment]
Seems to be isaacs/github#156

**Comment by jashkenas** [comment]
> Seems to be isaacs/github#156

Right. Nothing we can do about it for now? HTTPS isn't supported for Github Pages using custom domains just yet.
