### ISSUE TITLE
_ is not defined on  underscore doc

### ISSUE THREAD

**Issue by Galen-Yip** [jashkenas/underscore#2585]
![image](https://cloud.githubusercontent.com/assets/8219248/18268987/ce388906-7458-11e6-8fdb-ab78d6233ca4.png)

I think provide a _ is convenient for test functions.

**Comment by Florian-R** [comment]
Is it possible that for some reason the script is blocked on your network? It's already [included](https://github.com/jashkenas/underscore/blob/a9432276b90bd23d3022deb89ac1ba6b10ee7495/index.html#L3246) in the docs.

**Comment by Galen-Yip** [comment]
my mistake. i open dev console , it is not the 'top' as default
![image](https://cloud.githubusercontent.com/assets/8219248/18269629/85575a8e-745b-11e6-8b03-12312703203f.png)

**Comment by jdalton** [comment]
Related to [lodash.github.io/#46](https://github.com/lodash/lodash.github.io/issues/46).
