### ISSUE TITLE
There is a bug in  _.throttle function

### ISSUE THREAD

**Issue by hanzichi** [jashkenas/underscore#2589]
I use like below:

```javascript
function log() {
  console.log('hello world');
}
window.onscroll = _.throttle(log, 1000, {leading: false, trailing: false});
```

when scrolling the window for the first time, its behaviour is right, but when for the second time, it will immediately print `hello world` in the console, although we have set `leading` to `false`.

Thanks.

**Comment by hanzichi** [comment]
I'm sorry but nobody? I think it's a real issue

**Comment by akre54** [comment]
Why are both leading and trailing false? One of them should be true.

**Comment by hanzichi** [comment]
@akre54 thanks for your  replay. Maybe it's true, I have tried lodash, when used in this way, it does not trigger the callback function.
