### ISSUE TITLE
Versions after 1.6.0 cannot be used with Adobe Illustrator CC 2015.

### ISSUE THREAD

**Issue by ComingNine** [jashkenas/underscore#2590]
Versions after 1.6.0, for example, master, 1.8.3, 1.7.0, cannot be used with Adobe Illustrator CC 2015.
For example, when running inside Illustrator, the script with the include statement `#include "lib/underscore.1.8.3.js"` gives `"No matching closing brace found"`.

Furthermore, when running inside Illustrator, the script with the include statement `#include "lib/underscore.1.8.3-min.js"` makes Illustrator stop working immediately.

**Comment by captbaritone** [comment]
Since this is a pretty niche use case, and may be difficult or  impossible for others to reproduce (I don't have a license to Adobe Illustrator), we will probably need more specifics in order to understand what the problem is.

One approach would be to use Git bisect to identify the individual commit that caused Underscore to stop working in Illustrator.

https://git-scm.com/docs/git-bisect

**Comment by ComingNine** [comment]
Sorry that I do not know git-bisect well enough, and thus have to settle for 1.6.0 for now. It should be noted that a script containing only the include statement will trigger the error. Thank you for your time and efforts though !

**Comment by jdalton** [comment]
Stable [1.8.3](https://cdn.jsdelivr.net/underscorejs/1.8.3/underscore.js) or [Lodash v3](https://cdn.jsdelivr.net/lodash/3.10.1/lodash.js) works.

**Comment by ComingNine** [comment]
Dear jdalton, thank you very much for your efforts and time !

Indeed Lodash v3 works ! However, vanilla Underscore v1.8.3 does not work, as shown in the video attached. Can you help to comment ? :)

**Comment by jdalton** [comment]
@ComingNine The underscore.js on the master branch is not the stable release. I tested the stable release though (the one I linked to) and it does work.

**Comment by ComingNine** [comment]
@jdalton 
Thank you very much for your efforts to show your environment ! It then seems to related to Windows version of Adobe CC 2015 ( I just tried PhotoShop CC 2015 with the same error)... I will have to stick with Lodash v3.10.1 for now.
