### ISSUE TITLE
_.without doesn't include array properties

### ISSUE THREAD

**Issue by mikalmadsen** [jashkenas/underscore#2591]
When doing _(array).without(element), I expect the resulting array to be like the original array except that the given element is taken out.

However, properties set on the original array object are not copied over to the new one.

```
var arr = [1,2,3];
arr.prop = "foo";
arr.prop // => "foo"
var brr = _(arr).without(1);
brr.prop // => undefined
```

**Comment by akre54** [comment]
Right. Underscore's array functions work with numeric keys only.

Can you explain your use case? I've almost never seen a good reason to use an array this way.

**Comment by jashkenas** [comment]
Yep, Underscore assumes that you're using arrays normally — that's a feature, not a bug, and I think something that has been discussed in previous tickets.

**Comment by mikalmadsen** [comment]
I can easily build around it. (It's a property describing the elements in the array, so to my mind it was more elegant to keep it as a property of the array.)

I expect there would be a performance hit to changing the behavior, so it's fine as it is.

Consider adding an additional note at the start of the documentation on array functions that copies of arrays will not include properties set on them.

**Comment by jashkenas** [comment]
> I expect there would be a performance hit to changing the behavior, so it's fine as it is.

Quite so.

> Consider adding an additional note at the start of the documentation on array functions that copies of arrays will not include properties set on them.

Sounds good.

**Comment by mikalmadsen** [comment]
Interestingly, _.omit will find and remove a property set on an array, keeping other properties set on it, but _.clone won't include properties. (Maybe just add some note that Underscore functions don't consider properties set on arrays so behaviors might be unexpected.)
