### ISSUE TITLE
Sorting an array of arrays containing numbers

### ISSUE THREAD

**Issue by sohocoke** [jashkenas/underscore#2593]
` _.sortBy( [ 4, 15 ] )` returns `[4, 15]`, but ` _.sortBy( [ [4], [15] ] )` returns `[[15], [4]]`. 

I tried to find a clear and concise explanation on why, but couldn’t find any. Is this a bug or missing documentation? 

I’m finding it a little incredible for such a battle-hardened library such as Underscores to have bugs, so hoping the experts could enlighten me so I can contribute some docs.

**Comment by Florian-R** [comment]
This is because

```js 
[4] < [15]
// false
```

In this case, you want to supply an [iteratee](http://underscorejs.org/#iteratee)

```js
_.sortBy( [[15], [4]], _.first )
// [[4], [15]]
```

**Comment by sohocoke** [comment]
@Florian-R @jashkenas Many thanks for the clarification.
