### ISSUE TITLE
_.isFunction hack for certain browsers

### ISSUE THREAD

**Issue by ayqy** [jashkenas/underscore#2594]
Is `|| false` necessary?

    // Optimize `isFunction` if appropriate. Work around some typeof bugs in old v8,
    // IE 11 (#1621), Safari 8 (#1929), and PhantomJS (#2236).
    var nodelist = root.document && root.document.childNodes;
    if (typeof /./ != 'function' && typeof Int8Array != 'object' && typeof nodelist != 'function') {
      _.isFunction = function(obj) {
        //??? Is `|| false` necessary?
        return typeof obj == 'function' || false;
      };
    }

**Comment by Florian-R** [comment]
See the blame, it leads to https://github.com/jashkenas/underscore/issues/1621

**Comment by ayqy** [comment]
@Florian-R Thanks for your attention, an age-old funny issue (`typeof` DOM Element results `'function'` sometimes on IE 8 & 11)

It is necessary, please close this.
