### ISSUE TITLE
a bug in _.after function?

### ISSUE THREAD

**Issue by hanzichi** [jashkenas/underscore#2607]
I see the [docs](http://underscorejs.org/#after)

```
Creates a version of the function that will only be run after first being called count times.
```

but it seem not behave like that:

```javascript
function print() {
  console.log('hello world');
}

var renderNotes = _.after(2, print);

renderNotes();
renderNotes();  // hello world
renderNotes();  // hello world
renderNotes();  // hello world
```

not run after **first** being called count times, it seems you should always make sure that you should  call *renderNotes* with a certain times?

**Comment by hanzichi** [comment]
I think it's ok in most scenes, but think for this case, I have 100 API, but random 10 is ok, I will go for 100 asynchronous requests, but when 10 is reached, I will do the func

**Comment by captbaritone** [comment]
I think this might be a bug in our documentation. The comment before this function in the code reads: 

>  // Returns a function that will only be executed on and after the Nth call.

Would you like to submit a pull request to improve the docs?

**Comment by hanzichi** [comment]
@captbaritone well, my pleasure.
