### ISSUE TITLE
Discussion: Should Underscore support string syntax for deep property access?

### ISSUE THREAD

**Issue by captbaritone** [jashkenas/underscore#2609]
With #2494 Underscore functions that previously accepted a property name string, can now also accept an array representing a list of deeply nested property names.

For example:

    var postAuthorIds = _.pluck(posts, ['author', 'id']);

A possible additional layer of syntactic sugar would be to allow users to pass a `.` delimited string to more tersely express the same idea:

    var postAuthorIds = _.pluck(posts, 'author.id');

**The goal of this issue is to determine if Underscore should support deep property access via a string syntax.**

## Pros

* Cleaner (less noisy)
* Proven managable/successful/popular by Lodash
* Compatible with Lodash
* Can be used in places where arrays cannot (like keys of a `_.matcher` object).
* Prefered over the array syntax by devs. (According to @jdalton's [Twitter Poll]( https://twitter.com/jdalton/status/718165294678552576))

## Cons

* Could be seen as overly [magical](https://en.wikipedia.org/wiki/Magic_(programming)). See #2268 for a discussion of this concern.
* Can be ambiguous in the case of a key containing a literal `.` character. Applications that use such keys may have a hard time upgrading. Users will have to know to fallback to the array syntax in this case.
* Does not work well with dynamic keys. Users will have to know to fallback to the array syntax in this case as well.

Feel free to voice your support/objections on adding this syntax with a 👍  / 👎  on this issue. Please save the comments for raising new pros/cons or discussing the various tradeoffs.

**Comment by jashkenas** [comment]
> Should Underscore support string syntax for deep property access?

If we're going to support deep name access via array paths, then yes, we should also take string shorthand.

**Comment by jridgewell** [comment]
I'm fine with it, as long as we don't go off into [hell](https://github.com/lodash/lodash/blob/master/lodash.js#L141) of abstract `[]` [pattern matching](https://github.com/lodash/lodash/blob/master/lodash.js#L6701-L6706). Simple `a.0.b.c` => `['a', '0', 'b', 'c']`.

**Comment by bjmiller** [comment]
I don't think it would be hellish.  We should allow one level of bracket, for things that you'd expect like array indices and keys with dashes and the like.

Consider throwing if there are brackets inside brackets.. Lodash does all of this with a regex, fwiw.  We could do it that way, or with a single pass.

**Comment by jashkenas** [comment]
> I don't think it would be hellish. We should allow one level of bracket

What would be the downside of only supporting `.` paths, and not `[]` paths?

**Comment by bjmiller** [comment]
I picture a lot of attempts at using `a[0].foo`, which wouldn't go as expected.  That's the main thing.

**Comment by captbaritone** [comment]
It sounds like we have enough of a concensus here to move forward with the string syntax.
