### ISSUE TITLE
Filtering and reducing JSON 

### ISSUE THREAD

**Issue by nandakumar8** [jashkenas/underscore#2614]
Hi,

I have a use case where i need to use underscore.js to filter a JSON. For example

{"test":{
{ key: 1,country:USA,product:A,price:200}
{key: 1,country:USA,product:B,price:200}
{key: 1,country:UK,product:B,price:300}
}
}

I need to get the output as follows when i filter USA 

{"test":{
{ key: 1,country:USA,price:400}
}
}

and when i filter for product B

{"test":{
{ key: 1,product:B,price:500}
}
}

**Comment by jridgewell** [comment]
These kinds of questions are best suited for [StackOverflow](http://stackoverflow.com/questions/tagged/underscore.js).
