### ISSUE TITLE
Create proper documentation, atleast for settings 

### ISSUE THREAD

**Issue by igniteajaysuwalka** [jashkenas/underscore#2616]
Like I had to go through code to check whether there is something like 'allowRepeat' available or not! Thanks to you guys that It was available but the problem is it wasn't mentioned in documentation anywhere

**Comment by akre54** [comment]
I"m not sure what you're referring to. `allowRepeat` isn't in our code.

**Comment by igniteajaysuwalka** [comment]
allowRepeat is basically a property in your plugin which allows same tag to
appear more than once in so your documentation has no mention of the
allowRepeat.




Regards,

[image: Aurea] <http://www.aurea.com/>

*Ajay suwalka* | C# Software Engineer
ajay.suwalka@aurea.com | + <+55%2021%2097224-8822>91 7208728720
*Skype:* ajaysuwalka

www.aurea.com
