### ISSUE TITLE
The result of method '_.has'  when the path params is an array.

### ISSUE THREAD

**Issue by suyuTech** [jashkenas/underscore#2618]
I noticed the implement of method _.has, and when I try to use it like below:

_.has({a:1,b:2}, ['a'])      // evaluate to be true

_.has({a:1,b:2}, ['a','b'])  // evaluate to be false

Did I use the method correctly? Thank you!

**Comment by Florian-R** [comment]
In latest published version, the second parameter of `_.has` is not intended to be an array. The fact that your first example works is just a side effect of the implementation.

Basically, `_.has` defer to `hasOwnProperty`, which call `toString` on the property name, so : 

```js
_.has({a:1,b:2}, ['a']) === _.has({a:1,b:2}, 'a') //Yeah JS
```

This has changed since #2494 (unreleased), where you could do 

```js
_.has({a: {b: 'foo '}}, ['a', 'b']) //true
```

**Comment by captbaritone** [comment]
While this is not a bug, thanks for reporting it all the same. It's good for us to see how this change might affect people.

`_.has` has not previously officially supported the use of an array as the second argument. As @Florian-R pointed out, the behavior you were experiencing was as a result of the fact that JavaScript will cast a value to a string when you attempt to use it as an object key.

    ['a'].toString()
    // => 'a'

    ['a', 'b'].toString()
    // => 'a,b'

So, to illuminate your second example, previously:

    _.has({'a,b':1}, ['a','b']) // evaluate to be true

While that was true, it was probably not what you were trying to do.

To answer your question "Did I use the method correctly?", no. Passing an array as the second argument to `_.has` did not have a defined behavior, and the fact that you were getting something resembling a reasonable result was just a quirk of how JavaScript works.

**Comment by suyuTech** [comment]
@Florian-R  Oh I see, thank you very much!
