### ISSUE TITLE
_.first(arr, n) always returns the first element of the array, and not 'n' elements as expected

### ISSUE THREAD

**Issue by david-bulte** [jashkenas/underscore#2621]
For example, I get 5 iso [5, 4, 3] when I do

`_.first([5, 4, 3, 2, 1], 3);
`

Version: 1.8.3
Browser: Chrome (not tested on other browsers)

**Comment by akre54** [comment]
I can't reproduce this, and I'd be shocked if it wasn't something in your code. If you can demonstrate using a JSFiddle we can reopen.

**Comment by david-bulte** [comment]
Ok, sorry for not looking any further - in hindsight this would indeed seem very unlikely. 

Somehow webpack is bundling both lodash and underscore in my project, and apparently underscore's and lodash's first() function behave differently (as explained here: https://github.com/lodash/lodash/issues/946)
