### ISSUE TITLE
_.flatten documentation reverses effect of "shallow" argument

### ISSUE THREAD

**Issue by SebWiers** [jashkenas/underscore#2626]
Re http://underscorejs.org/#flatten

The documentation says "Flattens a nested array (the nesting can be to any depth). If you pass shallow, the array will only be flattened a single level."

It gives the following examples:
_.flatten([1, [2], [3, [[4]]]]);
=> [1, 2, 3, 4];

_.flatten([1, [2], [3, [[4]]]], true);
=> [1, 2, 3, [[4]]];

My execution (_.VERSION = "3.10.1") shows this is incorrect.  The correction would be:
Flattens a nested array (the nesting can be to any depth). If you pass shallow, the array will be flattened a to single level, otherwise nesting beyond one level is preserved."

_.flatten([1, [2], [3, [[4]]]]);
=>  [1, 2, 3, [[4]]];

_.flatten([1, [2], [3, [[4]]]], true);
=> [1, 2, 3, 4];

**Comment by captbaritone** [comment]
Underscore 3.10.1 does not exist (yet!). Is it possible that you are actually using Lodash?
