### ISSUE TITLE
Feature Request: Clear function instead of loop and clone

### ISSUE THREAD

**Issue by aseroj** [jashkenas/underscore#2628]
Yesterday i came across this issue and i wanted to clear my collection and the only way around is to loop through the clone of my collection and delete objects from the original one.

```
var self = this;
_.each(_.clone(this.channels.models), function(item) { self.channels.remove(item); });
```

I am suggesting that it can be a standalone function. 

Thanks in advance and keep `rockin`.

**Comment by captbaritone** [comment]
@aseroj I think this issue should be filed in the [Backbone](https://github.com/jashkenas/backbone) repository.

Good luck!
