### ISSUE TITLE
_.eq redundant comparison when both null

### ISSUE THREAD

**Issue by ahonn** [jashkenas/underscore#2629]
in `_.eq` function:
```
 eq = function(a, b, aStack, bStack) {
    // Identical objects are equal. `0 === -0`, but they aren't identical.
    // See the [Harmony `egal` proposal](http://wiki.ecmascript.org/doku.php?id=harmony:egal).
    if (a === b) return a !== 0 || 1 / a === 1 / b;
    // A strict comparison is necessary because `null == undefined`.
    if (a == null || b == null) return a === b;
   ......
}
```

a === b is true when a = null and b = null, so the function will return true.
and then, if `(a == null || b == null)` is true, return a === b. 
It would never be true, why not directly return false:
```
if (a == null || b == null) return false;
```

I checked the #2180 and #2179 , but I still don't understand why not directly return false?

**Comment by jridgewell** [comment]
Yah, looks like we could. Want to open a PR?

**Comment by ahonn** [comment]
Nice, I have opened a PR #2630

**Comment by demoneaux** [comment]
@ahonn since we are using `a == null || b == null`, `a` and `b` could be `null` or `undefined` due to `==` not being a strict equal comparison. Hence `a === b` is needed to ensure that `a` and `b` are not the same, if one is `null` and the other is `undefined`.

**Comment by jridgewell** [comment]
Yes, but we've already done a `a === b` check above it. So, if either `a` or `b` is `null` or `undefined`, we know that both aren't.

**Comment by demoneaux** [comment]
> Yes, but we've already done a a === b check above it

Ah, I completely missed that :| Thanks @jridgewell!

**Comment by ahonn** [comment]
When running `if (a == null || b == null) ...`, `a === b` would never be true.
Because if `a === b` is true, will return `a !== 0 || 1 / a === 1 / b`. So, That must be false.
