### ISSUE TITLE
can not require underscore@1.8.3 in weixin app development tool

### ISSUE THREAD

**Issue by mdsb100** [jashkenas/underscore#2631]
Please release 1.9.0 as soon as possible
![image](https://cloud.githubusercontent.com/assets/2350193/20638642/e036ba8c-b3e7-11e6-8a17-9cc62a93c801.png)

**Comment by captbaritone** [comment]
@mdsb100 Are you saying that this bug is resolved in the current master branch?

**Comment by mdsb100** [comment]
@captbaritone I am not sure, let me test tomorrow.
