### ISSUE TITLE
TypeError: sample.slice is not a function

### ISSUE THREAD

**Issue by waitingcheung** [jashkenas/underscore#2636]
I am getting a TypeError when trying to shuffle a list.

```
TypeError: sample.slice is not a function
    at Function._.sample (/path/underscore.js:406:19)
    at Function._.shuffle (/path/underscore.js:384:14)
```
Here is a simple test case to reproduce that

```js
var tricks = [
  {length: '5'},
  {length: {valueOf: _.constant(-1)}},
  {length: Math.pow(2, 53) + 1},
  {length: Math.pow(2, 53)},
  {length: null},
  {length: -2},
  {length: new Number(15)},
  {length: 2}
];

_.each(tricks, (function(trick) {
  _.shuffle(trick);
}));
```

It fails to shuffle the last element ``{length: 2}`` and it seems that the function [isArrayLike()](https://github.com/jashkenas/underscore/blob/master/underscore.js#L164) returns false for ``{length: -2}`` but returns true for ``{length: 2}``.

**Comment by akre54** [comment]
Right. Using `length` for anything but iterable keys length in javascript is a footgun. There are many issues in the underscore repo about this.

**Comment by waitingcheung** [comment]
This seems to be a valid usage to me, since this is how the [test case](https://github.com/jashkenas/underscore/blob/master/test/collections.js#L70) constructs the inputs, except that the last element of my tricks array can make the test case fails.
