### ISSUE TITLE
647 days and 398 commits since the last release

### ISSUE THREAD

**Issue by navels** [jashkenas/underscore#2645]
Not a huge deal as we're just going to update our bower.json to point to a commit hash, but still . . .

**Comment by captbaritone** [comment]
Thanks for bringing this up. I think we're far overdue for a release. I'll take some time soon to draft up a list of changes and what outstanding work we have to do before we can ship a new version. When I have that ready I'll create an issue with my notes. Watch this space.

**Comment by navels** [comment]
Any updates?
