### ISSUE TITLE
why .isJSON is out of scope?

### ISSUE THREAD

**Issue by antoine-pous** [jashkenas/underscore#2648]
Hi !

I would like know why `.isJSON()` is out of scope ?

Related to #2592 and #2639.

Thank you !

**Comment by akre54** [comment]
I can't speak for the rest of the team but I'll take a crack. Underscore is meant to be a library of small composable general-purpose functional utilities. Checking whether a string is JSON is too narrow of a use case for us to support in the main library and doesn't fit with our mission. It's much better left for your own code or for a specialized toolkit.

In the future please don't open a separate issue, just comment on the first one or ask on StackOverflow. Thanks!
