### ISSUE TITLE
Deeply validation of empty objects

### ISSUE THREAD

**Issue by ftrianakast** [jashkenas/underscore#2653]
Hi everyone

Seems to me that a method for validating if an object is deeply empty will be very helpful in some cases. So for example given an object:

`var a = {"p1": {   "p2":  {  "p3": []  } }}`  

if I apply `_.isEmptyDeep(a)` the method would return true. What do you think?

**Comment by akre54** [comment]
This is too special-cased for Underscore but would make a great mixin for your copy.

In the future please open just an issue or a pull. No need to open both.
