### ISSUE TITLE
_.map on undefined/null returns an empty array

### ISSUE THREAD

**Issue by wizzy25** [jashkenas/underscore#2662]
Current behaviour of ```_.map```: 
```js
const foo = _.map(undefined, x => x) // []
const bar = _.map(null, x => x) // []
``` 
Is this normal behaviour? I would expect calling _.map on undefined/null to also return undefined/null.

**Comment by jashkenas** [comment]
I believe that's something that was requested and settled in the past — there's probably a ticket lying around deep in the pile somewhere describing exactly why. Good luck finding it! ;)
