### ISSUE TITLE
it has a really bad performance after added detecting cyclic structures in deepEq 

### ISSUE THREAD

**Issue by Gcaufy** [jashkenas/underscore#2665]
https://github.com/jashkenas/underscore/blob/master/underscore.js#L1249

https://jsperf.com/deep-compare-vs-json-stringify

**Comment by Gcaufy** [comment]
fixed typo

**Comment by akre54** [comment]
... But JSON.stringify doesn't even deal with circular data structures. This is an invalid comparison.

```js
> const a = {}
{}
> a.a = a
{ a: [Circular] }
> JSON.stringify(a)
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at repl:1:6
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
```

**Comment by Gcaufy** [comment]
I know JSON.stringify doesn't work with circular data structures.
but now, underscore make every deep compare performance 200 times slower, because it supports circular data structures?

can we make it optional?  I don't want isEqual is 200 times slower than JSON.stringify.

**Comment by akre54** [comment]
I think we don't want to muddy the API or code by adding too many options. It shouldn't be a difficult thing to write yourself if you really need it.

**Comment by Gcaufy** [comment]
it's fine if you don't mind the low performance issue.
