### ISSUE TITLE
Uncaught TypeError: _.where is not a function

### ISSUE THREAD

**Issue by abizden** [jashkenas/underscore#2667]
Hello there,

I imported Underscore in the following way.

Import _ from 'underscore'

But when calling the .where method I get a Uncaught TypeError: _.where is not a function error.

Example code:

Var people = [
     {Name: "Tom", age: 21},
     {Name: "Tom", age: 22},
     {Name: "Tom", age: 22}
];

Var found = _.where (people, {age: 22})

**Comment by abizden** [comment]
Version: "underscore": "^1.8.3"

**Comment by akre54** [comment]
Please use StackOverflow or the gitter channel for debugging help.
