### ISSUE TITLE
Enhance _.template to support unescaping values before escaping when escape delimiters are encountered

### ISSUE THREAD

**Issue by platinumazure** [jashkenas/underscore#2668]
My workplace is implementing an XSS sanitizer on our server-side, but I know the reality of software development and so I know that it won't always be consistently rolled out. In addition, if our JS or templates are reused in a different setup that doesn't have an XSS sanitizer on the server side, we should continue to escape string values in our templates.

In order to work flexibly with HTML-encoded and non-HTML-encoded text, I would like to augment `_.template` so that it will unescape and then escape text between the escape delimiters. I assume this would be best handled as a `_.templateSettings` option to allow people to opt in rather than cause a breaking change.

Example test cases:

```js
const escapeTemplate = _.template("<%- value %>");

// Would not be impacted:
escapeTemplate("<b>Hello!</b>");   // "&lt;b&gt;Hello!&lt;/b&gt;"

// Would be impacted to avoid double encoding:
_.templateSettings.unescapeBeforeEscape = true;   // Open to bikeshedding

escapeTemplate("&lt;b&gt;Hello!&lt;/b&gt;");   // "&lt;b&gt;Hello!&lt;/b&gt;"
// Previous result: &amp;lt;b&amp;gt;Hello!&amp;lt;/b&amp;gt;
```

Would a pull request for this be accepted? I'm just asking before starting work on it-- happy to contribute but don't want to waste time on something that might not be desirable.

**Comment by jashkenas** [comment]
> Would a pull request for this be accepted?

I'm afraid not.

**Comment by platinumazure** [comment]
@jashkenas Any particular reason why not, especially given that it would be implemented as an opt-in option?

**Comment by jashkenas** [comment]
Not to be curt, but -- Because you should know the values that you're passing into `_.template`. 

Unescaping before escaping is hacky, and unreliable. You can do it for your particular use case, but it absolutely should not be something included in Underscore.
