### ISSUE TITLE
partitionBy a predicate of two?

### ISSUE THREAD

**Issue by emilefokkema** [jashkenas/underscore#2669]
I sometimes want to partition a collection based on whether two of its elements belong in the same group. For example: to partition the array [1, 2, 3, 4, 100, 101, 102] into groups based on whether two elements are 1 removed from each other, which would result in [1,2,3,4] and [100,101,102]. (Even though 100 and 102 are not 1 removed from each other, they are both in the same group as 101.)

In other words, what I would love is a function that accepts
 - a collection, and
 - a predicate of two that, if true, means that the two elements in question belong to the same group,

and returns all the groups.

'Partition' would then be a specific version of this that, when called with some predicate 'p', would call this function with predicate (x,y) => p(x) == p(y).

Any chance?

**Comment by jashkenas** [comment]
Cool function, but too specific for Underscore. Feel free to mix it in yourself.
