### ISSUE TITLE
Dead link in index.html

### ISSUE THREAD

**Issue by kamoroso94** [jashkenas/underscore#2689]
The link under the [`_.has`](http://underscorejs.org/#has) entry, "[overridden accidentally](http://www.devthought.com/2012/01/18/an-object-is-not-a-hash/)", is broken.  Maybe change it to link to http://www.pixelstech.net/article/1326986170-An-Object-is-not-a-Hash?

**Comment by MiltonAkash** [comment]
I have changed this. Merge this
https://github.com/jashkenas/underscore/pull/2704

**Comment by nandy-andy** [comment]
Looks like merged and fixed :+1:
