### ISSUE TITLE
isEqual incorrectly compares DataView objects

### ISSUE THREAD

**Issue by jasongrout** [jashkenas/underscore#2692]
isEqual returns true for the following comparison, when it should return false:

```javascript
_.isEqual(new DataView((new Uint8Array([1,2])).buffer), new DataView((new Uint8Array([5,6,10])).buffer))
```

This is in underscore 1.8.3.

**Comment by jasongrout** [comment]
It also appears to handle ArrayBuffers incorrectly:

```javascript
_.isEqual((new Uint8Array([1,2])).buffer, (new Uint8Array([5,6,10])).buffer)
```

**Comment by jasongrout** [comment]
(lodash 4.17.4 correctly returns false for each of the above cases)

**Comment by jasongrout** [comment]
@jashkenas - What is the possibility of getting a 1.8.4 released that has a fix for this if we submit a PR with a fix and tests? If we do submit a PR, should we submit it against 1.8.3?

**Comment by jashkenas** [comment]
@jasongrout PR's should be submitted against master, and we can certainly merge and release a fix.

**Comment by jasongrout** [comment]
@maartenbreddels and I looked into this and he submitted #2693. We can fix that PR, if you want. This problem cropped up in using backbone, and in the meantime, I've overridden backbone's set function to use lodash for the isEqual function (https://github.com/jupyter-widgets/ipywidgets/blob/ba4a4077ae3623eb83f42265a8c769d1cdb36ed7/packages/base/src/backbone-patch.ts)

**Comment by jasongrout** [comment]
(to be clear, @jashkenas, let us know if you want @maartenbreddels and I to iterate on #2693 - the response there wasn't very encouraging, so we aren't sure if you want to take it on or if you want us to pursue it further.)

**Comment by jashkenas** [comment]
Patching it for now in your copy of Backbone is a fine way to go — and you're welcome to iterate on #2693, or to submit a different PR. 

The ticket was closed because just nakedly trying to convert the objects into DataViews and silently catching any error seems like very much the wrong way to go. What if `a` and `b` are objects with `.buffer` properties that happen to be ArrayBuffers? Etc.

**Comment by maartenbreddels** [comment]
Ok, that would have been a more appropriate reply. The other option would be to whitelist all (now) known typed arrays.
