### ISSUE TITLE
_.groupBy does not work with a property that it is an object

### ISSUE THREAD

**Issue by malloc32** [jashkenas/underscore#2697]
_.groupBy does not work with a property that it is an object

Example code:

var event0 ={data:"0"};
var event1 ={data:"1"};

var list = [
{key:event0,result:{providerId:0,calendarId:"00",eventId:"000"}},
{key:event0,result:{providerId:1,calendarId:"11",eventId:"111"}},
{key:event1,result:{providerId:1,calendarId:"22",eventId:"222"}}
]

var out = _.groupBy(list,'key');

out is an ungrouped array :(

Thank you

**Comment by forguta** [comment]
`var event0 ={data:"0"};
var event1 ={data:"1"};

var list = [
{
key:event0,
result:{providerId:0,calendarId:"00",eventId:"000"}
},
{key:event0,result:{providerId:1,calendarId:"11",eventId:"111"}},
{key:event1,result:{providerId:1,calendarId:"22",eventId:"222"}}
]

var out = _.groupBy(list,function (value) {
                return value.key.data;
            });
console.log(out);`

[jsfiddle](https://jsfiddle.net/forguta/ye7dopuu/)
try this code.

**Comment by malloc32** [comment]
Thank you very much, but really event has a lot of properties, none of then are id, I need that it can group by "objects",I think this should be the natural behavior of the method groupBy...
