### ISSUE TITLE
throttle triggers trailing call when invoked repeatedly flaky in CITGM

### ISSUE THREAD

**Issue by MylesBorins** [jashkenas/underscore#2698]
✖ throttle triggers trailing call when invoked repeatedly
     failed, expected argument to be truthy, was: false
     false != true

This is being on and off flaky on a variety of platforms including ubuntu + debian + osx.

Any idea what's going on?

specifically on Node v8.x

**Comment by MylesBorins** [comment]
Just a quick ping that we are still seeing this quite a bit.

We are likely going to turn off CITGM for underscore if we cannot resolve this flaky test

**Comment by BridgeAR** [comment]
This is still an issue.
