### ISSUE TITLE
MAX_ARRAY_INDEX  =  Math.pow(2, 53) - 1;   is  a worry set  in line 163

### ISSUE THREAD

**Issue by lilililee** [jashkenas/underscore#2699]
from this property name we may consider a array max lenth is Math.pow(2, 53) - 1, but I have do a simple test ,like this:   var arr = [];  arr.length = Math.pow(2, 53) -1 ;   then running in lastest chrome browser, the console is  print a error: Uncaught RangeError: Invalid array length,  after searching related infomation and test,  I found  Math.pow(2, 32) - 1  is the critical value, this should be corrected, If I understand it wrong also please point out.

**Comment by andresroberto** [comment]
Hi. It was previously discussed here -> https://github.com/jashkenas/underscore/issues/2313
