### ISSUE TITLE
npm package(1.8.3) is not the latest source code.

### ISSUE THREAD

**Issue by sky0014** [jashkenas/underscore#2701]
Although version is both 1.8.3, npm missing _.throttle.cancel method.

**Comment by paulfalgout** [comment]
There hasn't been a release since 1.8.3, but master is always latest.  This is expected

**Comment by sky0014** [comment]
Ah, I see, that's a long time 😄

**Comment by andresroberto** [comment]
Do you have plans on doing a new release any time soon?

**Comment by seanCodes** [comment]
Bump. @jashkenas, when could we expect a new release? We’re coming up on the 3 year anniversary of 1.8.3 in a week here... 😅

**Comment by RobertLowe** [comment]
@jashkenas bump, the internet still loves underscore, 2011 -> 2015 npm had love, 2011->2018 community loves underscore.

Most stable library ever. 👍 

Thanks, so many times over.

**Comment by jashkenas** [comment]
Let's do it!

**Comment by RobertLowe** [comment]
Awesome!!
`<waits excitedly>`
😄

**Comment by jashkenas** [comment]
Boom, 1.9.0:

http://underscorejs.org/#changelog
https://github.com/jashkenas/underscore/compare/1.8.3...1.9.0

Let me know if you run into any problems ... or if there's anything important that I've forgotten to add to the changelog.
