### ISSUE TITLE
_.uniq iteratee function, when run on sorted array, can return extra value sometimes 

### ISSUE THREAD

**Issue by darren-a** [jashkenas/underscore#2705]
My understanding is that iteratee in these examples will transform the array to true or false values, get the two unique values, and then return the original values that were the cause of the two unique transformations. 

So in Ex 1 below, the transformed array would be: [false, false, false, true, false, false], so the two unique values would be 1 (false) and 3 (true). For sorted arrays like this, when the 'odd man out' value is separated by at least one other number from the first of the 'commoners', and has some different numbers following it, the result includes the following 'opposite' value as well (in this case, 4).

(tested 10/24/17 in jsbin with "underscore" library added - no version number given)

```

var numbers = [1, 2, 2, 3, 4, 4];

var iteratee = function(value) { return value === 3; };
var un = _.uniq(numbers, true, iteratee); // [1, 3, 4]    <-------- Ex 1
var un = _.uniq(numbers, false, iteratee); // [1, 3]

var iteratee = function(value) { return value === 1; };
var un = _.uniq(numbers, true, iteratee); // [1, 2]  <--- is ok
var un = _.uniq(numbers, false, iteratee); // [1, 2]

var iteratee = function(value) { return value === 4; };
var un = _.uniq(numbers, true, iteratee); // [1, 4]  <--- is ok
var un = _.uniq(numbers, false, iteratee); // [1, 4]

```

**Comment by darren-a** [comment]
As a point of reference results for lodash 4.x (tested with jsbin today; slightly different function, does not care about ordering) returns following:

```
var numbers = [1, 2, 2, 3, 4, 4];

var iteratee = function(value) { return value === 3; };
var un = _.uniqBy(numbers, iteratee); // [1, 3]

//var iteratee = function(value) { return value === 1; };
//var un = _.uniqBy(numbers, iteratee); // [1, 2]

//var iteratee = function(value) { return value === 4; };
//var un = _.uniqBy(numbers, iteratee); // [1, 4]
```

**Comment by darren-a** [comment]
I see why this is happening. In my "transform" there is no 1 to 1 mapping from x to f(x), as it's actually a test and not a transform. Therefore the iSorted efficiency gain won't yield expected results; or to put it another way, I shouldn't have fed _.uniq with a non-transforming iteratee.

**Comment by Lake1GitHub** [comment]
if isSorted is true, 'computed' just compare with 'seen'.in Ex1,numbers is not sorted actually.

`computed = iteratee ? iteratee(value, i, array) : value;`

numbers = [1, 2, 2, 4, 4, 3] or numbers = [3, 1, 2, 2, 4, 4]  is sorted
because the array is [false, false, false, false, false, true] or [true, false, false, false, false, false] actually

**Comment by darren-a** [comment]
Ex1 does use a sorted array, prior to applying any kind of transform. I assume the caller of uniq can only really specify the 'sortedness' of the collection prior to applying a transform.

It seems that, if given a sorted collection, the transform that uniq applies cannot impose its own ordering, ie. 'un-order' the collection, since that could render an inaccurate result.

**Comment by jashkenas** [comment]
I'm afraid this is behaving as expected: You passed `isSorted=true`, but the values you were trying to compare were `[false, false, false, true, false, false]` ... which isn't sorted. This will break every time.
