### ISSUE TITLE
Include flattened array test case for allocation of empty array of size N

### ISSUE THREAD

**Issue by alanzheng88** [jashkenas/underscore#2708]
As a minor enhancement, it would be good to include a test case for flattening an empty array of size N `assert.strictEqual(_.flatten([new Array(10)]).length, 10, 'can flatten an empty array of size N');`
to make debugging a bit easier when
the test case for `assert.strictEqual(_.flatten([new Array(1000000), _.range(56000), 5, 1, 3]).length, 1056003, 'can handle massive arrays')` fails

**Comment by jashkenas** [comment]
Sounds fine — feel free to send a PR!
