### ISSUE TITLE
about isFunction

### ISSUE THREAD

**Issue by zhangenming** [jashkenas/underscore#2712]
`if (typeof /./ != 'function' && typeof Int8Array != 'object') {
    _.isFunction = function(obj) {
      return typeof obj == 'function' || false;
    };
  }`
if the expression
(typeof /./ != 'function' && typeof Int8Array != 'object')
result is false, the isFunciton will be undefined
there will be error when some else function call isFunction?
thanks
[english bad, sorry]

**Comment by akre54** [comment]
This is, if I recall correctly, a bugfix for Safari.

In the future please ask questions to StackOverflow or the mailing list. Thanks!
