### ISSUE TITLE
Unescape not used globally

### ISSUE THREAD

**Issue by vinayshah** [jashkenas/underscore#2727]
[single Quote escape issue](https://github.com/jashkenas/underscore/blob/e4743ab712b8ab42ad4ccb48b155034d02394e4d/underscore.js#L1341)

Why is the escape and escaping of "'" not used globally? As other language escape "'" to `&#039;` where underscore js to `&#x27;`

**Comment by jashkenas** [comment]
`27` is `39` in hexadecimal.
