### ISSUE TITLE
undefined as an argument of argCount in optimizeCb (version 1.8.3)

### ISSUE THREAD

**Issue by xlshen** [jashkenas/underscore#2731]
**undefined as an argument of argCount**

In version 1.8.2: `switch(argCount == null ? 3 : argCount){...} `
If the argCount is undefined, such as` _.each()`, will work fine because of `undefined == null`.
But if merged in version 1.8.3, the _.each() will go to the default condition:
`return function() {
            return func.apply(context, arguments);
        };`
Because the `switch()` use the `===` to test and in the inner of Underscore, the case of 3 will never invoked.

[[optimizeCb] Combine null and 3 as multi-case for argCount switch statement #2613](https://github.com/jashkenas/underscore/pull/2613)

**Comment by captbaritone** [comment]
I don't see where it's possible for `optimizeCb` to get passed `null`. Can you give an example of using the external API that will cause `optmizeCb` to get passed `null`?
