### ISSUE TITLE
proposal for new method Object to Collection

### ISSUE THREAD

**Issue by stefanocudini** [jashkenas/underscore#2737]
hi,
I would like to implement a new method to create a collection(arrays of objects) from the properties of an object, here the use case is explained:
https://stackoverflow.com/questions/49611332/underscorejs-object-to-collection

the logic is very simple and very often I found myself having to solve this problem.
Now it seems to me that there is not a single method that implements this algorithm

I want to gather some opinions before creating a PR from my fork

thank you all

**Comment by jashkenas** [comment]
I don't think that we would merge that function, but you're welcome to `_.mixin` it yourself.
