### ISSUE TITLE
Possible regression on bindAll in 1.9.0

### ISSUE THREAD

**Issue by ErikLarsson82** [jashkenas/underscore#2746]
Hello,

We noticed something in our codebase while upgrading from 1.8 to 1.9 today.
In combination with **Ramdas (0.25.0) curry** function, we now had a different behaviour than before.

Behaviour using underscore 1.8:
```
function test(a,b) {}
_.bindAll(this, "test")
var curriedTest = R.curry(test)
curriedTest("a") // ->partially applied function
```

Behaviour using underscore 1.9:
```
function test(a,b) {}
_.bindAll(this, "test")
var curriedTest = R.curry(test)
curriedTest("a") // ->undefined
```

A solution is to skip bindAll completely and bind separately:
```
function test(a,b) {}
var curriedTest = R.curry(test.bind(this))
curriedTest("a") //->partially applied function again
```

I fully understand that debugging underscore in _combination_ with other libs/frameworks is potentially out of scope, but I wanted to post this to make sure no one else pulls their hair trying to find it - for us the fix was trivial.

**Comment by jashkenas** [comment]
The diff in the `bindAll` function is here:

https://github.com/jashkenas/underscore/compare/1.8.3...1.9.0#diff-0f36b362a0b81d6f4d4bfd8a7413c75dL738

![image](https://user-images.githubusercontent.com/4732/39202941-55c9baf6-47a8-11e8-8625-ebd2958b7dbb.png)

Do you mind tracking down the bug, and telling us more about what and where exactly things are going wrong?

**Comment by ErikLarsson82** [comment]
I did some more testing and if i switch the order (curry first, then bindAll) I get the correct behaviour again.
I tried to dig some but I don't have time for more investigation right now.

**Comment by captbaritone** [comment]
Looks like this is just a change in how `_.bind` works as of https://github.com/jashkenas/underscore/pull/2199.

> The only downside is supported environments will no longer get the correct length property of the bound method. Usually, you subtract the number of bound args from func's length. But, now Underscore is consistent between all environments.

I put together a demo to verify:

```
<html>
    <body>
    <script>function test(a, b) {};</script>

    <script src='https://unpkg.com/underscore@1.8.3/underscore.js'></script>

    <script> console.log("1.8.3 result: ", _.bind(test, {}).length); // 2 </script>

    <script src='https://unpkg.com/underscore@1.9.0/underscore.js'></script>

    <script> console.log("1.9.3 result: ", _.bind(test, {}).length); // 0 </script>
    </body>
</html>
```
[Try it here](https://cdn.rawgit.com/captbaritone/86b6cc132946bc21c57e0ccef95e792b/raw/f693c66f5c128b6fe87d9bd4b7fd613cd992264a/bind.html)
