### ISSUE TITLE
binary search in  _.sortedIndex is not rigorous.

### ISSUE THREAD

**Issue by Reveur000** [jashkenas/underscore#2752]
```
 _.sortedIndex = function(array, obj, iteratee, context) {

    iteratee = cb(iteratee, context, 1);

    var value = iteratee(obj);

    var low = 0, high = getLength(array);

    while (low < high) {

      var mid = Math.floor((low + high) / 2);

      if (iteratee(array[mid]) < value) low = mid + 1; else high = mid;

    }

    return low;

  };
```

the result of (low+high) can be  bigger than 9007199254740991,which is imprecise.

To make sure the result do not be bigger than it, we can avoid it by using this method.

`var mid =Math.floor((high-low)/2)+low;`

**Comment by captbaritone** [comment]
Is this theoretical, or something you've actually hit in real world example?

**Comment by Reveur000** [comment]
It's theoretical and I made a mistake , the length of array will never be greater than 2^32,so this condition will never happen.
However,this is a better way of coding than this.This way of coding brought about some bug in java
in the past.

**Comment by captbaritone** [comment]
Got it. Thanks for flagging, but I think we’re prefer the simpler code over the theoretically safer version. Thanks again!
