### ISSUE TITLE
1.9 regression failing in groupBy

### ISSUE THREAD

**Issue by Husterknupp** [jashkenas/underscore#2756]
Hi folks, I couldn't find an issue containing the `groupBy` function. So I'm creating one. Please redirect if I missed anything. Thanks for all the hard work. Appreciate it!

When updating from version 1.8.3 to 1.9.0 the behaviour of `groupBy` changed in a way that grouping by arrays was possible in 1.8.3, but it's not possible in 1.9.0. At least not as I'm expecting it to work 🤔 

The below test would succeed in 1.8.3 where it throws an exception in 1.9.0. Am I doing something wrong?

```javascript
var anArray = [1,2];
var list = [{
	arrayProp: anArray,
	otherProp: 1
}, {
	arrayProp: anArray,
	otherProp: 2
}];

var res = _.groupBy(list, 'arrayProp');
// var res = _.groupBy(list, function(element) {
//  	// stringified version of key is equal and gets grouped
//  	return JSON.stringify(element.arrayProp);
// });
var groupByKey = Object.keys(res)[0];
console.log(Object.keys(res).length) // 1
console.log(groupByKey); // 1,2

var expected = 2
var actual = res[groupByKey].length;
if (actual !== expected) {
	throw new Error("TEST FAILURE. EXPECTED " + 2 + ". GOT " + actual)
}
```

`-> Uncaught Error: TEST FAILURE. EXPECTED 2. GOT 1`

**Comment by captbaritone** [comment]
Thanks for reporting this. I think we need to switch to a simpler version of `_.has` for our internal use. In most of our six internal cases, we don't actually want the special behavior for Arrays (deep property access).

I think we probably do need to support the case where someone wants to group by (or count by) a key that is not a string, but could be coerced to a string.

I'll look into making a PR in the next few days. In the mean time, you could do something like this, which would be a bit more explicit:

```
var res = _.groupBy(list, val => String(val.arrayProp));
```

**Comment by Husterknupp** [comment]
thanks @captbaritone . This should work but I don't want to change my code right now. I'm not super eager to use 1.9 and can wait a bit more.

**Comment by captbaritone** [comment]
This will be fixed in the next release.
