### ISSUE TITLE
Debounce function documentation

### ISSUE THREAD

**Issue by carpben** [jashkenas/underscore#2762]
According to the documentation at http://underscorejs.org/docs/underscore.html#section-86 the debounce function: 
> Returns a function, that, as long as it continues to be invoked, will not be triggered. 

I think this phrasing is a bit misleading, as the function that won't be triggered is the first parameter it recevies.

**Comment by jashkenas** [comment]
Want to send a PR that improves it, and get the credit for the change?

**Comment by carpben** [comment]
Yes I would, thanks. I'll post a suggestion later this week.

**Comment by jgonggrijp** [comment]
@carpben Friendly reminder that you are still welcome to submit a pull request and get the credit.

**Comment by carpben** [comment]
@jashkenas @jgonggrijp , Thanks for the patience, and sorry for the delay on my part. 

I submitted https://github.com/jashkenas/underscore/pull/2858.

**Comment by jgonggrijp** [comment]
Was merged, closing.
