### ISSUE TITLE
karma-sauce-launcher should be inside devDependencies not dependencies

### ISSUE THREAD

**Issue by davideicardi** [jashkenas/underscore#2764]
It is correct that `karma-sauce-launcher` is installed as a production `dependency`? I think it should be inside devDependencies section. I'm right?

https://github.com/jashkenas/underscore/blob/c0e8feff7fc66ba399409ea0798e32d2806f3ff3/package.json#L50-L52

thanks

**Comment by jashkenas** [comment]
Quite right. That's just **awful!**

Thank you for catching it promptly.
