### ISSUE TITLE
The implementation of debounce with immediate is incorrect

### ISSUE THREAD

**Issue by riophae** [jashkenas/underscore#2770]
For example:

```js
function test(implementation, opts) {
  const start = Date.now()
  const wait = 100
  const interval = 20
  const f = n => console.log(Date.now() - start, n)
  const debounced = implementation(f, wait, opts)
  for (let i = 1; i <= 10; i++) setTimeout(debounced, i * interval, i)
}

test(_.debounce, true)
```

Results in:

```
20 1
```

However, with lodash:

```js
test(_.debounce, { leading: true })
```

We'll get:

```
20 1
303 10
```

Obviously the implementation of lodash is more correct. **underscore's debounce misses the last call.**

**Comment by riophae** [comment]
Now I give another example that more closes to the real-world usage. Say I have an input, as the user types we'll constantly sending request to get data from a remote server. With `immedaite=true`, as soon as the user types the first letter, the first AJAX call will be sent. If the user types very quickly and completes his typing earlier than `wait`, we'll miss the very last call. That's totally unacceptable.

**Comment by kelstra** [comment]
Lodash's trailing option defaults to true. So, if the leading option is also true, then the function is triggered on **both** the leading and trailing edges.

Underscore's immediate option triggers the function on the leading edge, **instead of** on the trailing edge. There is no option to trigger on both edges.

**Comment by jgonggrijp** [comment]
The explanation by @kelstra is correct.
