### ISSUE TITLE
why delete obj[0]

### ISSUE THREAD

**Issue by hooper-hc** [jashkenas/underscore#2773]
in unjs 1.9.1  source  

```javascript
  _.each(['pop', 'push', 'reverse', 'shift', 'sort', 'splice', 'unshift'], function(name) {
    var method = ArrayProto[name];
    _.prototype[name] = function() {
      var obj = this._wrapped;
      method.apply(obj, arguments);
      // TODO why ? 
      if ((name === 'shift' || name === 'splice') && obj.length === 0) delete obj[0];
      return chainResult(this, obj);
    };
  });
```

this line why need 'delete obj[0];'
```if ((name === 'shift' || name === 'splice') && obj.length === 0) delete obj[0];```

**Comment by simulency** [comment]
https://stackoverflow.com/questions/24725560/javascript-why-need-to-delete-the-0-index-of-an-array

**Comment by hooper-hc** [comment]
> https://stackoverflow.com/questions/24725560/javascript-why-need-to-delete-the-0-index-of-an-array

thanks！
