### ISSUE TITLE
npm run node-test does not work as qunit-test does not support wildcards yet

### ISSUE THREAD

**Issue by AaronNGray** [jashkenas/underscore#2774]

**Comment by AaronNGray** [comment]
Added wildcard support to **qunit-cli** as issue https://github.com/devongovett/qunit-cli/issues/17 waiting on pull request.

**Comment by AaronNGray** [comment]
done https://github.com/devongovett/qunit-cli/pull/19

**Comment by jgonggrijp** [comment]
@AaronNGray I'm closing this because I don't see any problem with the `npm run test-node` script in Underscore. If you feel that this is still an issue in Underscore, please reopen and clarify.
