### ISSUE TITLE
Adding _.single 

### ISSUE THREAD

**Issue by nikkorn** [jashkenas/underscore#2775]
Would anyone be interested in a function that behaves much in the same way as _.find, but only returns the first item to pass the predicate truth test IF only a single item passes it, otherwise undefined.

I'm not sure whether this is useful enough, although there have been a couple of times I've needed something like this to avoid having to validate whether we only have a single item that passes the predicate.

If so i'm happy to do the PR.

**Comment by jgonggrijp** [comment]
Closing in line with #2791. For future reference, this is how you can add `_.single` to your own instance of Underscore:

```js
function single(collection, predicate, context) {
    var matches = filter(collection, predicate, context);
    if (matches.length === 1) return matches[0];
    return void 0;
}

_.mixin({single: single});
```

Suggestions like these can also be submitted to [underscore-contrib](https://github.com/documentcloud/underscore-contrib). It has been unmaintained for a while, but I'm looking into a solution for that. If you submit a pull request over there, it might not be merged but it will be noticed.
