### ISSUE TITLE
Add to API document for the return value of bindAll function.

### ISSUE THREAD

**Issue by jongwookyi** [jashkenas/underscore#2777]
For many versions lower than 1.9.0 bindAll function returned bound object.
Since the version 1.9.0 it has been changed not to return.
This change might break the codes that used return value of bindAll function.

Please add to API document for the return value of bindAll and hopefully other functions.
Thanks.

**Comment by jgonggrijp** [comment]
@jongwookyi Thanks for reporting and sorry for the slow response.

This was almost certainly an unintended breaking change caused by https://github.com/jashkenas/underscore/commit/3cd04870adff10304da1a5cbd19c9aa310f1ee2c.
