### ISSUE TITLE
Documentation Site has very small font.

### ISSUE THREAD

**Issue by GajananMore** [jashkenas/underscore#2780]
Hi,

Documentation is in small font, have to zoom in every time needs to see document. can you increase font?

Thanks,
Gajanan.

**Comment by HZooly** [comment]
@GajananMore Font size seems correct. I'm using Chrome 70 on macOS

**Comment by jgonggrijp** [comment]
@GajananMore Sorry to hear that you found the documentation difficult to read. Do you still have this problem?

If you still have this problem, please tell us some details about your operating system, hardware and browser version. Perhaps also show us a screenshot. Thanks in advance.

**Comment by bnjmnt4n** [comment]
This is probably related to the website being not very mobile-friendly.
