### ISSUE TITLE
isEmpty

### ISSUE THREAD

**Issue by githublyp** [jashkenas/underscore#2788]
_.isEmpty(11)
true
_.isEmpty(''+11)

false

**Comment by LuigiC** [comment]
But I don't think this can be considered an issue, since ''+11 is equivalent to '11', and therefore not empty.

**Comment by skynin** [comment]
from doc
_.isEmpty(object) ... Returns true if an enumerable object  ... For strings and array-like objects _.isEmpty checks if the length property is 0. 

11 is not object, and has no the length property
'11' is string and has the length property

**Comment by jgonggrijp** [comment]
Seems to be resolved.
