### ISSUE TITLE
Build or build+test dependencies

### ISSUE THREAD

**Issue by swedebugia** [jashkenas/underscore#2790]
Hi
I'm wondering how many of the 12 devdeps are strictly needed for building? How many are needed if we want to test it too?

We are trying in Guix to figure out how to package npm-libraries in a reproducible way.
See also: https://lists.gnu.org/archive/html/guix-devel/2018-11/msg00201.html

I'm using a guile-script to make a graph of this package and the devdependencies and all recursive dependencies of those. It is still running and has 85 levels and 160 packages and counting.

This means that if we are to package async with all the devdeps (unlikely needed I hope so) we need first to package 160+ other packages to build the devdeps.

This is a lot.

Cheers
swedebugia

**Comment by captbaritone** [comment]
Does this help?

```
  "devDependencies": {
    "coveralls": "^2.11.2", // NOT NEEDED: Posts coverage reports to converalls.io
    "docco": "*", // NOT NEEDED: Builds docs
    "eslint": "1.10.x", // Needed for linting (not sure if you think of linting as part of testing)
    "gzip-size-cli": "^1.0.0", // NOT NEEDED
    "karma": "^0.13.13", // Needed for testing
    "karma-qunit": "~2.0.1", // Needed for testing
    "karma-sauce-launcher": "^1.2.0", // Needed for testing
    "nyc": "^2.1.3", // Needed for testing
    "pretty-bytes-cli": "^1.0.0", // NOT NEEDED
    "qunit-cli": "~0.2.0", // Needed for testing
    "qunit": "^2.6.0", // Needed for testing
    "uglify-js": "3.3.21" // Needing for building
  },
```

**Comment by swedebugia** [comment]
Yes! Thanks to this we can reduce the dependencies drastically if we choose to leave out the tests.
