### ISSUE TITLE
Suggestion: Extending the function `_.partition` function beyond boolean predicate/classifier

### ISSUE THREAD

**Issue by orezvani** [jashkenas/underscore#2793]
The existing partition function can divide the input collection into only two arrays. Why not extending the predicate/classification function to more than two sets?

I have done this in my clone of the project.

**Comment by jgonggrijp** [comment]
@orezvani Does [`_.groupBy`](https://underscorejs.org/#groupBy) perhaps do what you're looking for?

**Comment by jgonggrijp** [comment]
Closing due to lack of response. @orezvani Please feel welcome to comment or reopen.
