### ISSUE TITLE
Logic attempting to reference the global object is overly complicated

### ISSUE THREAD

**Issue by david-mark** [jashkenas/underscore#2797]
In the way this line is run, the - this - object *is* a reference to the global (referred to as "root" here) object, so the rest of this can be discarded. Found it odd that there was a fallback to a newly constructed Object object (what good would that do in this context?), which seemed to indicate a lack of confidence in the expression leading up to it. The comment doesn't match the logic either.

  // Establish the root object, `window` (`self`) in the browser, `global`
  // on the server, or `this` in some virtual machines. We use `self`
  // instead of `window` for `WebWorker` support.
  var root = typeof self == 'object' && self.self === self && self ||
            typeof global == 'object' && global.global === global && global ||
            this ||
            {};

**Comment by jashkenas** [comment]
David Mark! Good to hear from you!

People have used Underscore in all kinds of strange places — old browsers, Node.js, Narwhal, Adobe Illustrator, with AMD, UMD, various module systems, and so on...

That initial bit of code attempts to safely find the global namespace, whatever the JS environment might be, so that we can restore the previous definition of `_`, in the case that you later call `_.noConflict()`.

If no global namespace exists, we use an empty one, instead of putting conditionals everywhere the script later mentions `root`. Of course, you could do it either way.

**Comment by david-mark-cintas** [comment]
Nothing strange about any of those places. And ISTM that it should just throw an exception if no global *object* is found (a scenario impossible in a standards-compliant ECMAScript implementation).\

Anyway, as mentioned, you need only:

var root = this;

...and I expect you previously had a 'use strict' directive in here, right? That's the only possible way that you could have been led down the path to the current code (not that it would be right in that case either, but similar mistakes are common).

After nine years and who knows how many sets of eyes, it would be nice to get the *first line* right. ;)

**Comment by david-mark** [comment]
Nothing strange about any of those places. And ISTM that it should just throw an exception if no global object is found (a scenario impossible in a standards-compliant ECMAScript implementation).

Anyway, as mentioned, you need only:

var root = this;

...and I expect you previously had a 'use strict' directive in here, right? That's the only possible way that you could have been led down the path to the current code (not that it would be right in that case either, but similar mistakes are common).

After nine years and who knows how many sets of eyes, it would be nice to get the first line right. ;)

**Comment by david-mark** [comment]
Also, why do you feel the need to "sniff for old browser globals"? As in host objects found only in old browsers? I don't have the stomach to read past the first line of this thing (certainly not in 2019), but that sure sounds like browser sniffing.

I assume this library has come and gone. Found it in a framework and experienced deja vu with that first line. React and other libraries do similar things; as do AMD implementations, UMD, jQuery, etc. Open source developers have a responsibility to set good examples, but few seem to live up to it; always in a hurry to close issues without taking the time to understand them.

Good luck to you! :)
