### ISSUE TITLE
sort positive numbers first then, negative

### ISSUE THREAD

**Issue by chitgoks** [jashkenas/underscore#2803]
is this possible using 1 inline code?

e.g.

1, 4, -8, 2, -1, 6

result

1, 2, 4, 6, -1, -8

- so positive sorting is ascending
- negative sorting is descending
- positive must be sorted first, then negative

**Comment by AlisherAmonulloev** [comment]
`_.partition([1, 4, -8, 2, -1, 6].sort(), (n) => { return n > 0 }).join()`
Is this "inline" enough?

**Comment by chitgoks** [comment]
looks good thank you
