### ISSUE TITLE
contains doesn't behave properly

### ISSUE THREAD

**Issue by eimf** [jashkenas/underscore#2807]
**source**: https://jsonplaceholder.typicode.com/users

_correct output with_ https://lodash.com/docs/4.17.11#includes same **source**

**Comment by jgonggrijp** [comment]
@eimf Could you please show the code that invokes `_.contains`?

**Comment by jgonggrijp** [comment]
Closing this for lack of response. @eimf Please feel free to reopen or comment if you want to take up on this again.
