### ISSUE TITLE
Questions about _.indexOf()？

### ISSUE THREAD

**Issue by Wangyi-max** [jashkenas/underscore#2810]
_.indexOf([1,2,3,NaN,5,6],NaN,true)   // => -1

Source code
array[idx] === item ? idx : -1;

Can NaN detection be put in front?

**Comment by PengFanIsBest** [comment]
老师我来看你了，indexOf二分查找需要有序数组，里面混入了外星人（NaN），所以并不是有序数组。

**Comment by Wangyi-max** [comment]
> 老师我来看你了，indexOf二分查找需要有序数组，里面混入了外星人（NaN），所以并不是有序数组。
Thank you

**Comment by jgonggrijp** [comment]
I'm closing this because it seems the issue is resolved. If it isn't, please feel free to reopen or comment.
