### ISSUE TITLE
How do you display total number of records in a template?

### ISSUE THREAD

**Issue by lschneiderman** [jashkenas/underscore#2811]
I'm having trouble getting any answers on underscore.js on stackoverflow, so I'm just going to ask here. How do you display the total number of records in a template? In this example, how would I display totalNum?

<script type="text/template" id='templatePropertyLot'>
    <%  _.each(items,function(item,key,list) { %>
        <div class="popup_wrapper">
            <div class="header" id="count_of_addresses"><span id="currNum"><%- key + 1 %></span> of <span id="totalNum"></span> addresses in this search</div>
        </div>  
    <% }); %>
</script>

**Comment by spattanaik75** [comment]
shouldn't it be 

_.each(items,function(item,key,items) { %>
<%- items.length %> of addresses in this search
<% });

**Comment by jgonggrijp** [comment]
For future reference, if your `items` looks like this:

```js
[{id: 100}, {id: 101}]
```

Then you can render something for each `item` and then display the total number of them at the end like this:

```erb
<% _.each(items, function(item, index, list) { %>
    <!-- print whatever you want about each `item` here -->
<% }); %>
Total number of items: <%= items.length %>
```

If you want to tally during iteration to show something like “item 5 of 10”, this will work:

```erb
<% _.each(items, function(item, index, list) { %>
    This is item <%= index %> of <%= list.length %>.
<% }); %>
```

@lschneiderman @spattanaik75
