### ISSUE TITLE
Chain sorting an array does not return an array (Typescript)

### ISSUE THREAD

**Issue by MichaelGatesDev** [jashkenas/underscore#2812]
This snippet worked for me until I added Typescript and updated the package

```
rooms = _(this.getAllRooms()).chain().sortBy(function (room: Room) {
                return room.number;
            }, this).sortBy(function (room: Room) {
                return room.buildingName;
            }, this).value();
```
[Code here](https://github.com/MichaelGatesDev/ccss-support-manual/blob/master/packages/frontend/src/Sections/Home/Home.tsx#L86)

It takes an array of objects, sorts them, and returns the sorted array. 

But now, it complains that this code does not return a `Room[]` or otherwise array of objects. Rather, it returns a single `Room`. Using `values` returns a `_._Chain<any, any>` which is also not what I need.

How can I get around this issue? I just need a standard array returned.

**Comment by MichaelGatesDev** [comment]
It appears this issue is likely [also this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36510)

**Comment by jgonggrijp** [comment]
This is certainly an issue with `@types/underscore` rather than with underscore itself.

**Comment by jgonggrijp** [comment]
Closing. Please feel free to comment or reopen.
