### ISSUE TITLE
Enhance _.difference to evaluate non-primitives

### ISSUE THREAD

**Issue by sambavaro** [jashkenas/underscore#2822]
I came across a need to compare two arrays A and B of objects, and produce an output array containing the objects belonging to A but not B. This use case is supported by _.difference, but only if the elements within the array are primitives.

**Comment by jashkenas** [comment]
Difference also works with objects, using JavaScript’s object equality semantics. 

I'm not interested in adding deep object comparison/equality operators to core Underscore ... but I'm sure there are already lots of other libraries and plugins you can use that will do this.
