### ISSUE TITLE
Documentation of _.before is misleading (off-by-one)

### ISSUE THREAD

**Issue by MaxBarraclough** [jashkenas/underscore#2833]
Regarding the documentation of the `_.before` function:

At https://underscorejs.org/#before the documentation says:

> Creates a version of the function that can be called no more than count times. The result of the last function call is memoized and returned when count has been reached. 

On the other hand the in-source comment [states](https://github.com/jashkenas/underscore/blob/ca7d3f5cd27de32c1ed78581458e3dff485e48df/underscore.js#L956):

> Returns a function that will only be executed up to (but not including) the Nth call.

It seems the documentation is off-by-one, as it does not make clear the *but not including* behaviour. Also, it is misleading to say "can be called no more than", as of course the resulting function can be called as many times as is needed.

Also, it would be helpful to spell out how it behaves in the case of an exception being thrown.

**Comment by jgonggrijp** [comment]
> At https://underscorejs.org/#before the documentation says:
> 
> > Creates a version of the function that can be called no more than count times. The result of the last function call is memoized and returned when count has been reached.
> 
> On the other hand the in-source comment [states](https://github.com/jashkenas/underscore/blob/ca7d3f5cd27de32c1ed78581458e3dff485e48df/underscore.js#L956):
> 
> > Returns a function that will only be executed up to (but not including) the Nth call.
> 
> It seems the documentation is off-by-one, as it does not make clear the _but not including_ behaviour.

This is not a difference. It's just zero-based counting. `_.before(2, func)` will call `func` two times, the 0th time and the 1st time. So up to, but not including, the 2nd time. The source comment probably describes it in zero-based terms because the source itself is zero-based.

**Comment by jgonggrijp** [comment]
@MaxBarraclough I think it is possible to interpret the documentation in a way that aligns with the actual behaviour. That said, I agree it can also be interpreted in an off-by-one way.

Would you mind submitting a concrete suggestion for a fix, preferably in the form of a pull request?

**Comment by MaxBarraclough** [comment]
Sure here are some ideas:

### Suggestion 1

Returns a wrapper function over **function** such that the result of the (count-1)'th call is memoized, and returned immediately by all subsequent calls.

**count** is 1-based, such that if **count** = 2, **function** will be called at most once.

Exception handling:

* If a call prior to the (count-1)'th call of **function** throws an exception, the wrapper function also throws it.
* If the (count-1)'th call of **function** results in an exception being thrown, the wrapper function also throws it, and subsequent calls to the wrapper function return **undefined**.


### Suggestion 2

***A slightly more precise variation but using a mathematical style:***


Returns a wrapper function **w** over **function** such that the result of the (count-1)'th call is memoized, and returned immediately by all subsequent calls of **w**.

**count** is 1-based, such that if **count** = 2, **w** will call **function** at most once.

If a call prior to the (count-1)'th call of **function** throws an exception, **w** also throws it. If the (count-1)'th call of **function** results in an exception being thrown, **w** also throws it, and subsequent calls to **w** return **undefined**.

**Comment by jgonggrijp** [comment]
How about this:

> Creates a wrapper of **function** that memoizes its result. From the **count**-th call onwards, the memoized result of the last invocation is returned immediately instead of invoking **function** again. So the wrapper will invoke **function** at most **count** - 1 times.

A function that throws doesn't have a return value, so I don't think this needs separate mentioning.

For completeness, perhaps also a slight rewording of `_.after`:

> Creates a wrapper of **function** that does nothing at first. From the **count**-th call onwards, it starts actually calling **function**. Useful for grouping asynchronous responses, where you want to be sure that all the async calls have finished, before proceeding.

**Comment by MaxBarraclough** [comment]
Excuse my slow reply. That fixes the ambiguity nicely 👍 but:

> A function that throws doesn't have a return value, so I don't think this needs separate mentioning.

I strongly disagree here. For the documentation to be complete, it must describe the function's handling of exceptions. An alternative behaviour would be for the wrapper function to throw that exception again on subsequent invocations.

Similarly the documentation for the *after* function should be explicit that before the threshold is reached, *undefined* is returned.

**Comment by jgonggrijp** [comment]
> I strongly disagree here. For the documentation to be complete, it must describe the function's handling of exceptions.

In that case, I'm afraid all of the Underscore documentation is incomplete. Would you prefer it to be twice as long? ;-)

> An alternative behaviour would be for the wrapper function to throw that exception again on subsequent invocations.

To me, that sounds like a really bad idea that nobody would expect.

> Similarly the documentation for the _after_ function should be explicit that before the threshold is reached, _undefined_ is returned.

"Does nothing" already says that.

How about this: I'll prepare a pull request with the text that I last suggested, but I'll change "result" into "return value" so it's unambiguous that we're not talking about exceptions. That way, at least we have a solution for the off-by-one problem. Independently of that, you can prepare your own pull request to make it more to your liking.

**Comment by MaxBarraclough** [comment]
That's much clearer, thanks.

> In that case, I'm afraid all of the Underscore documentation is incomplete. Would you prefer it to be twice as long? ;-)

Honestly, yes. Brevity is a virtue, but not at the cost of completeness. That's a different matter though, and you've already addressed the ambiguity that this thread is about.

> To me, that sounds like a really bad idea that nobody would expect.

Disagree. If we treat the memoized function as simulating the final call to the underlying function, we'd assume it would throw, just as the final call to the underlying function did. If the documentation isn't clear on how an exception is handled, it's not complete.

> "Does nothing" already says that.

It doesn't, it leaves the reader to infer that `undefined` is returned.

Anyway, that's all by the by. Thanks for making the change, and apologies for my slow responses!

**Comment by jgonggrijp** [comment]
No need to apologize, @MaxBarraclough! This time, I was a bit slow to respond as well.

I'm happy that we could reach an agreement on the core of the issue. As I said before, please feel welcome to open a pull request any time.
