### ISSUE TITLE
Error when compiling VueJs application with Webpack and UglifyJs 1.10.2

### ISSUE THREAD

**Issue by matteocacciola** [jashkenas/underscore#2838]
hello, I am building my VueJs based app with webpack. It uses underscorejs too
I am experiencing this error

![2020-04-07-145446_1920x1080_scrot](https://user-images.githubusercontent.com/28953594/78672083-73430180-78e0-11ea-9187-4063c0f9f4df.png)

can someone help me, please?
underscorejs version is 1.10.2

**Comment by jgonggrijp** [comment]
It's impossible to tell from just the screenshot. `"chunk" is read-only` seems to suggest that something is trying to overwrite the `chunk` function.

I'm willing to take a look. Could you share your code, or otherwise create a reduced testcase and share that?

**Comment by jgonggrijp** [comment]
Closing this as 30 days passed without a response. @matteocacciola please feel free to reopen or comment if you want to take up on this again.
