### ISSUE TITLE
Add a note about JS comparison operators

### ISSUE THREAD

**Issue by jgonggrijp** [jashkenas/underscore#2846]
I would like to close all three of these tickets, because I believe they are based on a misunderstanding of the `<` operator, and I'd like to address this with a note in the documentation instead:

- #1768
- #1834
- #2042

The note would be somewhere at the bottom of the page, with a link to the MDN entry on the comparison operators. Reference entries on functions like `_.sortBy` and `_.sortedIndex` would reference to this note.

@jashkenas do you agree?

**Comment by jashkenas** [comment]
I agree! I don’t think that sorting `NaN` or `undefined` are an important problem to "fix" — you should *never* be sorting them.
