### ISSUE TITLE
Fix the Travis build

### ISSUE THREAD

**Issue by jgonggrijp** [jashkenas/underscore#2847]
Preferably using GitHub Actions. See discussion in #2740.

**Comment by jgonggrijp** [comment]
@jashkenas We just got a patch by @dominykas that fixed an inconspicuous indentation mistake in the `.travis.yml`. I suspect this is the reason why Travis stopped working in 2018 (see https://github.com/jashkenas/underscore/pull/2856#issuecomment-644083601). However, it appears that fixing the indentation is not sufficient to re-activate the repository; if I try to trigger a custom build on travis-ci.org, it still tells me that the repository is not active.

Would you mind a quick try whether you can activate the repository on travis-ci.org? I cannot do this on your behalf. With some luck, re-activating is all that is left to be done to get CI working again.

**Comment by jashkenas** [comment]
Sure thing. I’ve logged in and reactivated [the repository](https://travis-ci.org/github/jashkenas/underscore) on Travis.

**Comment by jgonggrijp** [comment]
Thanks @jashkenas! I was able to trigger a [custom build](https://travis-ci.org/github/jashkenas/underscore/builds/698687023). It failed, but hopefully at least we now have any CI at all. After I'm done with #2849, I'll see whether I can fix the build.

Keeping this open until I'm sure the build triggers automatically.

**Comment by jgonggrijp** [comment]
I pushed a bunch of new commits to #2849 and Travis automatically started a new build, so it appears we'll have CI again. The build is however consistently failing over something futile, so keeping this open and changing the title to remind myself that there is still something to be done.
