### ISSUE TITLE
Access to Underscorejs.org Blocked

### ISSUE THREAD

**Issue by erikblessman** [jashkenas/underscore#2861]
I work for LinQuest Corporation as a S/W Developer and have been using underscore js for a while now.  Just recently, access to underscorejs.org has been blocked.  I checked with our IT dept. and they are not blocking access.

What do we need to do to restore access to underscorejs.org?

**Comment by jashkenas** [comment]
I’m afraid that I don’t know what you’ll need to do, as nothing has changed on our end. 

If you’d like to reply with more information, such as the DNS lookup logs from when you try to connect from your work computer, we’ll be happy to reopen this ticket and help you figure it out.
