### ISSUE TITLE
Transposing matrices using zip/unzip

### ISSUE THREAD

**Issue by jgonggrijp** [jashkenas/underscore#2867]
This came to my attention while reviewing https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46306.

The documentation currently suggests to transpose nested arrays using `zip.apply`. This is, however, a bit convoluted, as `unzip` does matrix transposing out of the box, and `zip` is actually implemented on top of `unzip`. I suspect this is a part of the documentation that stems from an era when `unzip` didn't exist yet.

I suggest two changes:

- Update the documentation to suggest using `unzip` for matrix transposing instead.
- Add a `transpose` alias to `unzip`, since transposing matrices is likely a common use case. This name doesn't appear in Contrib or Lodash, so I think there should be no conflicts.

@jashkenas I'm asking your opinion on this as a "review before implementation". If you agree, I'll get it done without asking for another review.

**Comment by jashkenas** [comment]
That sounds great to me!
