### ISSUE TITLE
_.ieEqual doesn't work with objects whose value is a Set

### ISSUE THREAD

**Issue by aswathkk** [jashkenas/underscore#2889]
Here's the example which was failing for me:
```
_.isEqual({a:new Set([1,2])}, {a: new Set([1])})
// returns true
```

**Comment by jgonggrijp** [comment]
Duplicate of #2451 and by extension, #2147.

**Comment by jgonggrijp** [comment]
By the way, support for `Map`, `Set` and iterables is planned for version 2.0.
