### ISSUE TITLE
Add dark mode support for homepage

### ISSUE THREAD

**Issue by gprasanth** [jashkenas/underscore#2909]
Tried adding dark mode support for the docs on the underscorejs.org homepage.

Here's how it looks before and after:

![Screen Shot 2021-02-07 at 15 35 44](https://user-images.githubusercontent.com/1318897/107143283-4f19dc00-695a-11eb-98bb-31a670a162f4.png)
![Screen Shot 2021-02-07 at 15 24 45](https://user-images.githubusercontent.com/1318897/107143286-5345f980-695a-11eb-805e-3f6150a41eb1.png)

The code is available in a very short gist here:

[doccy-dark.css](https://gist.github.com/gprasanth/aae06b6e437d00f37af3bddc78776f57)

To submit a pull request I am not sure where to add this... in index.html in source root? or in docco.css?

In any case, this can be tweaked as required and added. Also, the logo lost the signature blue color, but can be avoided if an alternative logo image with white text is available.

**Comment by jgonggrijp** [comment]
Nice suggestion, thanks!

**Comment by itsdeekay** [comment]
@gprasanth You can raise PR . Recommended would be to use in index.html itself as all of the existing code is inside it. Also it ca be separated in docs folder and with specified folder.
