### ISSUE TITLE
Documentation _.unescape uses wrong hex code

### ISSUE THREAD

**Issue by MalteSaup** [jashkenas/underscore#2925]
In the documentation you use &#96 ; for the ` Symbol, wich is the correct Decimal Code, but _.unescape seems to only work with the hex code &#x60 ; wich also is returned from the _.escape function

**Comment by jgonggrijp** [comment]
Thanks for bringing this to our attention, @MalteSaup! If you like, please feel welcome to submit a PR to fix the documentation and get the credit for it.

**Comment by itsdeekay** [comment]
Hi @jgonggrijp , I have started contributing to open source. Could you assign this issue to me so that I can contribute?

**Comment by jgonggrijp** [comment]
@itsdeekay Thanks for stepping up! You can contribute without being assigned, but I don't mind assigning people so there you are.

**Comment by itsdeekay** [comment]
Thanks @jgonggrijp , I have created a pull request for the same. Do you have any contribution guidelines for this project? So that I can follow it
