### ISSUE TITLE
ES6 module support broken in 1.13.x

### ISSUE THREAD

**Issue by tstibbs** [jashkenas/underscore#2929]
When importing underscore into an ES6 module, an error is raised by the compiler.

### To reproduce
1. Populate `index.mjs` like this:
    ```
    import underscore from 'underscore'
    console.log(underscore)
    ```

1. `npm install underscore@1.13.1`
1. `node index.mjs`
1. An error will be logged as follows:
    ```
    file:///workspace/node_modules/underscore/underscore-node.mjs:6
    export { VERSION, after, every as all, allKeys, some as any, extendOwn as assign, before, bind, bindAll, chain, chunk, clone, map as collect, compact, compose, constant, contains, countBy, create, debounce, _ as default, defaults, defer, delay, find as detect, difference, rest as drop, each, _escape as escape, every, extend, extendOwn, filter, find, findIndex, findKey, findLastIndex, findWhere, first, flatten, reduce as foldl, reduceRight as foldr, each as forEach, functions, get, groupBy, has, first as head, identity, contains as include, contains as includes, indexBy, indexOf, initial, reduce as inject, intersection, invert, invoke, isArguments, isArray, isArrayBuffer, isBoolean, isDataView, isDate, isElement, isEmpty, isEqual, isError, isFinite, isFunction, isMap, isMatch, isNaN, isNull, isNumber, isObject, isRegExp, isSet, isString, isSymbol, isTypedArray, isUndefined, isWeakMap, isWeakSet, iteratee, keys, last, lastIndexOf, map, mapObject, matcher, matcher as matches, max, memoize, functions as methods, min, mixin, negate, noop, now, object, omit, once, pairs, partial, partition, pick, pluck, property, propertyOf, random, range, reduce, reduceRight, reject, rest, restArguments, result, sample, filter as select, shuffle, size, some, sortBy, sortedIndex, rest as tail, first as take, tap, template, templateSettings, throttle, times, toArray, toPath, unzip as transpose, _unescape as unescape, union, uniq, uniq as unique, uniqueId, unzip, values, where, without, wrap, zip } from './underscore-node-f.cjs';
             ^^^^^^^
    SyntaxError: The requested module './underscore-node-f.cjs' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
    For example:
    import pkg from './underscore-node-f.cjs';
    const { VERSION, after, every: all, allKeys, some: any, extendOwn: assign, before, bind, bindAll, chain, chunk, clone, map: collect, compact, compose, constant, contains, countBy, create, debounce, _: default, defaults, defer, delay, find: detect, difference, rest: drop, each, _escape: escape, every, extend, extendOwn, filter, find, findIndex, findKey, findLastIndex, findWhere, first, flatten, reduce: foldl, reduceRight: foldr, each: forEach, functions, get, groupBy, has, first: head, identity, contains: include, contains: includes, indexBy, indexOf, initial, reduce: inject, intersection, invert, invoke, isArguments, isArray, isArrayBuffer, isBoolean, isDataView, isDate, isElement, isEmpty, isEqual, isError, isFinite, isFunction, isMap, isMatch, isNaN, isNull, isNumber, isObject, isRegExp, isSet, isString, isSymbol, isTypedArray, isUndefined, isWeakMap, isWeakSet, iteratee, keys, last, lastIndexOf, map, mapObject, matcher, matcher: matches, max, memoize, functions: methods, min, mixin, negate, noop, now, object, omit, once, pairs, partial, partition, pick, pluck, property, propertyOf, random, range, reduce, reduceRight, reject, rest, restArguments, result, sample, filter: select, shuffle, size, some, sortBy, sortedIndex, rest: tail, first: take, tap, template, templateSettings, throttle, times, toArray, toPath, unzip: transpose, _unescape: unescape, union, uniq, uniq: unique, uniqueId, unzip, values, where, without, wrap, zip } = pkg;
        at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
        at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
        at async Loader.import (internal/modules/esm/loader.js:165:24)
        at async Object.loadESM (internal/process/esm_loader.js:68:5)
    ```

### What I've tried

- Using a `.js` file and declaring `"type": "module"` in the `package.json` results in the same error.
- Switching to the named imports style (e.g. `import {some} from 'underscore'`) results in the same error.

### Workaround
- Use version `1.12.1` with the 'default' import style

### Environment

Node version: 14.8.0
npm version: 7.10.0

**Comment by jgonggrijp** [comment]
Thank you for reaching out, @tstibbs. I'm a bit surprised by the problem you're running into, for two reasons.

**Theoretical reason:** the Node.js documentation [states](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_import_statements) that

> When importing CommonJS modules, the `module.exports` object is provided as the default export. Named exports may be available, provided by static analysis as a convenience for better ecosystem compatibility.

I ensured that this static analysis was possible in the `underscore-node-f.cjs` by [listing each named export separately](https://github.com/jashkenas/underscore/blob/3d2f17a62b2987c2b7f93880edb0d4e48ce61f10/underscore-node-f.cjs#L2032-L2157) with the `exports.name = ...` syntax. The error message you're getting from Node 14.8.0 seems like Node.js is contradicting its own documentation.

**Empirical reason:** I made a CI test that is [very similar](https://gitlab.com/jgonggrijp/underscore-import-tests/-/blob/integration/monolithic-esm.mjs) to yours and which [passes without a problem](https://gitlab.com/jgonggrijp/underscore-import-tests/-/jobs/1285241282) in Node 14.

Of course, I don't doubt your report and of course, I want this to work. Before I invest a lot of effort [again](https://github.com/jashkenas/underscore/pull/2914) into supporting Node.js's exotic "support" for ESM, though: would you mind trying whether upgrading to Node.js 14.17 solves the problem for you?

**Comment by tstibbs** [comment]
Yes, a node upgrade fixed it... (14.13.0 was the latest available in my package repo but that seemed to be enough). Looking at the changelog it looks like the CJS export detection didn't appear until 14.13 (https://github.com/nodejs/node/pull/35249).

I probably should have tried that first, thanks for the pointer and the well reasoned response, and sorry for the spurious report!

**Comment by jgonggrijp** [comment]
No problem @tstibbs, I'm glad your problem has been solved!
