### ISSUE TITLE
Npm install fails due to post install script

### ISSUE THREAD

**Issue by Rofer11607** [jashkenas/underscore#2968]
hello,
I cannot deploy my firebase project because this is a dependency to alot of packages I have installed. The remote build bails with code 127 and says 'sh: patch-package: command not found'

I tried to install the package locally and the same thing happens when I run npm install underscore --force. How can I fix this?

**Comment by vincent-ogury** [comment]
duplicate this: https://github.com/jashkenas/underscore/issues/2967

**Comment by iglosiggio** [comment]
You can add patch-package as a devDependency in your project (as a hacky workaround, i don't really like the idea of a dependency patching other dependencies).

**Comment by jgonggrijp** [comment]
I just released 1.13.6, hopefully that fixes it. Please close if that is the case.
