### ISSUE TITLE
Patch is a dev dependency in 1.13.5. 

### ISSUE THREAD

**Issue by markfoo1** [jashkenas/underscore#2969]
Consumers who use underscore as a dependency rather than as a dev dependency fail in postinstall because patch package is not available.

**Comment by mjaggard** [comment]
This has broken my build :(

**Comment by joeycozza** [comment]
duplicate of https://github.com/jashkenas/underscore/issues/2967

**Comment by jgonggrijp** [comment]
I just released 1.13.6, hopefully that fixes it. Please close if that is the case.
