### ISSUE TITLE
Filtering on objects could return an object

### ISSUE THREAD

**Issue by chikamichi** [jashkenas/underscore#359]
Hi,

Here is a common use-case for filter. Given

``` js
a = {35: true, 45: true, 55: false}
```

one would like to filter and get back only pairs which value is truish:

``` js
_.filter(a, function(val, key) {
  val === true;
});
// => {35: true, 45: true}
```

Currently, functions such as filter push(value) so one gets an array.

Is there any easy way to achieve this with a workaround, and if not, would you consider switching the return's type based on whether we're providing an object or a list?

**Comment by jtfairbank** [comment]
+1 Could you guys add `_.filterObj` (etc) one at a time, similar to `_.mapObj`?

**Comment by jtfairbank** [comment]
jk, just saw `_.pick` which is perfect for my use case

**Comment by typerory** [comment]
@jtfairbank exactly what I need and probably what most people need when they come here looking to 'filter' an object and create an object.

**Comment by towry** [comment]
`_.pickBy`
