### ISSUE TITLE
Invert escape on templates

### ISSUE THREAD

**Issue by sobrinho** [jashkenas/underscore#394]
I think it's more safe.

Instead of:

``` javascript
_.template("hello <%= name %>", { name: "<script>alert(1);</script>" })
// "hello <script>alert(1);</script>"

_.template("hello <%- name %>", { name: "<script>alert(1);</script>" })
// "hello &lt;script&gt;alert(1);&lt;&#x2F;script&gt;"
```

That:

``` javascript
_.template("hello <%= name %>", { name: "<script>alert(1);</script>" })
// "hello &lt;script&gt;alert(1);&lt;&#x2F;script&gt;"

_.template("hello <%= raw(name) %>", { name: "<script>alert(1);</script>" })
// "hello <script>alert(1);</script>"
```

Obviously, it's backwards incompatible :)

Note how the rails behave:

``` erb
hello <%= name %>
<!-- hello &lt;script&gt;alert(1);&lt;&#x2F;script&gt; -->

Hello <%= raw name %>
<!-- hello <script>alert(1);</script> -->
```

We can do that just changing the `templateSettings` but would be nice if it's default ;)

**Comment by oxdef** [comment]
Lets update this discussion. As my opinion security should be built-in by default into such thing like framework. If something is needed todo manually (e.g. using `<%-`) every time by the developer to make his code more secure it is not right way.  XSS is the one of the most popular security issues today. So I strongly recommend to change default behaviour to auto escaping for  ` <%= ` and add template setting to make possible switching it off.
