### ISSUE TITLE
_.isNumber(NaN) returns true

### ISSUE THREAD

**Issue by park9140** [jashkenas/underscore#406]
As NaN stands for "Not a Number" the isNumber check in this case seems like it should return false.  I notice from other discussions that this is in fact on purpose.  Maybe the documentation should reflect this fact explicitly.

**Comment by LiamKarlMitchell** [comment]
```
if (isNaN(Number(value))) {
  alert('Number required.');
}
```

**Comment by netdragonboberb** [comment]
Follow the JS standard. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

You also return false for isNaN(undefined)

Both are wrong and unexpected

But now, you'll need to create new functions since these are already messed up.

**Comment by jehrenzweig** [comment]
@pspi Agreed.  Making `_.isNumber()` behave correctly in the semantic sense means I'll never actually use it.
