### ISSUE TITLE
_.isEmpty Behavior on numbers

### ISSUE THREAD

**Issue by siyegen** [jashkenas/underscore#432]
``` javascript
var cow = {a: 1, b: {}, c: []};
_.isEmpty(cow); // returns false
```

isEmpty works fine on objects containing numbers as the only 'non-empty' values

``` javascript
_.isEmpty(cow.a); // returns true
```

However the individual k,v of a:1 is considered empty.

I did read through the issues and noted that originally _.isEmpty wasn't intended for strings, so this might be intended. If it's not intended then I have a branch I can make a pull request for.

**Comment by timurridjanovic** [comment]
I ran into this today.. I was using it with _.omit
```
_.omit(someObject, _.isEmpty);
```

**Comment by panialex** [comment]
the real use of isEmpty should be if the value is empty, the value that you don't know what it is, or wherever value that you need to know what it is, but js its a pile of bugs so I understand why it just generates more bugs
