### ISSUE TITLE
still recommend flatMap or concatMap

### ISSUE THREAD

**Issue by rebcabin** [jashkenas/underscore#452]
with reference to issue 436, I agree that documenting the second argument to flatten is a good start, but it didn't quite close the issue for me.  I would still recommend adding a "flatMap" or "concatMap" primitive to the base library so that we get proper chain composability. Adding this new primitive would not break anything, but would make chains of array-valued maps composable. For instance, imagine the following expression, in pseudo-C#, that represents the line items for high-value orders from a list of customers:
Customers
    .Where(customer => customer.Orders
        .SelectMany(order => order.LineItems)
        .Sum() > 1000)
    .SelectMany(customer => customer.Orders)
    .SelectMany(order => order.LineItems) ;

to write this in underscore with a new flatMap primitive, the "SelectMany"s become "flatMaps."  

I implemented a proposal for flatmap in a fork of underscore's source, along with a few unit tests for your consideration. I don't have docco running and I didn't produce a "min" version of the javascript, so it's just the javascript and the unit tests. https://github.com/rebcabin/underscore/commit/4f90bab75d8f69df8d8d0317354f9f5981e2fedb

**Comment by AlexGalays** [comment]
@inca, Or use ramda:   http://ramdajs.com/docs/R.html#chain

**Comment by eirirlar** [comment]
+1

**Comment by pfultz2** [comment]
Well, `flatMap` is very fundamental, more so than `filter` and `map`(especially since they can be implemented using `flatMap`). I just don't understand the rejection of basic list comprehension.

> Needing a recursive flatten is what is uncommon. 

Exactly. List comprehension(ie `flatMap`) is much more common than recursive flatten.

**Comment by inca** [comment]
I'm with you, my friends :smile:

**Comment by AlexGalays** [comment]
flatMap is a very basic tool in one FP programmer's tool belt. It wouldn't hurt to peek at what other languages have.

**Comment by arcseldon** [comment]
Would recommend readers interested in flatMap also take a look at Ramda - some of the core contributors were originally involved with Underscore.js. Very well thought out JavaScript library for functional programmers, with auto-currying of much of the API methods which makes composing functions easy to do. 
Here is an implementation of [Chain](http://ramdajs.com/ramdocs/docs/R.html#chain) - equivalent to flatMap).

**Comment by QuotableWater7** [comment]
+1 to `flatMap`
