### ISSUE TITLE
Treatment of negatives: _.isEqual(-1 * 0, 0) returning false

### ISSUE THREAD

**Issue by brahn** [jashkenas/underscore#490]
Using Underscore v.1.3.1, reproduced on the mac in up-to-date Chrome (17.0.963.56) and Firefox 7.0:

``` javascript
0 === -1 * 0
> true

_.isEqual(0, -1 * 0)
> false
```

This is surprising, at least to me.  Bug, or am I missing something?

Thanks!

**Comment by peterjeliot** [comment]
I know this is a very, very old issue, but I found it on google, so I guess it's still relevant.

Considering that Javascript considers 0 to equal -0 (using == or ===), shouldn't _.isEqual do the same? I thought isEqual was meant to be a more permissive version of ==, specifically for addressing the fact that arrays and objects can't be compared.

The inclusion of extra pickiness with signs on zeros doesn't seem like it fits the purpose of the function (and indeed, meant that I couldn't use it).

**Comment by michaelficarra** [comment]
@peterjeliot: `_.isEqual` has a much different notion of equality than `==` or `===` or `Object.is`. With primitives, it is very strict, like `Object.is`, but with objects it is even looser than `==`. If it was the same as any of those, there would be no need for it.

**Comment by peterjeliot** [comment]
Is there a method out there that can compare objects deeply without the increased scrutiny of primitives? I would like to have the well-engineered recursiveness of isEqual, but I still want -0 to equal 0.

The problem I was running into was when _.isEqual([0,1], [-0,1]) returned false. (The -0 was generated by inverting the values of [0, -1])
