### ISSUE TITLE
_.delay has no option to bind "this", and instead binds "this" to called function, which is useless

### ISSUE THREAD

**Issue by dgbeck** [jashkenas/underscore#494]
_.delay is incompatible with _.bind and _.bindAll.

Since _.delay calls its target function "func" with:

 func.apply(func, args);

any object that was previously bound to func using _.bind or _.bindAll will not be "this" when func is called. Many other underscore functions have a special parameter for "this".. why not _.delay? Moreover, it seems totally useless to me to have "this" be a reference to the function itself. Why not just call func directly, instead of using "apply", and then not mess with the value of "this"? Am I missing something? Here is code for the _.delay function for reference purposes:

_.delay = function(func, wait) {
     return setTimeout(function(){ return func.apply(func, args); }, wait);
};

**Comment by jeff-h** [comment]
I don't understand how we can call this "fixed". The various solutions in the comment above all appear very unreadable to me.

The change in https://github.com/jashkenas/underscore/commit/1366d903332fc2af1560c2c45b4fac5e6c75719b simply stops sending an odd context to the called function.

Is there a reason `delay` can't take a `context` argument as per https://github.com/jashkenas/underscore/issues/494#issuecomment-4886842 ? That, to me, would be awesome :)

**Comment by jridgewell** [comment]
There's no reason to change `_.delay`. If you want a context, bind it beforehand.

```javascript
_.delay(_.bind(func, context), 500)
```

**Comment by jeff-h** [comment]
Thanks! I should have tried that I guess, but assumed wrongly based on the complexity of the above answers that something more complicated was needed.
