### ISSUE TITLE
Deep pluck feature

### ISSUE THREAD

**Issue by mohsen1** [jashkenas/underscore#712]
Can underscore pluck have a deep pluck feature to do this:

```
_([{o:{a:1}},{o:{a:43}},{o:{a:234}},{o:{a:23}}]).pluck("o.a")
```

**Comment by chevex** [comment]
grumble grumble

**Comment by dandv** [comment]
underscore has a change of being [better than lodash](https://github.com/lodash/lodash/issues/262#issuecomment-113151010).

**Comment by chevex** [comment]
Just found lodash-deep after I complained here. Thanks for reinforcing that choice :)

And thanks to Underscore for reinforcing our choice to switch to lodash :P

**Comment by mohsen1** [comment]
[I made a `_.deepPick` back then](https://github.com/mohsen1/deep_pick)

**Comment by dandv** [comment]
@chevex: lodash-deep is a 3rd party module, because [lodash also refused to implement deepPluck](https://github.com/lodash/lodash/issues/262#issuecomment-17410875). Maybe [there's a reason for this](http://programmers.stackexchange.com/questions/291966/why-is-deep-plucking-a-bad-idea).

**Comment by jdalton** [comment]
@dandv ffs Dan reread the thread you linked to. Lodash has had deep pluck since 3.7.0.

**Comment by chevex** [comment]
That ^

Lol

**Comment by dandv** [comment]
@jdalton That is quite funny because I linked to [your comment](https://github.com/lodash/lodash/issues/262#issuecomment-17410875) saying 

> I still think something that walks namespace string, e.g. a.b.c, has a place just not in Lo-Dash core.
It would be great to see a mixin or lib that specializes in this kind of API sugar.

before closing the thread. Now I see the link in my post goes a few comments down the thread, and unless a cosmic ray hit my laptop, I didn't link there.

**Comment by jdalton** [comment]
> Now I see the link in my post goes a few comments down the thread

Glad that's all cleared up.

>  I didn't link there. It would've been silly. Also,
> ![image](https://cloud.githubusercontent.com/assets/33569/9105129/89f3212a-3bc9-11e5-91d7-d6444919e66a.png)

Yap, to hopefully reduce confusion in the future.

> Anyway, I'm happy deep plucking is supported in lodash via `_.map(collection, 'a.b.c')`.

Deep property support is also available in [several other methods](https://github.com/lodash/lodash/wiki/Changelog#v370).
