### ISSUE TITLE
New functions: dropWhile and sliding

### ISSUE THREAD

**Issue by sroebuck** [jashkenas/underscore#714]
Named after their implementations in the Scala collections libraries http://www.scala-lang.org/archives/downloads/distrib/files/nightly/docs/library/index.html#scala.collection.Seq, here are two additional functions if others would benefit from them:

```
_.mixin({
  dropWhile: function(array, f) {
    var indexOfMatch, match;
    match = _.find(array, function(x) {
      return !f(x);
    });
    console.log("match = " + match);
    if (match) {
      indexOfMatch = array.indexOf(match);
      return array.slice(indexOfMatch);
    } else {
      return [];
    }
  },
  sliding: function(array, window) {
    var end, i, _i, _results;
    end = array.length - window;
    _results = [];
    for (i = _i = 0; 0 <= end ? _i <= end : _i >= end; i = 0 <= end ? ++_i : --_i) {
      _results.push(array.slice(i, (i + window - 1) + 1 || 9e9));
    }
    return _results;
  }
});
```

**Comment by w0rp** [comment]
I found this in a Google search. You should consider adding `dropWhile` to underscore.js. It's a common algorithm. It's an inverted `find_if` as in C++. (or just find_if_not in C++11) http://en.cppreference.com/w/cpp/algorithm/find It's also named `dropwhile` in Python. https://docs.python.org/2/library/itertools.html#itertools.dropwhile

You can use it for any case where you need to find every element on or after a particular elemenet. I was just writing some JavaScript code with underscore JS and I ended up writing a for loop with a boolean tracking whether or not I hit the match to get what I needed done. It's nicer with a `dropwhile` algorithm.
