### ISSUE TITLE
_.isNaN(new Number(NaN)) should return true

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#749]
`_.isNaN(new Number(NaN))` should return `true` because it's handled in `_.isEqual(NaN, new Number(NaN)); // => true` that way.

**Comment by davidchambers** [comment]
For what it's worth [`Number.isNaN`][1] behaves differently:

```javascript
> Number.isNaN(NaN)
true
> Number.isNaN(new Number(NaN))
false
```


[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

**Comment by roy-lau** [comment]
_.isNaN(new Number(0));
// true
