### ISSUE TITLE
find from the end

### ISSUE THREAD

**Issue by arieljake** [jashkenas/underscore#869]
in the case of a chronological list, in some cases it makes sense to find the first record passing a truth test starting from the end of the list (most recent).

yes, you can reverse the list, but if it is a very long list, that is a painful performance hit.

suggestion:

_.find(list, iterator, [context], [fromEnd]) where 'fromEnd' is a bool

**Comment by jaridmargolin** [comment]
For anyone else who stumbles on this, #1981 introduces `findLastIndex` which can be used.
