### ISSUE TITLE
Template's 'new Function' blocked by CSP

### ISSUE THREAD

**Issue by bruun** [jashkenas/underscore#906]
The template rendering causes a CSP error, violating the unsafe-eval property: http://www.w3.org/TR/CSP/#script-src

render = new Function(settings.variable || 'obj', '_', source);

This was pointed out, and fixed, in Mustache a few months back: https://github.com/cweider/mustache.js/commit/dac64709f0458cc58caea724eaae2cf521e14c01

**Comment by jvoisin** [comment]
@jdalton Care to elaborate about how to "precompile your templates"?
I'd like to close [this]( https://trac.torproject.org/projects/tor/ticket/21230 ) Tor project issue ASAP.
Thank you :)

**Comment by jdalton** [comment]
@jvoisin One option is to use [lodash-cli](https://lodash.com/custom-builds). For support on that head over to their [gitter chat](https://gitter.im/lodash/lodash).
```shell
lodash template="./*.jst" settings="{interpolate:/\{\{([sS]+?)\}\}/g}"
```
